### ISSUE TITLE
gulp-helpers showing up?

### ISSUE THREAD

**Issue by lookfirst** [tjunnone/npm-check-updates#102]
Using latest unstable...

npm-check-updates
You can now use "ncu" for less typing!

"babel" satisfies current dependency (Installed: 5.6.14, Latest: 5.8.3)
"babel-core" satisfies current dependency (Installed: 5.6.20, Latest: 5.8.3)
"gulp-helpers" satisfies current dependency (Installed: 2.0.6, Latest: 2.0.6)
"karma-jspm" can be updated from ^2.0.0-beta.1 to ^2.0.1-beta.1 (Installed: 2.0.0-beta.1, Latest: 2.0.1-beta.1)

Not really sure why gulp-helpers showed up in that list given the two numbers reported are the same.

It is only installed locally.

**Comment by metaraine** [comment]
Agreed. v2 will have a colored table output that will be much clearer.

**Comment by metaraine** [comment]
#94

**Comment by lookfirst** [comment]
I'm not quite sure how a colored table is the issue here. 

What I'm describing is the fact that gulp-helpers is listed as 2.0.6 in my package.json and the current version is 2.0.6. 

Why, out of all the dependencies in my package.json, is it being listed in the output at all?

**Comment by metaraine** [comment]
It is because the listed dependencies is probably less than 2.0.6 (e.g. ^2.0.5) but the installed version is 2.0.6 due to semver rules. It is technically a different version, but it satisfies the semver constraint, so it is not a problem.

**Comment by lookfirst** [comment]
Ah, ok... well, that is super confusing...

**Comment by metaraine** [comment]
You're right... will be fixed.
