### ISSUE TITLE
Cache betweens multiple calls

### ISSUE THREAD

**Issue by theaqua** [tjunnone/npm-check-updates#103]
Hi, big thanks for this package, it's really useful!

I have idea for small enhancement. I often use `ncu` with this way: 

    ➜  frontend git:(develop) npm-check-updates
I check list of available updates. If I have major update in any package, I didn't update before read about changes.

then I run

    ➜  frontend git:(develop) npm-check-updates -u

for update. But `ncu` didn't cache calls and it runs again. My proposal: save path & result for 10 minutes and load from cache when `ncu` runs second time.

**Comment by metaraine** [comment]
Hi! I can see how running it a second time would be really slow if you have a lot of dependencies. I am hesitant to introduce caching. If a cached version is ever incorrect, it creates a lot of confusion. I'd rather avoid that.

An interim solution would be to use the --jsonAll or --jsonUpgraded flag to output a new package.json and examine the results:

```bash
ncu --jsonAll > newpkg.json
# evaluate newpkg.json
mv newpkg.json package.json
npm install
```

Or easier to see the specific differences by using git:
```bash
# make sure all changes are committed
ncu --jsonAll > package.json
git diff # evaluate diff
npm install
```
