### ISSUE TITLE
Option to exclude/ignore package update

### ISSUE THREAD

**Issue by theaqua** [tjunnone/npm-check-updates#104]
If I have major update that breaks my app, I don't want at this moment update it. I think, ability to run `ncu -u --exclude browserify` will be very useful.

**Comment by metaraine** [comment]
This can be done! It's a little awkward-looking but it's just a regex filter.

In v1.5.1:

```bash
ncu -f '/^(?!browserify)$/'
```

In upcoming v2 (usable now via `npm install -g npm-check-updates@unstable`):

```bash
ncu '/^(?!browserify)$/'
```

**Comment by theaqua** [comment]
Great, thanks!

**Comment by jlbruno** [comment]
+1 for the original request because regex.

**Comment by groundrace** [comment]
with recent versions > 2 you can using something like:

`ncu -x 'pattern'`

**Comment by RichardWilburn** [comment]
ncu -x '*react-*' - u in my case worked for excluding react upgrades. Thanks @groundrace
