### ISSUE TITLE
Send output in the callback instead of stdout when ncu is used as a module

### ISSUE THREAD

**Issue by Skywalker13** [tjunnone/npm-check-updates#108]
Hello,

your module is great and useful but something is a bit annoying when it's used as a module.

For example:

```js
ncu.run ({
  jsonUpgraded: true
}).then (function (err, output) {
  console.log (output);
});
```

jsonUpgraded is really useful, but the output is in the stdout; IMHO it should be sent to the callback like the code above.

Regards

**Comment by metaraine** [comment]
I totally agree. Let me investigate.

**Comment by metaraine** [comment]
Fixed!

From the documentation:

```
var ncu = require('npm-check-updates');

ncu.run({
    packageData: fs.readFileSync('./some/project/package.json', 'utf-8'),
    // Any command-line option can be specified here.
    // These are set by default:
    // silent: true,
    // jsonUpgraded: true
}).then(function(upgraded) {
    console.log('dependencies to upgrade:', upgraded);
});
```

Note that `run` returns a Promise, so you have to use the [Promise convention](http://promise-nuggets.github.io/articles/01-the-simplest-example.html) rather than the node callback convention:

```
ncu.run().then(function (output) {
  console.log(output);
}, function(err) {
  console.log(err);
});
```

**Comment by Skywalker13** [comment]
Cool
Thanks!
