### ISSUE TITLE
Despite outdated packages, ncu does not output any package to update

### ISSUE THREAD

**Issue by msieurtoph** [tjunnone/npm-check-updates#110]
Hi,

Here are my `devDependencies` (no prod dependency in my project) :

```json
...
  "devDependencies": {
    "angular": "^1.4.3",
    "angular-mocks": "^1.4.3",
    "grunt": "^0.4.5",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-karma": "^0.11.2",
    "jshint-stylish": "^2.0.1",
    "karma": "^0.12.37",
    "karma-coverage": "^0.4.2",
    "karma-jasmine": "^0.1.6",
    "karma-phantomjs-launcher": "^0.2.0",
    "karma-spec-reporter": "0.0.20",
    "load-grunt-tasks": "^3.2.0",
    "phantomjs": "^1.9.17",
    "time-grunt": "^1.2.1"
  }
...
```

`npm outdated` gives me :

```
$ npm outdated
Package        Current   Wanted  Latest  Location
grunt-karma     0.11.2   0.11.2  0.12.0  grunt-karma
karma-jasmine    0.1.6    0.1.6   0.3.6  karma-jasmine
karma          0.12.37  0.12.37  0.13.3  karma
```

but `ncu` does not show anything.

Did I miss something when using your module? 
It seems to big to be an issue? Especially if I am the only one to face it.

For the record, I am using `npm_lazy` (local registry mirroring).
But when I tried `ncu -r http://registry.npmjs.org/` or `ncu -r  http://localhost:8088/` (my local mirror), or even to shutdown and by-pass my mirror, it did not show anything neither ...

**Comment by metaraine** [comment]
You are right, that is a big issue!

The defaults for when ncu is run as a module were accidentally applied when run on the cli. 

Fixed in `v2.0.1`.

Thanks, and sorry for the inconvenience!

**Comment by floydpink** [comment]
+1 - thanks for the quick fix!

**Comment by msieurtoph** [comment]
+1. Really quick fix! Thx.
