### ISSUE TITLE
Updated version of a module is not detected

### ISSUE THREAD

**Issue by 4kochi** [tjunnone/npm-check-updates#112]
<img width="570" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1742426/8952767/3fd2e2f0-35da-11e5-8058-620970de0941.png">

You can test it with the following repo: https://github.com/litixsoft/baboon-frontend

**Comment by metaraine** [comment]
Thanks, I will investigate

**Comment by metaraine** [comment]
In your repo, the declared dependency of karma-mocha is `*`, so you can simply run `npm update` to install newer versions. `npm-check-updates` is primarily for rewriting dependencies in your package.json that have a newer version beyond the given semver constraint. This allows you to have more control over when potentially breaking 3rd party changes are integrated into your codebase.

Specifying a dependency of `*` is not recommended, even for devDependencies, as updates may be backwards-incompatible, breaking your local build process. The recommended approach is to specify versions using syntax like `^1.0.0`, and run `ncu` when you have time to verify that a newer major version does not break your codebase.

**Comment by 4kochi** [comment]
Ah sorry, totally missed that. Stars are bad and i will replace them. Thanks.
