### ISSUE TITLE
Linting, style and CI discussion

### ISSUE THREAD

**Issue by etiktin** [tjunnone/npm-check-updates#115]
As the project grows and more people contribute, it becomes harder to maintain a consistent style and quality. I think we should consider adding automatic linting and style check to the test stage.

I don't think it matters which linter and coding style we use as long that it's consistent. The main goal is to make it easy for contributors to jump in and start contributing.

Also it seems that the Travis CI isn't working, which is a shame because it can give the contributor and the maintainer a fast indicator that something is wrong.

**Comment by metaraine** [comment]
Thank you for this suggestion. I agree it is about time for linting!

Can you suggest a good path towards this? Tools, config files, etc. I do not currently have linting in my workflow.

Also, I have contacted @tjunnone to get Travis CI working. Since the repo is in his account, he will have to enable Travis.

**Comment by etiktin** [comment]
The popular linter these days is [ESLint](http://eslint.org/). JSHint is also good (I still use it for most of my projects).
There's a bunch of configurations on npm. I'll try to find one that makes sense for us.
There's also a project called [standard](https://www.npmjs.com/package/standard) that enforces a set of rules with no need for configuration, but I find some of it's choices too controversial (e.g. no semicolons are allowed), so I don't think we should use it.

**Comment by metaraine** [comment]
Cool, ESLint sounds like it could be good.

**Comment by etiktin** [comment]
In PR #121 I added ESLint configuration and fixed the errors it found. 
It's really easy to change a rule from error to warning or remove it completely if necessary. So we can perfect it during the work on future PRs.

**Comment by metaraine** [comment]
Awesome! Thanks for the help! Published in `v2.1.3`

**Comment by etiktin** [comment]
Is there any news about the travis setup?

**Comment by metaraine** [comment]
Emailed @tjunnone directly and haven't heard back from him yet.

**Comment by tjunnone** [comment]
Sorry for the late reply, Travis is now hooked up to the repo. Nice work!

**Comment by etiktin** [comment]
Awesome! Thanks :+1:
