### ISSUE TITLE
Ignore github dependencies

### ISSUE THREAD

**Issue by silverwind** [tjunnone/npm-check-updates#12]
My package.json has

````js
    "codemirror": "marijnh/CodeMirror.git#v4"
````

When running `npm-check-updates -u` it seems to want to downgrade me to the latest relase, on a nonexistant branch:
````
"codemirror" can be updated from marijnh/CodeMirror.git#v4 to marijnh/CodeMirror.git#v3 (Installed: 4.0.0, Latest: 3.22.0)
````

Shortly after, I get

````
npm ERR! notarget No compatible version found: codemirror@'marijnh/CodeMirror.git#v3'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.33.0","3.14.1","3.15.0","3.16.0","3.17.0","3.18.0","3.19.0","3.20.0","3.21.0","3.22.0","3.11.1","3.12.0","3.13.0"]

````
CodeMirror right now only has these branches: v4, v2, master.

**Comment by metaraine** [comment]
Version patterns to ignore:
- `git://github.com:RichardLitt/rangy.git#748582f `
- `RichardLitt/rangy.git`
- `git+ssh://git@bitbucket.org:org/project`

**Comment by metaraine** [comment]
Fixed in v2!
