### ISSUE TITLE
add compatibility with "next" releases

### ISSUE THREAD

**Issue by gr2m** [tjunnone/npm-check-updates#125]
When I run `npm-check-updates` in one of my projects, I get this

```
$ npm-check-updates
"semantic-release" can be updated from ^4.0.2 to ^3.3.2 (Installed: 4.0.3, Latest: 3.3.2)
```

The reason is that semantic-release@3.3.2 is the latest, but 4.02 is published under the "next" tag. In that case, I would suggest that npm-check-updates does not recommend to "downgrade" to the latest version, as it is below the currently installed one.

**Comment by metaraine** [comment]
I agree! Can you confirm the version of npm-check-updates you are using?

```sh
$ ncu -V
2.2.0
```

**Comment by gr2m** [comment]
@metaraine I'm so sorry, I didn't update first. I was on version 1.5, it works correctly in 2.2.0 :+1: sorry for the noise!

**Comment by metaraine** [comment]
No problem! Glad it's working.
