### ISSUE TITLE
Add extra column: URL of package repo

### ISSUE THREAD

**Issue by superclarkk** [tjunnone/npm-check-updates#129]
Great work on this project - it's very useful!

This is an enhancement request. I've seen #76, but I feel a better solution would be to simply list the repo URL by each package. Then, the user could simply click on it to quickly get access to the changelog, the history, or the actual code changes, before updating the package.

**Comment by superclarkk** [comment]
Of course, `npm repo pkgname` works fine, but maybe not quite as convenient.

**Comment by metaraine** [comment]
Thanks for the suggestion!

I see how this would be a more convenient way to examine release notes.

I value the simplicity of this lib, and the minimalist output, so I am hesitant to add anything unless there is significant additional value.

At the moment I consider this low priority, but I'll keep this open for a bit in case others have different opinions.

**Comment by ustun** [comment]
I think this would be a good addition. Most of the time, I run `ncu`, then do a Google search for releases for that repo. If ncu could output the release url of each repo, it would same me some time.
