### ISSUE TITLE
ncu upgrades to a pre-release version when released under the latest tag

### ISSUE THREAD

**Issue by sanemat** [tjunnone/npm-check-updates#131]
I'm not sure this is a bug or `gulp-load-plugins` package's issue.

I run `ncu -u`, then I get below:

```diff
(snip)
-    "gulp-load-plugins": "^0.8.0",
+    "gulp-load-plugins": "^1.0.0-rc.1",
```

https://github.com/sanemat/node-logentries-retrieving-log/commit/1b6b3b87f98eeb0ffa4eb32031d19f1143dff69b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L23

```
$ npm view gulp-load-plugins dist-tags
{ latest: '1.0.0-rc.1', beta: '0.6.0-beta' }
```

But I install `gulp-load-plugins` manually, then I install `v0.10.0`. 

```
$ npm i gulp-load-plugins
gulp-load-plugins@0.10.0 node_modules/gulp-load-plugins
├── multimatch@2.0.0 (array-differ@1.0.0, array-union@1.0.1, minimatch@2.0.10)
└── findup-sync@0.2.1 (glob@4.3.5)
```

I don't add `-t/--greatest` option.

Is this `gulp-load-plugins` package's problem? Or npm-check-updates has wrong check logic?

My environment:
```
$ npm view gulp-load-plugins versions
[ '0.2.0',
  '0.3.0',
  '0.4.0',
  '0.5.0',
  '0.5.1',
  '0.5.2',
  '0.5.3',
  '0.6.0-beta',
  '0.6.0',
  '0.7.0',
  '0.7.1',
  '0.8.0',
  '0.8.1',
  '0.9.0',
  '0.10.0',
  '1.0.0-rc.1' ]
$ npm -v
2.14.2
$ cat node_modules/npm-check-updates/package.json |grep version
  "version": "2.2.2",
```

**Comment by metaraine** [comment]
After [some investigating](https://github.com/npm/npm/issues/8672), I found that npm does not install pre-release versions if you don't specify a version number or tag. It's meant to be more intuitive, preventing people from unintentionally installing pre-release versions, but it is not well-documented currently (The [tag config](https://docs.npmjs.com/misc/config#tag) docs say the default is `latest`, with no mention of the pre-release special case).

Thus, `npm install gulp-load-plugins` will install `0.10.0` (the latest version that is not a prerelease), and `npm install gulp-load-plugins@latest` will install `1.0.0-rc.1` (the actual latest tag). 

`npm-check-updates` uses the latter (explicit latest).

**Comment by sanemat** [comment]
Thanks! I understand.
