### ISSUE TITLE
`$ ncu -a` issue

### ISSUE THREAD

**Issue by gsklee** [tjunnone/npm-check-updates#134]
I have some dependency `some@1.0.2` while that latest version of `some` being v1.0.4:

```javascript
"some": "1.0.2"
```

When I tried to update my `package.json` using `$ ncu -a`, I was expecting that the above line be left as-is, but it turned out `ncu` will update that line to:

```javascript
"some": "1.0.4"
```

Is this intended or a bug?

**Comment by metaraine** [comment]
If you have a fixed version number such as `1.0.2` (i.e. not a range such as with `~` or `^`), then `ncu` will upgrade to any higher latest version that has been published. This is the intended behavior for both `-u` and `-a`.

It gets slightly more complex with ranges. Consider if you list `^1.0.2` in your package.json. A latest version of `1.0.4` *satisfies* the specified version range, thus you only need to run `npm update`, and `ncu -u` (`--upgrade`) will not modify your package.json. (However, it will give you a friendly message to suggest running `npm update` if the installed version is behind.) 

Some people really want the *latest* version listed in their package.json (even though IMHO it is not necessary). In this case, they may run `ncu -a` (`--upgradeAll`), which modifies the package.json even if the currently specified version satisfies the latest.

**Comment by gsklee** [comment]
@metaraine Okay, so... Is there anyway to lock my dependency to certain version while also being able to use `ncu` from time to time...? I know one possible way is to specify version using the hash instead, but for some ill-maintained libraries it's very hard to find out which version corresponds to which commit hash sometimes.

**Comment by metaraine** [comment]
ncu is intended to upgrade to latest versions. I'm not sure what your use case is. [semver](semver.org) seems to handle dependency hell/versioning issues just fine in my experience.

That said, perhaps you can get what you want by using filtering, specifying which dependencies you want to force upgrade or not:

```bash
# match packages that do not start with "gulp-". Note: single quotes are required
# here to avoid inadvertant bash parsing
$ ncu '/^(?!gulp-).*$/'
```

**Comment by gsklee** [comment]
@metaraine Interesting, thanks!
