### ISSUE TITLE
on OSX, ncu and npm-check-updates commands remain unavailable after npm install -g npm-check-updates

### ISSUE THREAD

**Issue by Jon007** [tjunnone/npm-check-updates#135]
Hi, it sounds good but how do you make the command-line tool available, as the specified instruction doesn't seem to do it?

JPMPRO:~ jon$ sudo npm install -g npm-check-updates
Password:
/usr/local/Cellar/node/4.1.0/bin/npm-check-updates -> /usr/local/Cellar/node/4.1.0/lib/node_modules/npm-check-updates/bin/old-alias
/usr/local/Cellar/node/4.1.0/bin/ncu -> /usr/local/Cellar/node/4.1.0/lib/node_modules/npm-check-updates/bin/npm-check-updates
npm-check-updates@2.2.3 /usr/local/Cellar/node/4.1.0/lib/node_modules/npm-check-updates
├── async@1.4.2
├── closest-package@1.0.0
├── fast-diff@1.0.1
├── semver-utils@1.1.0
├── semver@5.0.3
├── cint@8.2.1
├── bluebird@2.10.0
├── lodash@3.10.1
├── npm@3.3.3
├── get-stdin-promise@0.1.1 (get-stdin@3.0.2, rsvp@3.1.0)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── cli-table@0.3.1 (colors@1.0.3)
├── json-parse-helpfulerror@1.0.3 (jju@1.2.1)
└── chalk@1.1.1 (ansi-styles@2.1.0, escape-string-regexp@1.0.3, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
JPMPRO:~ jon$ ncu
-bash: ncu: command not found
JPMPRO:~ jon$ npm-check-updates
-bash: npm-check-updates: command not found
JPMPRO:~ jon$

**Comment by Jon007** [comment]
oops, found this one later in node_modules/npm-check-updates/bin/  .. but it wasn´t there first time I looked and didn´t get onto the path

**Comment by metaraine** [comment]
Glad you figured it out!

**Comment by KingGeneral** [comment]
how you fix this one @Jon007  ??

**Comment by Jon007** [comment]
it was user error as far as I remember
