### ISSUE TITLE
ncu is not compatible with npm@3.3

### ISSUE THREAD

**Issue by mrhyde** [tjunnone/npm-check-updates#137]
After updating to node 4.1 and npm 3.3 I encountered a bug in `ncu` which is probably related to the fact that npm@3.3 flatten all deps
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'graceful-readlink'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\utils\opt\nodejs\node_modules\npm-check-updates\node_modules\commander\index.js:8:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I tried to reinstall module dependencies manually but even if `graceful-readlink` is present in node_modules directory I'm still having error

node_modules structure with npm@3.3
```
\node_modules\npm-check-updates> npm list| grep readlink
│ └── graceful-readlink@1.0.1
│ │ │ │ │ └── graceful-readlink@1.0.1
```

Rolling back to npm@2.14.5 fixes an issue and `ncu` works again
```
\node_modules\npm-check-updates> npm list| grep readlink
│ ├── graceful-readlink@1.0.1
│ │ │ │ └── graceful-readlink@1.0.1
│ │ └── graceful-readlink@1.0.1
│ │ ├── graceful-readlink@1.0.1

**Comment by metaraine** [comment]
Thanks for reporting! What version of `ncu` are you using?

If your dependencies are installed with npm@2, and are not flattened, does npm@3 properly handle converting the structure to the flattened version? i.e. Does the problem exist when dependencies were installed with a different version of npm? If you haven't already, try deleting your `node_modules` folder, switching to npm@3, running `npm install`, and *then* running `ncu`.

Internally `ncu` uses `npm@3.3.3`. It only uses the `load`, `list`, and `view` commands. Everything else is just text parsing of the package.json, so I'm not sure where that error would come from.

**Comment by MrHyde** [comment]
Unfortunately (or actually fortunately) I'm not being able to reproduce this bug anymore.
Tried everything I did yesterday (fresh install, npm install etc) - everything works.
Apparently it was related to npm registry or internet connection issues. Weird...

Sorry for your time, i think we can close this one.

**Comment by metaraine** [comment]
> The only thing worse than knowing why software is not working, is not knowing why it is working.

;)
