### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by etiktin** [tjunnone/npm-check-updates#141]
What do you think about adding the [`update-notifier`](https://www.npmjs.com/package/update-notifier) module to `ncu`?

The idea is that when you run `ncu` through the cli, the module will check with npm, if there's an update to `ncu`. If there is an update it will print a notification to the console (see screenshot in the module page).
If the users are using recent versions, it means they get bug fixes faster and it will be easier to provide support when an issue arises.

**Comment by metaraine** [comment]
Yes, I like it!!!
