### ISSUE TITLE
Add cli alias for Bower

### ISSUE THREAD

**Issue by etiktin** [tjunnone/npm-check-updates#151]
I  think that it will be nice if we offer a command to run ncu for bower. So instead of `ncu -m bower`, you could run `bcu` (or some other agreed upon alias).

What do you think?

**Comment by metaraine** [comment]
I'm not sure. Strictly speaking the `ncu` shortcut is unnecessary, but it gets everyone on the same page without them all having to create their own alias.

Those that use bower should be capable of creating an alias themselves:

```
alias bcu="ncu -m bower"
```

May be obviated by the decision on #148.

**Comment by etiktin** [comment]
I think that if we decide to separate the modules, it will take some time (unless if we just duplicate everything for a start). So I think it's still relevant.

It's easy to create an alias if you know how and you live in the terminal, but I'm not sure it's true to all users. For example on Windows, I know very few people that know how to create an alias in cmd (it's done by the `doskey` if anyone is wandering).

It's a small thing, but I think it improves the experience.

**Comment by listepo** [comment]
+1 rename ```npm-check-updates``` to ```package-check-updates``` for npm and bower ```ncu``` & ```bcu``` bin
