### ISSUE TITLE
v3 is slow

### ISSUE THREAD

**Issue by metaraine** [tjunnone/npm-check-updates#152]
Some people are reporting that v3 is slower than v2. Needs to be investigated.

**Comment by metaraine** [comment]
Adding `--depth 0` to the `npm ls` command resulted in a 3x speed increase (v2.5.3).

**Comment by raineorshine** [comment]
This issue was not the same reason for the recently published v3.0.0's performance issues. This has now been addressed thanks to @stoically and published in v3.0.5.
