### ISSUE TITLE
metaraine/semver-utils Github dependency

### ISSUE THREAD

**Issue by treythomas123** [tjunnone/npm-check-updates#157]
[This dependency](https://github.com/tjunnone/npm-check-updates/blob/2632e09f14a1e898e79a734f6307ad3725a870ac/package.json#L56) on the Github repository `metaraine/semver-utils` makes this package difficult to install within my company's secure environment, which has an NPM mirror inside it but no internet access or mirror of Github.

Can the changes on this fork of the [semver-utils npm package](https://www.npmjs.com/package/semver-utils) be added to the original [semver-utils repo](https://github.com/coolaj86/semver-utils)?

I noticed [this issue](https://github.com/coolaj86/semver-utils/issues/3) hasn't gotten any attention, but a pull request might.

Edit: I missed the [pull request already submitted](https://github.com/coolaj86/semver-utils/pull/2) for this. I'll leave this here anyway, just to call attention to the issue of this being inconvenient to install without Github access.

**Comment by treythomas123** [comment]
[Pull request got merged](https://github.com/coolaj86/semver-utils/pull/2), so this is resolved! Closing.

**Comment by metaraine** [comment]
Thanks!!! Yes, I've been waiting quite a while for that PR to be merged.

**Comment by treythomas123** [comment]
Sure! They already published the a new version on NPM, so I just wrote [this PR](https://github.com/tjunnone/npm-check-updates/pull/158) to switch the dependency in npm-check-updates.

**Comment by metaraine** [comment]
Thanks! Looks like we were doing it at the same time :). Published in v2.3.3.
