### ISSUE TITLE
Is there an option to upgrade to the latest minor version of the current dependency?

### ISSUE THREAD

**Issue by jduprey** [tjunnone/npm-check-updates#159]
If my package.json has a dependency, depAbc, with version 4.0.1.  NCU would upgrade to the latest version < 5.0.0.  I realize this is the same as specifying ^4.0.1.  So maybe ncu -u would change the package.json to be:

```
depAbc: ^4.7.5
```

**Comment by metaraine** [comment]
If you have a dependency `"depAbc": "4.0.1"`, ncu will upgrade to the **latest version** (even if > 5.0.0). ncu will always upgrade to the latest (or `--greatest`) version. If you are not wanting to force versions to the latest, it is generally assumed that you are wanting to stay within your version constraints, and should just use `npm update` to get the latest version *within* the specified constraint. Does that answer your question?

**Comment by jduprey** [comment]
Yes.  That makes sense.  Thank you.

**Comment by medikoo** [comment]
`npm update` doesn't address it really.

`npm update` updates package.json _only_ if (1) given package is installed in `node_modules` and (2) is installed at version lower than latest as supported by range.

In many cases it'll be already installed in `node_modules` at latest supported, that won't force an update to `package.json`. Clearing `node_modules` also doesn't help as then (1) is not satisfied

**Comment by testerez** [comment]
Old issue but `ncu -u -t minor` does that.
