### ISSUE TITLE
Why is this package necessary having $npm outdated?

### ISSUE THREAD

**Issue by davidpelayo** [tjunnone/npm-check-updates#160]
So, any gain on using this package?

I just realized talking with a coworker.

**Comment by metaraine** [comment]
Hi David, thanks for the question.

The main points I can think of:
- npm-check-updates does not just tell you which packages have newer versions, but rewrites your package.json with the latest versions.
- npm-check-updates maintains existing version constraints, e.g. `^2.3.1 → ^3.0.0` or `2.3.1 → 3.0.0` or `~2.3.1 → ~3.0.0`.
- Works with global packages ([supposedly](https://github.com/tjunnone/npm-check-updates/issues/146)).
- Advanced options for selectively upgrading packages, outputting JSON, integrating into CI, etc
