### ISSUE TITLE
'ncu -m bower' doesn't honour #latest release

### ISSUE THREAD

**Issue by aroncal** [tjunnone/npm-check-updates#170]
It goes to the newest version available in the github project, even if the one tagged as "#latest" is a previous version.

A couple of examples:

(https://github.com/jtblin/angular-chart.js/releases) : #latest is 0.8.4, newest 0.8.5
(https://github.com/MrRio/jsPDF/releases) : #latest is v1.0.272, newest v1.1.135

bower.json:

```json
{ 
  "name: "test", 
  "version" : "0.1",
  "dependencies" : {
    "angular-chart.js" : "~0.7.0",
    "jspdf" : "~1.0.272"
  }
}
```

```
> ncu -m bower
  angular-charts.js       ~0.7.0 -> ~0.8.5
  jspdf                          ~1.0.272 -> ~1.1.135
```

**Comment by metaraine** [comment]
Thanks, I will investigate.

**Comment by metaraine** [comment]
Turns out this is the default behavior of bower. It goes straight to the newest version from the repo. It does not honor release tags like npm.

```
$ bower info jspdf
bower cached        git://github.com/MrRio/jsPDF.git#1.1.135
bower validate      1.1.135 against git://github.com/MrRio/jsPDF.git#*

{
  name: 'jspdf',
  version: '1.1.135',
  ...
}
```

This differs from npm:

```
$ npm view jspdf version
1.0.272
```
