### ISSUE TITLE
Unnecessary `async` dependency?

### ISSUE THREAD

**Issue by joepie91** [tjunnone/npm-check-updates#175]
Currently, `package.json` [lists `async` as a dependency](https://github.com/tjunnone/npm-check-updates/blob/1e616bdd9bc0ecacc0d8c6b483cce9100c36add9/package.json#L47), but it does not appear to actually be used anywhere in the code (anymore).

Perhaps this dependency could be removed entirely?

**Comment by metaraine** [comment]
Yes, will do in the next version. Thanks!
