### ISSUE TITLE
Hanging on; Waiting for package data on stdin.

### ISSUE THREAD

**Issue by numediaweb** [tjunnone/npm-check-updates#176]
The process hands on this commands
```
{ .build } HEAD » npm-check-updates -u -l verbose
You can now use ncu for less typing!
Initializing...
Running in local mode...
Finding package file data...
Waiting for package data on stdin...
```

After this, it hangs forever.

**Comment by mriehema** [comment]
sounds like https://github.com/tjunnone/npm-check-updates/issues/136

**Comment by metaraine** [comment]
Please refer to [my comment on #136](https://github.com/tjunnone/npm-check-updates/issues/136#issuecomment-155859050).

I am unable to reproduce the issue myself, but the workaround is to use the `--packageFile` flag.

```
ncu --packageFile package.json
```
