### ISSUE TITLE
Doesn't work on fixed github dependencies like "PolymerElements/paper-menu#1.0.0"

### ISSUE THREAD

**Issue by RoXuS** [tjunnone/npm-check-updates#179]
Hello !

I have a problems with some dependencies and the bower mode (-m bower).

I have these two packages in my bower.json :

```JSON
    "moment": "2.9.0",
    "paper-menu": "PolymerElements/paper-menu#1.0.0"
```
When I launch `ncu -m bower` I get the following output :
```
 moment  2.9.0  →  2.10.6 

Run with -u to upgrade bower.json
```
Whereas the last version of paper-menu is 1.1.1.

ncu should works with this dependency ?

Thx !

**Comment by metaraine** [comment]
Hi Rousseau, thanks for reporting.

`PolymerElements/paper-menu#1.0.0` is a hardcoded github dependency that points directly to `https://github.com/PolymerElements/paper-menu` at tag `1.0.0`. npm-check-updates only works on dependencies that are given as a simple semver version number, and ignores others. npm-check-updates is not smart enough to parse `#1.0.0` from the github dependency, know that the tag is a valid semver version, and then know that there is a newer version available on github.

npm-check-updates uses the chosen package manager's API to find latest/greatest versions. If `paper-menu` were in bower, it would have information to upgrade the version.

```sh
$ bower info paper-menu
bower ENOTFOUND     Package paper-menu not found
```

In the mean time, you will have to manually update fixed github dependencies. You can encourage library owners to publish their package to a package manager.

**Comment by RoXuS** [comment]
Thanks for the explanation !

**Comment by kevin-smets** [comment]
When this is hosted on an internal Stash server, things go wrong. You get a response in html, and NCU fails on it.

```
Unhandled rejection SyntaxError: Unexpected token <
```

I would expect ncu to simply ignore an erroneous response and continue, but it stops altogether. Maybe I got time to look into the code at a later time but for now, just wanted to report this.

**Comment by metaraine** [comment]
Thanks @kevin-smets. That sounds like a separate issue. Will you create a new issue for it and provide steps to reproduce when you get a chance? Thanks!
