### ISSUE TITLE
Doesnt support private modules

### ISSUE THREAD

**Issue by garrows** [tjunnone/npm-check-updates#180]
Looks like it doesnt check for updates for private modules. I assume it's not sending any auth tokens with the requests to NPM.

**Comment by metaraine** [comment]
Hi Glen. No it doesn't send any auth tokens. I'm not sure exactly how private modules work on npm, but I'm guessing support could be added if the user was able to login with their npm credentials before npm-check-updates made the `npm view @user/privatemodule` request to get the latest version number.

**Comment by namar00** [comment]
exactly how private modules work on npm, but I'm guessing support could be added if the user was able to login with their npm credentials before npm-check-updates made the npm view @user/privatemodule request to get the latest,,

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.
