### ISSUE TITLE
No output if an installed package has an update available

### ISSUE THREAD

**Issue by mdouglass** [tjunnone/npm-check-updates#181]
I've run into a strange problem that just started for me today with ncu. If I don't have a node_modules folder (never run `npm install`), then everything works correctly. If I've previously done an `npm install` then I will get two lines of blank output and then the command prompt returns.

package.json
```
{
  "name": "ncu-issue",
  "dependencies": {
    "bluebird": "^3.0.5"
  }
}
```

Results with no node_modules folder:
```
~/ncu-test$ rm -rf node_modules/
~/ncu-test$ ncu

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package.json by using npm update. If you want to update the dependency in your package.json anyway, use ncu --upgradeAll.

 bluebird  ^3.0.5  →  ^3.0.6 
```

Results after npm install:
```
~/ncu-test$ npm install
ncu-test@ /Users/mdouglass/ncu-test
└── bluebird@3.0.6 

npm WARN EPACKAGEJSON ncu-test@ No description
npm WARN EPACKAGEJSON ncu-test@ No repository field.
npm WARN EPACKAGEJSON ncu-test@ No license field.
~/ncu-test$ ncu


~/ncu-test$ 
```

Versions:
```
ncu 2.5.2
~/ncu-test$ node -v
v5.1.0
~/ncu-test$ npm -v
3.3.12
```

**Comment by mdouglass** [comment]
This only seems to happen if there is a package that needs an update and that package is installed in node_modules.

**Comment by metaraine** [comment]
Thank you, there have been lots of edge cases with the different
satisfied/unsatisfied/installed/not-installed combinations.

Currently this is the expected behavior: if you don't have the package
installed, it won't say anything because your specified dep is already at
the latest (albeit one patch behind, which won't affect which version is
installed since you're using a range). It is only when the installed
package is behind that it suggests you update.

**Comment by mdouglass** [comment]
Ok, but I think I'm seeing the exact opposite of that. 

If nothing is installed (not even a node_modules folder) then I get an out of date message for bluebird.  

If bluebird is installed, I get no output.  Not even a 'all dependencies are up to date message'.  Just two carriage returns and a new prompt.  

Did I misunderstand the expected behavior?

**Comment by metaraine** [comment]
Okay, I will investigate.

**Comment by metaraine** [comment]
I've tested again and the behavior on my end for ncu `v2.5.2` is as expected, although I don't know why you're getting blank output.

Given your specified version is `^3.0.5` and the latest is `3.0.6`:

- If nothing is installed, it'll tell you that you need to run `npm update`.
- If the latest version is installed, it won't say anything.

When I have `^3.0.5` specified and `3.0.6` installed, I see:

```
$ ncu
All dependencies match the latest package versions :)
```

**Comment by mdouglass** [comment]
Ok, went to go try to test this out today and was planning to actually debug what was going on. However, I can no longer repro the problems I was having even with the test project that was 100% before.  I'm going to close this out and will re-open if it happens again.
Thanks for looking into it

**Comment by metaraine** [comment]
Thanks for trying. There have been several frustrating issues lately that have not been reproducible the second time around.
