### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by jlbruno** [tjunnone/npm-check-updates#186]
Trying to exclude packages as shown in your documentation, but when I run the example code

`$ ncu '/^(?!gulp-).*$/'`

I get an error 

`.*$/ was unexpected at this time`

Using v2.5.4 on Windows.

**Comment by metaraine** [comment]
Hi Jeff. Thanks for reporting. As I have only tested the regex on Mac, I am guessing that `/^(?!gulp-).*$/` needs to be escaped differently on the Windows command line. Does `echo '/^(?!gulp-).*$/'` give you the same error? You could try googling to find out how to escape special characters on Windows command line.

**Comment by jlbruno** [comment]
`echo '/(?!gulp-).*$/'` returns `'/(?!gulp-).*$/'`

But it must be something about windows CLI, it does work if I use that command from Git Bash. Thanks for the direction.
