### ISSUE TITLE
When there is no network connection, no error is thrown

### ISSUE THREAD

**Issue by raffomania** [tjunnone/npm-check-updates#187]
When running ncu without an internet connection, it reports that all packages are up to date. I would expect it to throw an error.

**Comment by metaraine** [comment]
When I try it with no network connection, I get the following, after a long period of time:

```sh
Unhandled rejection Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

What OS are you on?

**Comment by kevin-smets** [comment]
I also receive an error so it looks fine to me (OS X here), just wanted to report this as some of the registries for me are only accessible over VPN. So it works as expected.

```
Unhandled rejection Error: getaddrinfo ENOTFOUND servers.overvpn.somewhere servers.overvpn.somewhere
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by metaraine** [comment]
Closing. I'll reopen if someone can reproduce.
