### ISSUE TITLE
Convention on command-line flags

### ISSUE THREAD

**Issue by dashmug** [tjunnone/npm-check-updates#188]
I'd like to make a suggestion to use existing unix/linux (or is it POSIX?) conventions for the multi-word command-line flags.

I'm referring to the following flags:

```
--error-level
--jsonAll
--jsonUpgraded
--loglevel
--packageData
--packageFile
--packageManager
--upgradeAll
```

I think it would be best if we can make these flags `hyphen-separated` instead of using `camelCase`. So `--upgradeAll` becomes `--upgrade-all`.

I'll see if I have the time to make a PR for this.

**Comment by metaraine** [comment]
Thanks, I'm open to that. It can be released in the next major version.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.
