### ISSUE TITLE
Update notifier reports wrong version

### ISSUE THREAD

**Issue by gsklee** [tjunnone/npm-check-updates#190]
Got this:

```
$ ncu -a

┌─────────────────────────────────────────────────┐
│ Update available: 2.5.2 (current: 2.5.1)        │
│ Run npm install -g npm-check-updates to update. │
└─────────────────────────────────────────────────┘
```

But:

```
$ npm ls --depth=0 -g

/Users/kaylee/.nvm/versions/node/v5.2.0/lib
├── babel-eslint@4.1.6
├── npm@3.3.12
├── npm-check-updates@2.5.4
└── semistandard@7.0.4
```

Looks like the version checking mechanism is bugged.

**Comment by metaraine** [comment]
Interesting! It is using [update-notifier](https://github.com/yeoman/update-notifier) directly.

**Comment by sindresorhus** [comment]
`update-notifier` is not aware of nvm and you might have two different globally installed versions of `npm-check-updates`. One in the nvm subshell and one in the PATH.

**Comment by metaraine** [comment]
It looks like `update-notifier` only checks updates once a day by default. That might also have caused the discrepancy.
