### ISSUE TITLE
ncu doesn't install new dependencies

### ISSUE THREAD

**Issue by alundiak** [tjunnone/npm-check-updates#200]
I saw some issue/PR these days here (something related to `@latest`), which might be related to described my issue below. Sorry if so. Anyway, IMHO, below described behavior is odd.

So I tested on 2 modules: `grunt-penthouse` and `grunt-plato`.
And short summary -  **ncu doesn't update internal node_modules/package.json, despite it says that module updated**.

FYI, U will see below 2 kinds of package.json:
- /Users/alund/prj/builders/`package.json` - my main json file of project.
- /Users/alund/prj/builders/ `./node_modules/grunt-MODULE/package.json` - json file of tested module.

## TEST CASE 1

I spotted on this, during grunt-penthouse module research (cc/ @fatso83 here).

step 1:
```
npm install grunt-penthouse@0.1.1 --save-dev
```
step 2 - I do configure all I need, and `grunt penthouse` works ok.
step 3 - I decided to check updates, by running `ncu`:
```
grunt-penthouse  ^0.1.1  →  ^0.3.0 

Run with -u to upgrade package.json
```

step 4 - So I do run `ncu -u` or even `ncu -a`, and it shows me msg:
```
grunt-penthouse  ^0.1.1  →  ^0.3.0 

Upgraded /Users/alund/prj/builders/package.json
```
And this file is updated.

step 5 (final, key step) - **BUT**. When I open `./node_modules/grunt-penthouse/package.json` file **I see no changes** - `"version": "0.1.1"`

step 6 (additional) - *And ONLY AFTER* `npm install grunt-penthouse --save-dev` I have `/node_modules/grunt-penthouse/package.json` => `"version": "0.3.0",`

## TEST CASE 2
cc/  @jsoverson here.
step 1:
```
npm install grunt-plato@1.1.0 --save-dev
```
my package.json => "grunt-plato": "^1.1.0",

step 2:
```
$ ncu

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use -a/--upgradeAll.

 grunt-plato  ^1.1.0  →  ^1.2.1 
```
step 3:
```
$ ncu -u
The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use -a/--upgradeAll.

 grunt-plato  ^1.1.0  →  ^1.2.1 
```
step 4:
```
$ ncu -a

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use -a/--upgradeAll.

 grunt-plato  ^1.1.0  →  ^1.2.1 

Upgraded /Users/alund/prj/builders/package.json
```

step 5:  And file is updated, `/Users/alund/prj/builders/package.json` => `"grunt-plato": "^1.2.1",` - OK
**BUT** `./node_modules/grunt-plato/package.json` => `"version": "1.1.0",` - NOT OK

step 6: *And ONLY AFTER* `npm install grunt-plato --save-dev` I have  `./node_modules/grunt-plato/package.json` => `"version": "1.2.1",`.
Yes, the latest release/tag for grunt-plato is 1.3.0 but at least I see BUG - `npm-check-updates` **doesn't update/install module in fact and doesn't update package.json correctly**.

@tjunnone @metaraine what do u think? Is this expected behavior?  I can test one more module if needed.

Reproduced with:
- npm-check-updates `v2.5.6` 
- grunt-cli `v0.1.13`
- grunt `v0.4.5`
- node `v4.2.4`
- npm `v2.14.12`

PS. Once again, sorry, If I pick up well known issue, I tried to search, similar issues (open/closed).

**Comment by metaraine** [comment]
Hi Andrii. Thanks for reporting and for providing a detailed explanation of the issue.

It is in fact by design. Notice that after you run `ncu -u` it just says "Upgraded package.json." It does not say "Installed new modules." *ncu only modifies your package.json*. You can simply run `npm update` or `npm install` afterwards in order to actually install the updated dependencies.

Leaving the actual installation to npm ensures that ncu's only write operation is to the package.json, and everything else is read-only. Limiting ncu in this way makes is easier to reason about its effects.

**Comment by alundiak** [comment]
@metaraine I got it. Nevertheless, I don't see any sense to just upgrade/modify my project's package.json. IMHO, I would expect `ncu -u` to do do final installation. The word `upgrade` itself tells me, that something upgraded, not updated, not even modified. Kinda misunderstood. 
But good to know now, what ncu in fact does. Now my automatization script will have one more line :( And I hoped this would be done by ncu.

### Q1
And what about 
```
-a, --upgradeAll             include even those dependencies whose latest version satisfies the declared semver dependency
```
?? is it only abou `@latest` vs. semver "issue"?

### Q2
What if you implement 
```
ncu -ri || ncu --real-install-i-beg-you
```
which would do besides upgrade, installation also :)

### Q3
What if I want to check updates for global modules and reinstall them all-in-one command?

```
➜  builders git:(master) ✗ ncu -g        

 generator-webapp    1.1.0  →  1.1.2 
 jshint              2.8.0  →  2.9.1 
 npm               2.14.12  →  3.5.3 
 rimraf              2.5.0  →  2.5.1 
 webpagetest         0.3.3  →  0.3.4 
 yo                  1.4.8  →  1.6.0 
```

So when I run `ncu -g -u` what package.json will be updated?
Again, designed, right?
```
ncu cannot upgrade global packages. Run npm install -g [package] to update a global package
```
But what if I have such task/need :) ? Does it make sense that ncu is right place to have such ability?

**Comment by metaraine** [comment]
Yes, I can understand how it would it be nice for ncu to handle installation, and how it could be confusing at first. The current design is important though for sticking to a modular, linux-y design.

Tightly coupling the installation process with the package upgrade makes it less flexible.

e.g. It is possible to feed ncu a package.json from anywhere: `ncu --jsonFile /some/package.json` or `cat /some/package.json | ncu`. It wouldn't necessarily make sense to install dependencies in that case.

ncu currently does something that npm *doesn't* do. Hence it is its own module. I do not think it is beneficial to wrap npm functionality within ncu. It is essentially the wrong place to create the abstraction for chaining commands. If you want to always install packages after ncu, you are better off doing this at the shell level with an alias or bash function:

```sh
$ alias ncu=ncu && npm install
```

Hope that helps explains some of my reasoning :).

**Comment by alundiak** [comment]
@metaraine thanks for additional explanation of the `ncu` design purpose. I got it and kinda agree. 
I think, now I may close the issue, coz' in fact, no issue :)
