### ISSUE TITLE
.ncurc file to ignore certain packages

### ISSUE THREAD

**Issue by superclarkk** [tjunnone/npm-check-updates#205]
Enhancement Request:

My project uses [grunt-html](https://github.com/jzaefferer/grunt-html). The latest version of it requires java 1.8, which my platform doesn't natively support. Anyway, I'm quite happy using java 1.7 for now, as I have other non-node apps that rely on it.

It would be quite nice to be able to specify this package in a ncu configuration file (json, possibly) in the project folder, because I'm bound to forget that this should not be upgraded when I periodically run ncu, and hence this functionality would save some time and aggravation.

**Comment by metaraine** [comment]
Thanks for the suggestion! This behavior is actually already supported through the command line argument, which acts as a regex filter:

```
# match packages that start with "gulp-html" using regex
$ ncu /^gulp-watch/

# match packages that do not start with "gulp-html". Note: single quotes are required
# here to avoid inadvertent bash parsing
$ ncu '/^(?!gulp-html).*$/
```

You could alias this or create a script in your package.json so you didn't have to type it every time.

**Comment by superclarkk** [comment]
Nice one! Thanks for that. This is the script I used in the end, in case anyone needs it:


~~~
# /path/to/project/ncu.sh

#!/bin/bash

# Specify packages to ignore using IGNOREPKGS (regexp)
IGNOREPKGS='/^(?!grunt-html).*$/'

if (( $# > 0 )) && [ "$1" == "-u" ]; then
	echo Using the filter: "$IGNOREPKGS"
	echo Upgrading package.json...
	echo 
	ncu -u "$IGNOREPKGS"
else
	echo Note: Run \'ncu.sh -u\' to upgrade package.json
	echo
	echo Using the filter: "$IGNOREPKGS"
	echo Finding packages in package.json that are out of date...
	ncu "$IGNOREPKGS"
fi
~~~
