### ISSUE TITLE
[REQUEST] integrate with lab for tested upgrades

### ISSUE THREAD

**Issue by rainabba** [tjunnone/npm-check-updates#206]
I update one dependency at a time, run `npm test` to be sure an update isn't an issue, then run `ncu` and repeat with the next. I'd LOVE to see an update mode where this was automated by ncu.

**Comment by metaraine** [comment]
That's a great idea. Sounds very doable. It will require ncu to run `npm install DEPENDENCY@VERSION' for each dependency. Might be a time-saver to assume that non-major upgrades will still work and only run `npm test` for major version upgrades (at least as an option).

A pull request is the most likely way for this to be completed, as fixing a couple bugs and refactoring are on the top of my list currently.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Comment by RichardWright** [comment]
Hi! Could I extend this issue? This flow sounds great, could it be something that is triggerable beyond the command line? Ideally I'm looking to create a pull request between package updates which would go into a CI pipeline?

**Comment by RichardWright** [comment]
I should add, that I love this project and it's functionality and would love to extend it!

**Comment by raineorshine** [comment]
Hi @RichardWright! Thanks for your interest. Would love your help! Let me know more about what you have in mind and I would be happy to advise and support.
