### ISSUE TITLE
Upgrade only specific packages specified via API

### ISSUE THREAD

**Issue by TheSavior** [tjunnone/npm-check-updates#208]
It looks like I can specify via the CLI specific packages for it to update, but I can't seem to figure out how to specify specific packages when using the API. is this an undocumented option somewhere?

**Comment by metaraine** [comment]
Yes, I will add it to the README.

The `args` option allows you to specify CLI argument via the API. It filters dependency names and accepts strings, arrays of strings, or regex.

```
// upgrade all grunt plugins
ncu.run({
    packageFile: 'package.json',
    args: [/grunt-/]
}).then(function(upgraded) {
    console.log('dependencies to upgrade:', upgraded);
});
```
