### ISSUE TITLE
[feature request] Honor @beta tag

### ISSUE THREAD

**Issue by CWSpear** [tjunnone/npm-check-updates#21]
Is there a way to honor the `@beta` tag? I'm developing an app and while still in the development stage, I want to make sure I update dependencies often so I can catch any issues as soon as possible.

But part of that is I'm using the SailsJS Beta (installed via `npm install --save sails@beta`), because I need features in the beta version and I don't expect to launch my app until that version of Sails becomes stable.

I use (and love) `npm-check-updates` to keep stuff up to date easily in my packages.json, but it keeps trying to revert my `sails` module (and the Sails adapter modules I'm using) to the latest stable version.

Is there a way to make `npm-check-updates` honor that `@beta` tag? 

Part of the problem is that `npm` itself doesn't put any beta designation in `package.json`. Maybe `npm-check-updates` can check the latest version with the version in `package.json` and if it's *higher* than the "latest" version, in can then check the beta channel?

**Comment by metaraine** [comment]
Added -t/--greatest flag to look for highest version number available (v2.0.0-alpha4).
