### ISSUE TITLE
Bower with GitHub shorthand

### ISSUE THREAD

**Issue by JosefJezek** [tjunnone/npm-check-updates#210]
With GitHub shorthand

```
"polymer": "Polymer/polymer#1.2.3",
```

```
All dependencies match the latest package versions :)
```

With out GitHub shorthand

```
"polymer": "1.2.3",
```

```
polymer  1.2.3  →  1.2.4
```

I need GitHub shorthand for PSK+
https://github.com/StartPolymer/polymer-starter-kit-plus

**Comment by metaraine** [comment]
Hi Josef, thanks for reporting. This isn't trivial not works in all cases given the semantics of GitHub shorthand, but correct me if I'm wrong. 

GitHub shorthand refers to a tag on GitHub. These tags are arbitrary and do not have to follow semver. Parsing the tag from the shorthand, assuming it was semver, and retrieving possible updates from the list of tags on github would work in your use case. It would be a dangerous assumption however for all libraries, so at the very least should be opt-in.

I would be open to this as a pull request, but I will not be able to implement it myself at this time.

**Comment by JosefJezek** [comment]
Please create simple option for update to latest version without semver.

**Comment by blowsie** [comment]
+1

It would be great if git paths were supported in this format.

```
 "devDependencies": {
    "grunt": "^0.4.5",
    "my-custom-package": "git+ssh://git@myprivategit.com:groupname/project-name.git"
  }
```

**Comment by metaraine** [comment]
Hi Sam. Thanks for the suggestion. You may have to fill me in a little as I am not familiar with these forms of specifying dependencies. For example, by the looks of your git path, there is no version number included. What exactly would ncu be upgrading? Thanks.

**Comment by blowsie** [comment]
@metaraine Ultimately `my-custom-package` is still a npm package, therefore it has a `package.json` file, I assumed it may be possible to check this file for newer versions?

**Comment by metaraine** [comment]
In that case, I think a normal "npm update" would work.

npm-check-updates only works for packages in the npm registry.

**Comment by BorntraegerMarc** [comment]
Is there an update on the GitHub shorthand issue?

**Comment by raineorshine** [comment]
@BorntraegerMarc No update unfortunately. There have been higher priority issues and I have been the only one working on this for several years now :/.
