### ISSUE TITLE
should update from prerelease to latest

### ISSUE THREAD

**Issue by julien-f** [tjunnone/npm-check-updates#214]
In my `package.json`:

``` json
{
  "devDependencies": {
    "babel-eslint": "5.0.0-beta6"
  }
}
```

I would expect `ncu -u` to update it to 5.0.0.

**Comment by metaraine** [comment]
That makes sense. I can investigate further when I have time, or someone
else could submit a pull request.

**Comment by laggingreflex** [comment]
+1. Also, if there's `5.0.0-beta7` or `5.0.0-rc0` etc. it should be updated to those instead.

**Comment by raineorshine** [comment]
Works as intended now.

Recommend using a combination of the `--newest` and filtering to handle specific prereleases.

```
ncu -x babel-eslint && ncu --newest babel-eslint
```
