### ISSUE TITLE
Is not working inside of Docker Container

### ISSUE THREAD

**Issue by Skilgarriff** [tjunnone/npm-check-updates#215]
I built a docker container that is only built to run gulp as a task runner. I have tried implementing npm-check-updates into this process so that I could make it easier to update the packages. When I run ncu -u I get a failure error:
Invalid package file from stdin. Error details:
No data, empty input at 1:1

^
(my docker container) exited with code 1. 

I know that the package file exists and works correct, as if I only run npm install and gulp everything runs as expected. 

If you want to recreate this issue the code for the container I am using is located here: 
https://github.com/Skilgarriff/docker-develop
Simply download this then uncomment Line 11 and comment Line 15, 5 and 8 in the dockerfile. 
run Docker-compose build, then docker-compose up and the error should be replicated.

**Comment by metaraine** [comment]
Try using the --packageFile option. Some nonstandard usages of ncu trigger its stdin mode.

**Comment by Skilgarriff** [comment]
Used the --packageData option instead and it worked! Can close, thanks for the help

**Comment by metaraine** [comment]
Great

**Comment by rzr** [comment]
IMHO, ncu could detect that stdin is not available and then fallback to desired behaviour described above.
has this been reported anywhere ?

For the record here is the reported error:

```sh
ncu -a
Invalid package file from stdin. Error details:
Bad numeric literal - "." at 1:1
package.json
```

**Comment by raineorshine** [comment]
@rzr Yes, there is an issue that several people have reported with stdin false positives, although nobody has investigated more thoroughly yet. I am unable to reproduce on my end. 

See #136
