### ISSUE TITLE
Cannot filter global packages

### ISSUE THREAD

**Issue by superclarkk** [tjunnone/npm-check-updates#216]
To reproduce:

~~~
npm install -g eslint@1.10.3
ncu -g '/^(?!eslint).*$/'
~~~

This should ignore eslint, but instead prints the following:
`eslint  1.10.3  →  2.2.0`

**Comment by metaraine** [comment]
Thanks, I will investigate when I have time. Or if someone else wants to
look into it that's great, too.

**Comment by raineorshine** [comment]
Fixed and published to v2.6.5.
