### ISSUE TITLE
blacklist option

### ISSUE THREAD

**Issue by jonathanong** [tjunnone/npm-check-updates#218]
right now, we can do a regex to whitelist which packages to check. i'd like a blacklist option. this is specifically for packages that have breaking changes that i don't want to update my code for yet.

**Comment by metaraine** [comment]
It's possible to do with regex (see README) but it's a really terrible
syntax. I agree we need an exclude cli option.

**Comment by focusaurus** [comment]
+1 would like to see this feature.

**Comment by metaraine** [comment]
Published to latest v2.6.0.
