### ISSUE TITLE
Support Git/GitHub URLs?

### ISSUE THREAD

**Issue by gsklee** [tjunnone/npm-check-updates#222]
In light of the recent npm/leftpad drama, I'd like to change the way I author my `package.json` into a format that's less-dependent on npm:

```javascript
{
  "dependencies": {
    "express": "expressjs/express#4.13.4",
    "mocha": "mochajs/mocha#v2.4.5"
  }
}
```

Do either `$ ncu -u` or `$ ncu -a` support version update in the case above? Just checking.

**Comment by metaraine** [comment]
ncu does not currently support this. It has been brought up a couple times, so could be a useful feature.

From #210:

> GitHub shorthand refers to a tag on GitHub. These tags are arbitrary and do not have to follow semver. Parsing the tag from the shorthand, assuming it was semver, and retrieving possible updates from the list of tags on github would work in your use case. It would be a dangerous assumption however for all libraries, so at the very least should be opt-in.

> I would be open to this as a pull request, but I will not be able to implement it myself at this time.

**Comment by gsklee** [comment]
Well, maybe there is some way... I can do some research into this some time.

**Comment by metaraine** [comment]
Thanks. Definitely doable, just involves some steps and some assumptions.

Please post progress in #210.
