### ISSUE TITLE
ncu -t and ncu -a does not pick up the same version

### ISSUE THREAD

**Issue by gajus** [tjunnone/npm-check-updates#223]
```
  create-index git:(master) ✗ ncu -t

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use -a/--upgradeAll.

 yargs  ^4.4.0  →  ^4.5.0

➜  create-index git:(master) ✗ ncu -a

All dependencies match the latest package versions :)
```

I am expecting `ncu -a` to update `yargs` to v4.5.0.

**Comment by metaraine** [comment]
-t searches for the greatest version numbers (i.e. beyond latest).

-a includes newer versions that are still within the declared version
range, but doesn't automatically search for greatest versions.

Try adding both flags if you want both behaviors!

**Comment by metaraine** [comment]
Sorry, my previous message got clipped by the email parser! Here is my complete message:

> -t searches for the greatest version numbers (i.e. beyond latest). 

> -a includes newer versions that are still within the declared version range, but doesn't automatically search for greatest versions. 

> Try adding both flags if you want both behaviors!

**Comment by gajus** [comment]
Understood. Thank you.
