### ISSUE TITLE
not running using zsh on mac

### ISSUE THREAD

**Issue by cybermarkus1** [tjunnone/npm-check-updates#225]
not running using zsh on mac. dont know why

**Comment by metaraine** [comment]
Sorry to hear that! Are you seeing any output? Is it getting stuck at a certain point? You can try running it with the `--loglevel verbose` to see more output.

**Comment by vladikoff** [comment]
Works fine for me on zsh on latest OS X.

**Comment by metaraine** [comment]
Closing, but please reply with more details about the issue of it's still a problem!
