### ISSUE TITLE
ncu using insecure dependency

### ISSUE THREAD

**Issue by binduwavell** [tjunnone/npm-check-updates#228]
I use bithound to track deps for one of my projects. They are fingering npmi 1.0.1 (which ncu depends upon) as being insecure because it is still relying on a pretty old npm that has the token leaking problem outlined by npm recently.

Here is the report: https://www.bithound.io/github/binduwavell/generator-alfresco/master/dependencies/npm/npm-check-updates

The npmi folks are suggesting folks use the next tag to grab a pre-release of 2.0.1 that depends on npm ^3.

https://github.com/maxleiko/npmi/issues/7

**Comment by metaraine** [comment]
Thanks! I will add it to my list and address it as soon I have time, or happily accept a pull request.

**Comment by metaraine** [comment]
FYI, npmi is used to dynamically install bower so that it is not downloaded for every user.

**Comment by binduwavell** [comment]
PR #229 submitted

**Comment by metaraine** [comment]
Published in v2.6.3
