### ISSUE TITLE
 ncu -m bower crash hard on installing bower dependency

### ISSUE THREAD

**Issue by k3v3n** [tjunnone/npm-check-updates#232]
Installing bower dependency... (this is a one-time operation)
npm-check-updates@2.6.3 /usr/local/lib/node_modules/npm-check-updates/lib/package-managers/../../
└── bower@1.7.9  extraneous

Unhandled rejection Error: EINVAL: invalid argument, rename '/usr/local/lib/node_modules/npm-check-updates/lib/package-managers/../../' -> '/usr/local/lib/node_modules/npm-check-updates/lib/....DELETE'
    at moveAway (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/install/action/finalize.js:38:5)
    at destStatted (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/install/action/finalize.js:27:7)
    at FSReqWrap.oncomplete (fs.js:117:15)

Error: EINVAL: invalid argument, rename '/usr/local/lib/node_modules/npm-check-updates/lib/package-managers/../../' -> '/usr/local/lib/node_modules/npm-check-updates/lib/....DELETE'
    at Error (native)

Environment
OSX 10.11.4
node v6.0.0
npm 3.8.6

**Comment by raineorshine** [comment]
There continue to be unresolved issues with the npm and bower dependencies. I think the ultimate fix is to not include them as dependencies at all, and just ask the user to install them globally then invoke them from a child_process. I am not sure when exactly I will have time to address this. Other than some smaller pull requests, I am the only maintainer currently. Open to help from the outside :).

**Comment by raineorshine** [comment]
The npm implementation now uses a combination of [package-json](https://github.com/sindresorhus/package-json) and spawning npm in a child process.

bower uses the commands API via the globally installed bower. The automatic installation causing problems in the OP is no longer in use.

Also, from bower.io:
> While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects
