### ISSUE TITLE
`ncu -g` errorously reports everything up to date when there's broken symlinks

### ISSUE THREAD

**Issue by stipsan** [tjunnone/npm-check-updates#235]
If you have a broken symlink in your global node_modules `ncu` will fall back to the default "Everything is up to date:-)" message.
It's pretty easy to encounter this if your contributor workflow involves `npm link` on forks of other peoples npm packages to test your patches before submitting your PRs.
If it's a one-off contribution it's likely you'll delete your local git checkout and replace the symlink with the version tag that contains the changes from your PR and all is fine in userland.

Except you forgot to remove the symlink in the global node_modules folder and the next time you run `ncu -g` you'll start to get suspicious when there's 6 months since you updated your global deps and you can't believe none of your deps is outdated yet.
Also, this happens: https://github.com/npm/npm/issues/12342

It's out of scope to expect ncu reporting broken symlinks as an extra service. But it would be nice if it simply ignored broken symlinks and reported the other deps status as usual 😃

**Comment by raineorshine** [comment]
Thank you for reporting. I thought that ncu was just ignoring broken symlinks and still checking other dependencies as normal. Are you saying that your other deps are not getting updated either?

**Comment by stipsan** [comment]
Yes, that's exactly what I'm saying.

Here's a screenshot of what happens before I symlink a package, after the symlink is done and after I leave the symlink in the global node_modules but delete its target:

![skjermbilde 2016-05-09 kl 14 21 35](https://cloud.githubusercontent.com/assets/81981/15112926/917f749a-15f1-11e6-95dc-a661809e3c4e.png)

Steps to reproduce:
1. git clone any npm module
2. `cd` into the local checkout and do `npm link`.
3. `rm . -vrf` and from now on `ncu -g` will always say `All global packages are up-to-date :)` until the broken symlink is nuked 😨 

I don't know how npm-check-updates works internally but I have a hunch this issue may be related: https://github.com/npm/npm/issues/9564

Maybe add it to a FAQ of known issues while waiting for npm to fix it?

**Comment by raineorshine** [comment]
Thank you for the clear explanation and steps to reproduce! Will definitely
document and investigate.

**Comment by raineorshine** [comment]
It appears this is very much the result of npm/npm#9564. I'll be watching that issue closely.

**Comment by raineorshine** [comment]
For others who are experiencing this issue, a quick way to way to see if you have dead symlinks is this:

```
$ less $(npm -g prefix)/lib/node_modules/*
```

If anything says `No such file or directory`, that's your problem. Delete the dead link and it should clear it up.

**Comment by tejeswar491** [comment]
How do we resolve the issue? If I do ncu(picks it from from package.json and even on bower.json), it says upto date. But shows the versions upgrade needed when I go into each dependency file and do ncu -m bower.json. I did "$ less $(npm -g prefix)/lib/node_modules/*", and says "*** is a directory".

**Comment by raineorshine** [comment]
@tejeswar491 npm/npm#9564 needs to be fixed since this is a dependency bug.
