### ISSUE TITLE
Gulp v4 task not updating package.json

### ISSUE THREAD

**Issue by emveeoh** [tjunnone/npm-check-updates#237]
> Using Gulp v4 (https://github.com/gulpjs/gulp/tree/4.0)
> npm-check-updates v2.6.4 is installed both globally (-g) and locally (devDependencies).

I run the [$ gulp updates] task. It *does* properly log the outdated dependencies to the console. However, the package.json is never updated/edited. No other errors are logged.

Running ncu -u from bash does work as expected.

My Gulp v4 task:

     // [updates]
     // Will automatically update package.json file with latest versions of all dependencies

     gulp.task('updates', function (cb) {
       ncu.run({
         // Always specify the path to the ./package.json file
         packageFile: gulpPath.to.packageJson,
         silent: false
       })
         .then(function (upgraded) {
           console.log('\n\nDEPENDENCIES TO BE UPDATED:\n', upgraded)
           cb()
         })
     })

**Comment by raineorshine** [comment]
The programmatic api is the same as the cli, so all flags must be included to get the same behavior. Try adding the `--update` flag to the `ncu.run` options:

```
gulp.task('updates', function (cb) {
   ncu.run({
     // Always specify the path to the ./package.json file
     packageFile: gulpPath.to.packageJson,
     update: true,
     silent: false
   })
     .then(function (upgraded) {
       console.log('\n\nDEPENDENCIES TO BE UPDATED:\n', upgraded)
       cb()
     })
 })
```

**Comment by emveeoh** [comment]
@raineorshine  Thank you for your suggestion!  I added the  --update command to the gulp task, but is still not updating the package.json file.

**Comment by raineorshine** [comment]
Whoops, it should actually be `upgrade: true`.

Unfortunately it still doesn't work though :(. I took a brief look through the relevant sections of code and could not figure it out. I'll have to investigate more another day.

As a temporary fix, I might suggest using a gulp plugin that invokes the ncu cli as a child process.
