### ISSUE TITLE
Regression. Using the API with an arg for one package updates all.

### ISSUE THREAD

**Issue by TheSavior** [tjunnone/npm-check-updates#240]
Updating to 2.6.5 from 2.5.8 caused ncu to stop being able to filter packages.

I'm calling the API with

```
return ncu.run({
      packageFile: '/my/path/to/package.json',
      upgrade: true,
      jsonUpgraded: false,
      args: ['packageName']
    })
```

With 2.5.8, this upgraded only the specific package I passed in as an arg. With 2.6.5 it upgraded all of the packages in my package.json

**Comment by raineorshine** [comment]
Thanks for reporting! I will have to take a look.
