### ISSUE TITLE
Way to ignore node_modules for comparison?

### ISSUE THREAD

**Issue by joshuajabbour** [tjunnone/npm-check-updates#244]
I love this module (package.json OCD for the win!), but constantly get confused by its behavior. If I run `npm update` _before_ running `ncu` (or I ran `npm install`), and newer versions of modules were installed from what's in package.json, there's no way to upgrade the package.json file. `ncu -a` just ignores them.

What I really want is a way to ignore what is in `node_modules` and just compare `package.json` to the npm registry (this is really the behavior I always expect, since I'm not sure why what is in node_modules matters).

This would allow me to always keep my package.json up-to-date. The workaround I've found is to `rm -rf node_modules && ncu -a && npm install`, which does what I expect. But that's a lot of extra work.

**Comment by raineorshine** [comment]
Hi Joshua! That does sound confusing. The behavior or `a` should probably change to ignore installed dependencies. 

This is a change that I can make when I have time, or that anyone else who was interested in could submit a pull request for.

**Comment by joshuajabbour** [comment]
Cool, I just wanted to clarify behavior. I can take a look at a PR soon.

**Comment by raineorshine** [comment]
Just want to note that this behavior is confusing for many users. Next major version should not do anything special regarding node_modules.

**Comment by mqklin** [comment]
+1, spent a lot of time to understand that I need run `rm -rf node_modules` first

**Comment by raineorshine** [comment]
Fixed and soon will be published to `v3`
