### ISSUE TITLE
Do the actual update

### ISSUE THREAD

**Issue by piranna** [tjunnone/npm-check-updates#245]
On NodeOS we are thinking about adding [an auto-update feature](https://github.com/NodeOS/NodeOS/issues/247). I was thinkin to use `npm-check-updates` as basis for this, but I'm not sure if it's in focus to add a way to do the actual updates of the package (specially the global ones), of if it should be done in an independent project that uses `ncu` as dependency. Would you accept that feature?

**Comment by lite20** [comment]
+1 for an update performing feature

**Comment by raineorshine** [comment]
Can you just run `npm install` after `ncu -u`?

**Comment by piranna** [comment]
Yes we can (sort of), we are just studying if it makes more sense to have
that functionality inside ncu, or on it's own project using ncu as
dependency.

**Comment by raineorshine** [comment]
@piranna Strongly prefer doing it outside `ncu`. Unix philosophy: do one thing and do it well. No sense adding `npm install` or `npm update` functionality if it already exists. It helps keep `ncu` contained and focused if we know that the only modifications it ever makes are to the `package.json`.

**Comment by piranna** [comment]
I think so too, it's only that since it lasted the last extra mile, maybe
you would find it a good feature to have, so we could implement it directly
on ncu. I think then this could be clossed.

**Comment by raineorshine** [comment]
You can't have it both ways :). Better to keep things modular.

**Comment by piranna** [comment]
I agree :-)
