### ISSUE TITLE
"^*" could not be parsed by semver-utils.

### ISSUE THREAD

**Issue by pbwuxus** [tjunnone/npm-check-updates#247]
i get ^* in the version field added by a other script program(can't remember the name) to force the version upgrade.

> Unhandled rejection Error: "^*" could not be parsed by semver-utils. This is probably a bug. Please file an issue at https://github.com/tjunnone/npm-check-updates.
>     at isUpgradeable (/usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:151:15)
>     at /usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:8201:21
>     at /usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:4299:13
>     at /usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:3073:15
>     at baseForIn (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:2033:14)
>     at pickByCallback (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:4298:7)
>     at Function.<anonymous> (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:9893:11)
>     at Function.pick (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:8152:31)
>     at baseWrapperValue (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:2768:30)
>     at LodashWrapper.wrapperValue (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:6124:14)
>     at Object.upgradeDependencies (/usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:135:10)
>     at /usr/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:112:39
>     at tryCatcher (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:504:31)
>     at Promise._settlePromise (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:561:18)
>     at Promise._settlePromise0 (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:606:10)
>     at Promise._settlePromises (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:685:18)
>     at Promise._fulfill (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:630:18)
>

**Comment by raineorshine** [comment]
Thanks, I will investigate! If ^* is actually a valid version number then we'll need to fix semver-utils.

**Comment by raineorshine** [comment]
Published in `v2.6.8`

**Comment by pbwuxus** [comment]
thx
