### ISSUE TITLE
package fails to install

### ISSUE THREAD

**Issue by Eschon** [tjunnone/npm-check-updates#250]
I just ran ncu and got the message that an update is available but when I run `npm install -g npm-check-updates` I get the following error output

```
/Users/egon/.nvm/versions/node/v6.2.2/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/egon/.nvm/versions/node/v6.2.2/bin/node" "/Users/egon/.nvm/versions/node/v6.2.2/bin/npm" "install" "-g" "npm-check-updates@2.6.7"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /Users/egon/.nvm/versions/node/v6.2.2/lib/node_modules/.staging/abbrev-b983ae62
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/egon/.nvm/versions/node/v6.2.2/lib/node_modules/.staging/abbrev-b983ae62' -> '/Users/egon/.nvm/versions/node/v6.2.2/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/egon/.nvm/versions/node/v6.2.2/lib/node_modules/.staging/abbrev-b983ae62' -> '/Users/egon/.nvm/versions/node/v6.2.2/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/egon/Desktop/lynx/npm-debug.log
npm ERR! code 1
```

I tried to install the previous version with `npm install -g npm-check-updates@2.6.7` but that produces the same error now.

**Comment by raineorshine** [comment]
I'm not sure what this problem is, but npm-check-updates doesn't use the `abbrev` package so it's either an issue with a dependency or with the install process, which unfortunately is not unheard of. Do you get the same error when you install other packages globally? When you install ncu on a fresh version of node?

**Comment by Eschon** [comment]
I just tried it again and now it works. I'm not sure what the problem was before.

**Comment by raineorshine** [comment]
npm flakiness :/

**Comment by Elyx0** [comment]
@Eschon @raineorshine same issue here, but it's not solving itself :(

**Comment by raineorshine** [comment]
@Elyx0 I'm sorry it's not working for you. If you can provide a set of reproducible steps, I will be able to help troubleshoot the issue. It is possible that is is not an issue with npm-check-updates at all, and is rather an npm install issue.

**Comment by Elyx0** [comment]
@raineorshine Actually I updated npm and `rm -rf /usr/local/lib/node_modules/npm-check-updates` and reinstalled and it was good.

**Comment by raineorshine** [comment]
@Elyx0 I hate when thing work without knowing why almost as much as I hate when things don't work without knowing why :).
