### ISSUE TITLE
This package is not working in GitBash?

### ISSUE THREAD

**Issue by pokakhoaitay** [tjunnone/npm-check-updates#251]
It's working well in cmd.exe but in the mintty.exe (git bash shell) it's stuck forever
![image](https://cloud.githubusercontent.com/assets/7122384/16543310/f5c959ee-40f7-11e6-9ac2-270f3c70c503.png)
(it's stuck here forever)

**Comment by raineorshine** [comment]
Hi! Thanks for reporting! This is a known issue. There is a solution! From the main README:

> In some environments (Windows?) npm-check-updates may hang. Run ncu --loglevel verbose to see if it is waiting for stdin. If so, try setting the package file explicitly: ncu -g --packageFile package.json. See #136.

**Comment by pokakhoaitay** [comment]
Ok. thanks for the information
