### ISSUE TITLE
ncu's stopped working recently

### ISSUE THREAD

**Issue by zhekaus** [tjunnone/npm-check-updates#254]
ncu does nothing, doesn't give any output. I've tried to reinstall it and nodeks - nothing's helped

**Comment by raineorshine** [comment]
Thanks for reporting. Does --help work? Does --logLevel verbose give
anything?

**Comment by zhekaus** [comment]
$ ncu -l silly
Initializing...
Running in local mode...
Finding package file data...
Waiting for package data on stdin...

... and you can go to sleep

**Comment by mykohsu** [comment]
This is documented on known issues list.

**Comment by zhekaus** [comment]
@mykohsu Oh, yes. This's my case. Thanks a lot!
