### ISSUE TITLE
Use bower resolvers

### ISSUE THREAD

**Issue by jrencz** [tjunnone/npm-check-updates#259]
Use case:

I install [babel-polyfill from npm](https://www.npmjs.com/package/babel-polyfill) using bower and [`mjeanroy/bower-npm-resolver`](https://github.com/mjeanroy/bower-npm-resolver).

`ncu -m bower` won't show if my dependency installed using 3rd party resolver is outdated.

ncu may use [resolvers](https://bower.io/docs/pluggable-resolvers/) (maybe via CLI `bower.command.lookup`?) to check status of dependencies.

**Comment by raineorshine** [comment]
Hey, that's a great idea! I don't have time at the moment, but I'm open to pull requests.
