### ISSUE TITLE
greatest suggests to downgrage for one specific package

### ISSUE THREAD

**Issue by bsr203** [tjunnone/npm-check-updates#260]
Hi,

I had this issue for sometime, and thought of reporting now.

ncu works great and I use it all the time. I found one exception where it reports greatest package wrongly. It works well for other packages.

```
ncu -t
...
 react-select                  ^1.0.0-beta14  →  ^1.0.0-beta9
 babel-plugin-istanbul                ^1.0.3  →        ^1.1.0
```

```
npm dist-tag ls react-select                                                                                ⏎ master
latest: 1.0.0-beta14
```

why is it asking to change `beta14` -> `beta9`

```
npm --version                                                                                                 master
3.10.2
ncu --version                                                                                                 master
2.7.2
```

I indeed has beta14 installed

```
cat node_modules/react-select/package.json                                                                    master
{
  "_args": [
    [
      {
        "raw": "react-select@^1.0.0-beta14",

        "scope": null,
        "escapedName": "react-select",
...
```

**Comment by raineorshine** [comment]
Good catch! Apparently it is because npm sorts versions lexicographically instead of leaving them in publish order:

```
$ npm view react-select versions
 
[ ...
  '0.9.0',
  '0.9.1',
  '1.0.0-beta1',
  '1.0.0-beta10',
  '1.0.0-beta11',
  '1.0.0-beta12',
  '1.0.0-beta13',
  '1.0.0-beta14',
  '1.0.0-beta2',
  '1.0.0-beta3',
  '1.0.0-beta4',
  '1.0.0-beta5',
  '1.0.0-beta6',
  '1.0.0-beta7',
  '1.0.0-beta8',
  '1.0.0-beta9' ]
```

We might be able to avoid this by simply querying `view react-select` (which does have them in the correct order) and then plucking out the versions. I will look into it.

**Comment by raineorshine** [comment]
You can now use the `--newest` flag to get the desired behavior. `--greatest` will continue to get the greatest lexicographic version number, which may still be needed if a package author publishes versions out of order.

Thanks!

Published in `v2.8.0`.

**Comment by bsr203** [comment]
that was super fast :-) works great. thanks.

**Comment by raineorshine** [comment]
Luckily it was an easy one :)

**Comment by billyjanitsch** [comment]
It doesn't look like react-select is formatting its beta releases correctly. They [should be](https://docs.npmjs.com/misc/semver#prerelease-tags) published as `1.0.0-beta.11` rather than `1.0.0-beta11`. I'm not sure how `ncu` is sorting its versions, but if it's using a standard semver module, the previous behavior might have actually been correct.

**Comment by billyjanitsch** [comment]
Yeah, it looks like the sort order is fine when the formatting is correct. It's not a strict lexicographic sort -- it obeys semver, so `1.2.3-beta.10` occurs after `1.2.3-beta.9`. e.g. `npm view webpack versions`:

```
[ ...
  "2.1.0-beta.0",
  "2.1.0-beta.1",
  "2.1.0-beta.2",
  "2.1.0-beta.3",
  "2.1.0-beta.4",
  "2.1.0-beta.5",
  "2.1.0-beta.6",
  "2.1.0-beta.7",
  "2.1.0-beta.8",
  "2.1.0-beta.9",
  "2.1.0-beta.10",
  "2.1.0-beta.11",
  "2.1.0-beta.12",
  "2.1.0-beta.13",
  "2.1.0-beta.14",
  "2.1.0-beta.15",
  "2.1.0-beta.16",
  "2.1.0-beta.17",
  "2.1.0-beta.18",
  "2.1.0-beta.19",
  "2.1.0-beta.20"
]
```

So @raineorshine you may want to revert this change and @bsr203 you may want to bring this up with the react-select maintainers to get this fixed on their end.

**Comment by raineorshine** [comment]
@billyjanitsch Thanks for the additional information. It'll be good to see this corrected on the react-end.

The change I made is backwards-compatible since I added it under a new flag, `--newest`.

**Comment by JedWatson** [comment]
Sorry about this - I hadn't gone through so many beta releases on a project before so I didn't realise they weren't in the right format until it was pointed out for react-select!

We're into rc phase now and it's versioned properly (with a proper release to come "soon") so this shouldn't trouble anybody again.

On another note, thanks for `ncu` - I use it all the time 😀

**Comment by raineorshine** [comment]
👍
