### ISSUE TITLE
Comments in package.json are not supported

### ISSUE THREAD

**Issue by ludoo0d0a** [tjunnone/npm-check-updates#262]
package.json can have ignored instructions by putting comments like this : 

```js
"//": {"bootstrap": "3.3.6"}
```

ncu failed to parse these comments.
Thanks

**Comment by raineorshine** [comment]
Reference?

**Comment by ludoo0d0a** [comment]
http://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install

https://github.com/npm/npm/issues/4482

**Comment by raineorshine** [comment]
@ludoo0d0a Are you placing the "comment" key-value pair in the root of the package.json, in the dependencies section, or in another section? (thinking about this comment: http://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install#comment22422105_14221781)

**Comment by ludoo0d0a** [comment]
I placed my comment in dependencies and it worked for me.
I don't see why it should be at root only, as said in the mentioned comment.

**Comment by raineorshine** [comment]
I'm afraid the comment hack does only work at root only.

There is some interest in adding JSON5 support to ncu: https://github.com/tjunnone/npm-check-updates/issues/83
