### ISSUE TITLE
cannot upgrade global packages

### ISSUE THREAD

**Issue by cameronroe** [tjunnone/npm-check-updates#265]
`ncu cannot upgrade global packages. Run npm install -g [package] to update a global package`

We have to install -g each global module? What if we have like 20+ globals?

**Comment by raineorshine** [comment]
@cameronroe Hi! Thank you for the question, it does seem silly to have to do it manually for every one of your globals. Keep in mind that `npm-check-updates`'s single purpose is to upgrade `package.json` files. Since global packages are not tracked in a `package.json`, `npm-check-updates` is not really applicable. You could use something like the following bash command to get the list of all global packages, concatenate them, and run them through npm install:

```sh
npm install -g $(ls -m $(npm -g prefix)/lib/node_modules | sed 's/,//g')
```

**Comment by cameronroe** [comment]
True. But isn't this module "`npm`" check updates? Which should hopefully include globals. Would it be possible to include a command to assist upgrading global packages as well?

- `ncu -g`
- `ncu -u -g`

**Comment by raineorshine** [comment]
From a library perspective, there is incentive to limit the surface area of the API. If upgrading all global packages is simply a matter of adding an alias `alias npm-upgrade-global=npm install -g $(ls -m $(npm -g prefix)/lib/node_modules | sed 's/,//g')` to your bash profile then I think this functionality should stay out of `npm-check-updates`.

I am open to other people chiming in with their opinions!

**Comment by cameronroe** [comment]
That alias doesn't work for me.

**Comment by raineorshine** [comment]
Do you get an error message? Which part of it doesn't work?

**Comment by cameronroe** [comment]
I get a bunch of bash errors:

```
-bash: alias: install: not found
-bash: alias: -g: not found
-bash: alias: npm: not found
```

**Comment by raineorshine** [comment]
Sorry, I left out the quotes. I think it should be:

```sh
alias npm-upgrade-global="npm install -g $(ls -m $(npm -g prefix)/lib/node_modules | sed 's/,//g')"
```

Does that work for you?

If not, try running each of the subcommands one at a time and tell me what you get:

```sh
npm -g prefix
ls -m $(npm -g prefix)/lib/node_modules
ls -m $(npm -g prefix)/lib/node_modules | sed 's/,//g'
npm install -g $(ls -m $(npm -g prefix)/lib/node_modules | sed 's/,//g')
```

**Comment by cameronroe** [comment]
Okay, that worked. Thanks.
