### ISSUE TITLE
Add loglevel or flag to hide satisfied dependencies

### ISSUE THREAD

**Issue by Siilwyn** [tjunnone/npm-check-updates#267]
It would be really nice to be able to not print the "The following dependency is satisfied by its declared version range, (...)" message and list of dependencies.

I can create a PR but would like to hear some thoughts on this first, thinking of adding another loglevel or flag for it.

**Comment by raineorshine** [comment]
This is a minor change, but seems fine. I'm a little hesitant to extend the
API for something so minor. Is there a way to simply hide that part with
standard unix commands? If not, we could add another logLevel.

**Comment by Siilwyn** [comment]
How about logging the message at the `warning` level? The first thing I tried was setting the level to `error`, which didn't work.

**Comment by raineorshine** [comment]
`warn` is the default level, which it is already logging. We could add a
`minimal` log level that would be like `warn` but without the message that
you want to hide.

**Comment by raineorshine** [comment]
Published in `v2.8.3`.
