### ISSUE TITLE
Only check/update selected packages

### ISSUE THREAD

**Issue by nylen** [tjunnone/npm-check-updates#27]
As an example, I'd like to do `npm-check-updates -u mocha should` to only update the `mocha` and `should` packages.  This doesn't appear to be possible.

This might conflict with the fact that the first non-option argument is currently a `package.json` or a directory.  But really, how often do you want to run `npm-check-updates` outside of the current directory?

**Comment by kud** [comment]
Is it done? as we've got 1.5.0?

**Comment by metaraine** [comment]
Yes, this is done. Turns out the more complex gulp regex I provided doesn't work because of some bash escaping issues. It should be `npm-check-updates -f '/^(?!gulp-).*$/'`. I'll update the README. Thanks!

**Comment by kud** [comment]
Okay, thank you. ;)
