### ISSUE TITLE
Unsupported versionTarget error for a valid versionTarget

### ISSUE THREAD

**Issue by karanjthakkar** [tjunnone/npm-check-updates#274]
I keep getting this error while trying the valid `versionTarget` of `greatestMinor` as suggested in the image:

<img width="638" alt="screen shot 2016-09-28 at 9 32 26 pm" src="https://cloud.githubusercontent.com/assets/1824298/18921663/4b1a037a-85c3-11e6-98e5-73ea563f58b4.png">

Am I missing something or this actually a bug? 

`package.json`: https://gist.github.com/karanjthakkar/8f18b14eb40673b0ac1034fe01e16183

**Comment by raineorshine** [comment]
How confusing! It should be one of `latest, newest, greatest, major, minor`. I'll fix the error message in the next version, but if you start using `major` or `minor` it should work!
