### ISSUE TITLE
Unhandled rejection: Error 401

### ISSUE THREAD

**Issue by tizmagik** [tjunnone/npm-check-updates#278]
I have a dependency that's published to a local artifactory instance. For some reason (probably unrelated to ncu), I get an `Unhandled rejection` error:

```
Unhandled rejection Error: Registry returned 401 for GET on https://artifactory.xx.com/artifactory/api/npm/npm-virtual/@scope%2fcustom-module
 ...
```

If I manually remove this dependency from `package.json` and then re-run `ncu` it works as expected. Would it be possible to have ncu handle this rejection and continue checking the other dependencies?

**Comment by raineorshine** [comment]
Yes! Can you try the `ncu --reject PACKAGE_NAME` feature? 

Documented in the [README](https://github.com/tjunnone/npm-check-updates#usage).

**Comment by tizmagik** [comment]
Ah, sorry I missed that in the README. Yes, that does work!

Although, I wonder if `ncu` could just handle the error gracefully here? It would be great if it could display an error instead of the version number for that package and resume for the rest of the packages normally?

**Comment by raineorshine** [comment]
Great!

Yes, there are some usability improvements that could be made so this is more graceful. Allowing ncu to continue to check other packages sounds good. If this is run in upgrade mode though I'm not sure if it should go ahead and modify the package.json or error out. I will mark this issue as *enhancement.* There are some actual bugs that take priority, but this could be a good candidate for a pull request from a new contributor.

**Comment by tizmagik** [comment]
Hey @rainorshine is this handled differently now or is the `--reject` still the recommended workaround?

**Comment by raineorshine** [comment]
Same behavior
