### ISSUE TITLE
Failure on node v0.12.15

### ISSUE THREAD

**Issue by fpedroza** [tjunnone/npm-check-updates#279]
Running `ncu` works fine on node v0.12.9, but on v0.12.15, I receive the following error:
> /Users/fmpdmb/.nvm/versions/node/v0.12.15/lib/node_modules/npm-check-updates/node_modules/find-up/index.js:2
> const path = require('path');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/Users/fmpdmb/.nvm/versions/node/v0.12.15/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:9:14)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)

**Comment by fpedroza** [comment]
I may have my answer
> npm WARN engine find-up@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.14","npm":"2.15.1"})

**Comment by raineorshine** [comment]
I recently upgraded all packages and the `find-up` package now requires node >= 4. I don't think I am using any benefits of the latest version, so I should downgrade `find-up` as a simple way to keep this module node 0.12.x compatible.
