### ISSUE TITLE
Should handle paths like npm outdated

### ISSUE THREAD

**Issue by nylen** [tjunnone/npm-check-updates#28]
The algorithm `npm outdated` uses to figure out what to list is something like this:

- Look for a `package.json` in the current directory
- Look for a `package.json` in any parent directories
- Stop at the first one found and print versions of installed packages

There's probably more to it, anyone know details?

Currently `npm-check-updates` does not look for `package.json` in parent directories.

**Comment by metaraine** [comment]
Available in v2.0.0-alpha4

`npm install -g npm-check-updates@unstable`
