### ISSUE TITLE
ncu command stopped working after update to 2.8.3

### ISSUE THREAD

**Issue by jharris4** [tjunnone/npm-check-updates#283]
I just upgraded to version 2.8.3, and the ncu command stopped working.

I see the progress indicator, but then nothing else (no message at all and no obvious errors either)

It was working fine with version 2.8.2

**Comment by jharris4** [comment]
I reinstalled 2.8.2 and it works properly, definitely something broken in 2.8.2->2.8.3

**Comment by raineorshine** [comment]
Thanks for reporting. What do you see when you run it with `logLevel verbose`?

**Comment by raineorshine** [comment]
Rather: `--loglevel verbose`

**Comment by jharris4** [comment]
```Initializing...
Running in local mode...
Finding package file data...
Getting installed packages...
Fetching latest versions...
⸨░░░░░░░░░░░░░░░░░░⸩ ⠼ :```

**Comment by raineorshine** [comment]
Okay. I will try to reproduce as soon as I'm at my computer.

**Comment by raineorshine** [comment]
Can you provide your package.json dependencies?

**Comment by jharris4** [comment]
Found the bug...

**Comment by raineorshine** [comment]
Let's see it :)

**Comment by raineorshine** [comment]
Fix published in `v.2.8.4`.

**Comment by jharris4** [comment]
awesome, thanks for the quick fix!

**Comment by raineorshine** [comment]
Thanks for the assist!
