### ISSUE TITLE
ncu API call doesn't detects updated packages in node_modules.

### ISSUE THREAD

**Issue by carmelone** [tjunnone/npm-check-updates#287]
If I use `ncu` in my folder where is `package.json` everything works.

`ncu` correctly detects that many packages are outdated in my `package.json` file (using "~1.0.0") but updated in my "node_modules" folder because of `npm update`. And this is good. Infact if I change (just for this test) the package.json of that package in "node_modules\my-package\" and set an older version `ncu` correctly says this:

"The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use ncu -a/--upgradeAll.

 my-package  ~1.0.0  →  ~1.0.1"

And I'm happy.

This behavior doesn't work in API version of ncu. Infact everytime (with my below code) it always says to me (also if I everytime run `npm update` and call it again):

"{'my-package':'~1.0.1'}"

using this code:

"function checkMyUpdate() {
  return ncu.run({
    packageFile: 'package.json',
    upgradeAll: true,
    filter: /^my-/,
    jsonUpgraded: true
  });
}"

**Comment by raineorshine** [comment]
I have reopened #201, so well use that for consistency.
