### ISSUE TITLE
running `ncu` results in node terminating process

### ISSUE THREAD

**Issue by tconroy** [tjunnone/npm-check-updates#289]
Environment:
- OSX 10.11.6
- Node @ 6.9.0 (via nvm)
- NPM @ 3.10.8 (via nvm)
- Prezto shell (fork of oh-my-zsh)

I just installed ncu globally, executed it in the project directory. the terminal window freezes for a minute or two, then I get a termination notice.

```
❯❯❯ ncu
[1]    40393 terminated  ncu
❯❯❯ ncu --verbose
[1]    41396 terminated  ncu --verbose
```

..any ideas? :/ `--verbose` flag doesn't seem to provide any info.

**Comment by raineorshine** [comment]
The fact that you don't see anything when specifying `verbose` suggests that somehow it's not even starting up properly. I'm not sure what could cause this as I haven't see this behavior before. 

Other global packages installed with npm work fine?

**Comment by raineorshine** [comment]
I'll close this since I didn't hear back from you, but happy to help if you're still experiencing the issue!
