### ISSUE TITLE
No timeout when registry is unreachable

### ISSUE THREAD

**Issue by tanepiper** [tjunnone/npm-check-updates#290]
Today, with the DynDNS outage that caused the NPM registry to be un-contactable - before I was aware of this I ran npm-check-updates on a repository I'm working on.

At no point did it time out, it sat for about 20 minutes just spinning while trying to resolve it.  I had run it, gone away to grab a coffee and came back a bit later only to notice this when I was about to start writing code again.

**Comment by raineorshine** [comment]
Good call. It would be better if it timed out and notified you that there may be network issues.

**Comment by raineorshine** [comment]
`--timeout <ms>` option added.

Published in [`v2.11.0`](https://github.com/tjunnone/npm-check-updates/releases/tag/v2.11.0)
