### ISSUE TITLE
`--all` without upgrading?

### ISSUE THREAD

**Issue by mathieumg** [tjunnone/npm-check-updates#291]
Is there a way to list all latest versions (like `--upgradeAll` does), without actually doing the upgrade? Ideally, I imagine `--all`/`-a` and `--upgrade`/`-u` would be two separate commands and you would just do `--all --upgrade`/`-au` if you wanted to do both, much more intuitive (and flexible). 

I realize this is a breaking change, but are you open to a PR that implements this approach, or is there already an obvious way to do this and I've missed it? :blush: Thanks!

**Comment by raineorshine** [comment]
Hi Mathieu! Thanks for the suggestion. Actually, the default behavior is to list all latest versions, including those that are satisfied by the declared version range. There is an explanatory message separating the two:

```
The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use ncu -a/--upgradeAll.

 react-select  ^1.0.0-beta13  →  ^1.0.0-rc.2 
```

Does the default behavior satisfy your request, or are you looking for something else? I realize that the various options for all/greatest/latest and upgrade/non-upgrade can be confusing.

**Comment by mathieumg** [comment]
You are right, seems to be the case. There must be an other underlying issue, I have many dependencies that should show up on that list, but don't. (Which would explain that none did when I tested with a smaller repository) For instance, I have both of these (among others):

```js
  "async": "^2.0.1",
  "lodash": "^4.15.0",
```

and they don't show up on that second list, despite `async@2.1.2` and `lodash@4.16.6` existing. Do you want me to open a separate issue for that?

**Comment by mathieumg** [comment]
Looks like I was hit by https://github.com/tjunnone/npm-check-updates/issues/263

Will track it there. My old version of this tool didn't rely on installed version but what is in the package, which was the better behavior I believe.

Thanks!

**Comment by raineorshine** [comment]
Good catch. The special case for installed packages is confusing and will
be removed in the next major version.
