### ISSUE TITLE
dark blue uses for highlighting important thing in cli. --> impossible to read on black

### ISSUE THREAD

**Issue by rtack** [tjunnone/npm-check-updates#294]
![image](https://cloud.githubusercontent.com/assets/5379/20305032/b8ad9060-ab33-11e6-9d87-89c56d078e68.png)

**Comment by raineorshine** [comment]
Hi! Thanks for reporting. It is important that the output is readable. In
this case it's likely the default settings for your terminal are not
optimal for reading certain colors. I would recommend checking the settings
of your terminal to set the color of blue to be lighter if you have a dark
background. I am not able to control the shade of blue from
npm-check-updates.

**Comment by rtack** [comment]
The color blue as used for the directory listings of e.g. the `ll` command works just fine and is readable. It looks bolder though. 

konsole with "linux colors" scheme (the default)
![image](https://cloud.githubusercontent.com/assets/5379/20310503/847982a4-ab4c-11e6-8fa1-c97b9d23e510.png)
terminal 
![image](https://cloud.githubusercontent.com/assets/5379/20310520/94f76290-ab4c-11e6-827f-70238b19675c.png)

in both cases the chosen blue doesn't work very well. 
I realise now that I can configure the colors to my liking but wanted to point out that ncu is the command line program that I use that suffers from this. And I am using default terminal/konsole settings of my distro.

It might be worth changing to the other like the one "git" uses in the attached screenshots here.
If not this can be closed.

**Comment by raineorshine** [comment]
Great, thank you for the additional information. That helps to know that
there may be a better blue to use.

Note that I might not be able to change the update message at the top that
says `run npm install -g npm-check-updates to upgrade` since that is a
separate library.
