### ISSUE TITLE
yarn conflict

### ISSUE THREAD

**Issue by ghost** [tjunnone/npm-check-updates#298]
Installed with next command
```
yarn global add package
```
after using 
```
ncu
```
console is shutting down.

After install through npm like in docs and works fine.

Thank you.

**Comment by raineorshine** [comment]
Thanks for reporting! I will investigate as soon as I get a chance.

You may already be aware of this, but in the mean time, if you install ncu
with npm then you can still use it on projects that use yarn.

**Comment by GabrielQDuarte** [comment]
Can confirm that this really happens. Did the same steps as ghost.

I'm using windows, when i run cmd /k ncu, i can see the error, which is something like 

> "$basedir/C:/Users/my_profile_name/AppData/Local/Yarn/config/global/node_modules/.bin/ncu.cmd"   "$@"
> The filename, directory name, or volume label syntax is incorrect"

I'm using windows with pt-br locale, so i translated the error to what it should be in english (the original one is "A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.")

**Comment by anantoghosh** [comment]
This is a known issue with yarn on window. Temp fix https://github.com/yarnpkg/yarn/issues/1324#issuecomment-256078658

**Comment by Deathis** [comment]
command : yarn global add yarn 

Then I can't yarn global remove yarn !!!
My yarn down !!!
Can't do anything!!!
Help!!!

**Comment by raineorshine** [comment]
Are you posting in the right place? If so, please describe details of where
ncu is behaving differently than expected. So far everything mentioned
seems to be an issue with yarn itself. Thanks!

**Comment by raineorshine** [comment]
Seems like this is a dependency bug. Closing.
