### ISSUE TITLE
Combination version ranges

### ISSUE THREAD

**Issue by hashchange** [tjunnone/npm-check-updates#30]
When running `npm-check-updates -u`, the version range

    "dependencies": {
      "backbone": "^1.0.0 <1.2.0",
      "underscore": "^1.5.0 <1.7.0"
    }

morphs into

    "dependencies": {
      "backbone": "^1.1.2..",
      "underscore": "^1.7.0.."
    }

**Comment by metaraine** [comment]
Cool. Now for implementing it :)

**Comment by metaraine** [comment]
v2 is out! Hopefully it is more intuitive now.

From the documentation:

```
- Dependencies with less-than relations (e.g. `<1.0.0` or `<=1.2`) are converted 
to semantic wildcard relations (e.g. `^2.0.0` or `^2.0`). This change was made 
because if you are going to upgrade these to backwards-incompatible versions, 
the less-than contraint will no longer be relevant.
```

**Comment by hashchange** [comment]
Great, thanks!
