### ISSUE TITLE
"spawn npm ENOENT" error on Windows 10 x64.

### ISSUE THREAD

**Issue by carmelone** [tjunnone/npm-check-updates#301]
I'm getting this error using this:

```
const upgraded = ncu.run({
    packageFile: 'package.json',
    packageFileDir: true,
    jsonUpgraded: true,
    upgradeAll: false
})
```

**Comment by raineorshine** [comment]
Thanks for reporting this! Did you say that you don't get the error when `packageFileDir` is false? Please include all relevant information.
