### ISSUE TITLE
Semver update problem

### ISSUE THREAD

**Issue by pyalxx** [tjunnone/npm-check-updates#304]
Hi, thanks for nice package. 

I have following package.json dependencies:

```
"devDependencies": {
    "eslint": "^3.11.0",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-friendly-formatter": "^2.0.6",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.7.1",
    "nodemon": "^1.11.0"
  }
```

Following semver (taken from https://github.com/npm/node-semver doc) `^2.2.3: >= 2.2.3 and < 3.0.0`

Though `ncu -u` gives:

`eslint-plugin-jsx-a11y  ^2.2.3  →  ^3.0.1`

I want to use programatic API of package, but such behavior will break setup.

Please, let me know if it is an issue, or I'm using package wrong. Thanks!

**MacOS 10.2.1**
**npm 3.10.9**

**Comment by raineorshine** [comment]
Hi! Thanks for asking. I think I need a bit more explanation to understand
what you are asking? What is it that you expect, and what is behaving
differently? I will respond with my best guess at what might be relevant
for you below, but let me know if you're asking something different.

The example you provided looks right to me. npm-check-updates is meant to
upgrade versions beyond their semver constraints. It is meant to force a
backwards-incompatible change. If you want to upgrade within your specified
dependency range, use `npm update`.

**Comment by pyalxx** [comment]
Thanks for fast follow up!

In my case, upgrading `eslint-plugin-jsx-a11y` will break `eslint-config-airbnb, but I overlooked package behavior as you pointed out indeed. 

Will use it right now on, thanks!
