### ISSUE TITLE
NCU not finding package.json by default

### ISSUE THREAD

**Issue by markau** [tjunnone/npm-check-updates#306]
I didn't think `ncu` was working, until I added the `-l verbose` flag to see that it wasn't finding the `package.json` file. I had to explicitly add the `--packageFile ./package.json` flag.

v2.8.8 on Windows 10 x64 (git bash shell).

Thanks for the otherwise painless package upgrades!

**Comment by raineorshine** [comment]
Thanks for reporting! Did it say where it was looking? It should look first
in the current working directory. Also, was it just hanging? In that case,
it may have been looking on stdin, which is a known issue on Windows.

**Comment by markau** [comment]
hey @raineorshine you've got it.. `Waiting for package data on stdin...`.  I'll close the issue as I just noticed it in the `README.md`.  oops 😨  Thanks.

**Comment by raineorshine** [comment]
Thanks!

The next major version will make stdin opt-in as a good Windows solution hasn't emerged.
