### ISSUE TITLE
Doesn't find latest version of mongodb driver

### ISSUE THREAD

**Issue by Brade** [tjunnone/npm-check-updates#31]
When I run npm-check-updates for a project that specifies "mongodb":"1.4.x" it says all my packages are up to the latest, even though there is a mongodb version 2.0.5 now. When I replace all my dependency versions to "*" and run "npm outdated" it DOES find the latest mongodb. So what gives?

**Comment by metaraine** [comment]
Changed npm-check-updates to never downgrade. Published on unstable tag. Feedback welcome!

`npm install npm-check-updates@unstable`

**Comment by metaraine** [comment]
Added -t/--greatest flag to look for highest version number available (v2.0.0-alpha4).
