### ISSUE TITLE
"ncu -u" not working

### ISSUE THREAD

**Issue by nndung179** [tjunnone/npm-check-updates#310]
* node version: v5.1.1
* npm version: 3.10.6
* npm-check-updates version: 2.8.9

---------------------------

Hi!

I have used `ncu -u` to update my `package.json`. But It's seen to be not working. I have upgraded to a newest version. But it is still the same.

**Comment by raineorshine** [comment]
Hi! A couple questions:

Do you see any output? If so, what is it?
Does ncu without the -u work? What is its output?

**Comment by raineorshine** [comment]
I see. Can you run it with --loglevel verbose and tell me what you get? I
think that will tell us which package file it is writing to. One some
systems you have to specify --packageFile explicitly.

**Comment by gtothesquare** [comment]
Hi I'm getting the same problem. Here is my outputs:

```
Initializing...
Running in local mode...
Finding package file data...
Using [path to my package.json]/package.json
Getting installed packages...
Fetching latest versions...
⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ :
The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use ncu -a/--upgradeAll.

 autoprefixer             ^6.5.3  →   ^6.6.1 
 babel-core              ^6.18.2  →  ^6.21.0 
 babel-loader             ^6.2.8  →  ^6.2.10 
 cross-env                ^3.1.3  →   ^3.1.4 
 elasticsearch           ^12.1.0  →  ^12.1.3 
 helmet                   ^3.1.0  →   ^3.3.0 
 html-webpack-plugin     ^2.24.1  →  ^2.25.0 
 node-cache               ^4.1.0  →   ^4.1.1 
 postcss-loader           ^1.2.0  →   ^1.2.1 
 sass-loader              ^4.0.2  →   ^4.1.1 
 enzyme                   ^2.6.0  →   ^2.7.0 
 eslint                  ^3.11.1  →  ^3.12.2 
 jsdom                    ^9.8.3  →   ^9.9.1 
 sinon                   ^1.17.6  →  ^1.17.7 
 webpack-dev-middleware   ^1.8.4  →   ^1.9.0 
 webpack-hot-middleware  ^2.13.2  →  ^2.14.0 
```
Then when I try `ncu -a/--upgradeAll.` it outputs
```
Using [path to my package.json]/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠋ :
All dependencies match the latest package versions :)

```
It seems it ignores minor upgrades.

**Comment by raineorshine** [comment]
Thanks. Can you also provide the output of npm outdated? I'd like to see if
your installed versions differ from what is listed.

**Comment by gtothesquare** [comment]
@raineorshine let me get back to you since I need access to my home computer.

**Comment by gtothesquare** [comment]
@raineorshine yes they do 
```
Package         Current         Wanted  Latest  Location
istanbul  1.1.0-alpha.1  1.1.0-alpha.1   0.4.5  express-webpack2-react
webpack      2.2.0-rc.3     2.2.0-rc.3  1.14.0  express-webpack2-react
```

**Comment by raineorshine** [comment]
Hmmm I'm not sure if I have enough information to troubleshoot. Can you try
deleting your node_modules folder and running again?

**Comment by gtothesquare** [comment]
I did that with a empty node_modules and it will show you a list of all packages in package.json. The problem is not when you upgrades mayor versions. It upgrades when you have this difference:
`node-sass  3.13.0  →  4.1.1` 

This is the output I got in another project:
```
 node-sass  3.13.0  →  4.1.1 

The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use ncu -a/--upgradeAll.

 autoprefixer          ^6.5.3  →   ^6.6.1 
 cross-env             ^3.1.3  →   ^3.1.4 
 helmet                ^3.1.0  →   ^3.3.0 
 html-webpack-plugin  ^2.24.1  →  ^2.26.0 
 sinon                ^1.17.6  →  ^1.17.7 

```
however `ncu -a/--upgradeAll` is not working properly, it does not upgrade minors.

**Comment by raineorshine** [comment]
Okay, thanks for the additional information. I am traveling abroad for the
next couple weeks without a computer so won't be able to investigate
further right away. If you are able to troubleshoot the problem, post here
with any updates. Otherwise I will add it to my list when I return. Thanks!

**Comment by Mizstik** [comment]
Confirming the same issue. -u does not work when used together with -a/--upgradeAll.

**Comment by raineorshine** [comment]
@Mizstik `-a` and `-u` are redundant. `-u` is always implied when `-a` is provided.

@gtothesquare @nndung179 I went through the following steps to attempt to reproduce your issue.

1. created a new package.json in a new directory
2. `npm install --save helmet@^3.1.0
3. `ncu -a`

```sh
Using /Users/raine/test/temp/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠏ :

 helmet  ^3.1.0  →  ^3.4.0 

Upgraded /Users/raine/test/temp/package.json
```

```
$ cat package.json

{
  "dependencies": {
    "helmet": "^3.4.0"
  }
}
```

As you can see, it works as expected. Are you able to reproduce the issue from an empty directory? Does the issue only occur with certain packages? Please let me know if you are able to determine any additional information that will help us troubleshoot for you! Thanks!

**Comment by Mizstik** [comment]
Hahaha. Well, I literally typed:

`ncu -a/--upgradeAll`

You might consider revising the on-screen help that appears. It actually led me to believe I should type ncu -u -a/--upgradeAll.

**Comment by raineorshine** [comment]
**[off-topic]**
@Mizstik I would be open to a more intuitive way of writing this. Do you have a suggestion that is compact but makes it clearer that the short and long flags are two different options? There might be a linux standard I am not familiar with as well.

**Comment by Mizstik** [comment]
Personally I would only show -a in a message that routinely shows up like this. The user can find out the long form in -h.

I would also move ncu -u to above the paragraph.

This is based on my previous misunderstanding though. For actual standards you might want to ping the experts.

**Comment by raineorshine** [comment]
@Mizstik Cool, thanks for your input.

**Comment by nndung179** [comment]
hi @raineorshine,

+ I have upgraded my node from v5.1.1 => v6.5.0 & v7.4.0 => It **worked**

+ v5.1.1 => still not working, I have tried in different machine: windows, mac. It is still the same. Below is an info:

```
version: v5.1.1
npm version: 3.10.6
npm-check-updates version: 2.8.9
```

**Comment by raineorshine** [comment]
Thank you! That is good to know. I will test on v5.1.1 and see if I can
reproduce.

**Comment by raineorshine** [comment]
@nndung179 I have v5.1.1 installed now and I am ready to test. Can you provide the minimum dependency specification that reproduces the issue? Thanks!

**Comment by nndung179** [comment]
hi @raineorshine!

I have used the `package.json` of [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate). You can clone it into your machine.

commands to run:
1. cd to project
2. run commands below:
```
npm i
```

```
npm start
```

**Comment by raineorshine** [comment]
@nndung179 I have tested ncu on a fresh clone of react-boilerplate with your versions of node, npm, and ncu. Unfortunately I am unable to reproduce. It works every time for me.

**Comment by raineorshine** [comment]
@nndung179 Can you print the results of `--loglevel verbose` in case that gives us more information? Or if you are content to have it working on the latest version and do not want to troubleshoot any more that is okay, too.

**Comment by nndung179** [comment]
@raineorshine. Unfortunately, I did not keep the old configurations. If so, you could temporary close this topic. I will keep my eyes on a test case next time. Thanks for your supporting.

**Comment by raineorshine** [comment]
Okay, thanks :).

@gtothesquare Are you still having issues? Can you narrow it down to a single package or version of node/npm? Thanks.

**Comment by gtothesquare** [comment]
@raineorshine I figure out what was my problem (we shouldn't just copy paste ). I was just copy/pasting `ncu -a/--upgradeAll` which will not work off coarse since its either `ncu -a` or `ncu --upgradeAll` :)

**Comment by raineorshine** [comment]
@gtothesquare Aha! That is good feedback. I will update the formatting on that message so it is less confusing. Thanks!

**Comment by mahios2015** [comment]
try npm install -g npm-check-updates -u
