### ISSUE TITLE
Feature please make an attribute that removes the accents in version

### ISSUE THREAD

**Issue by joelharkes** [tjunnone/npm-check-updates#313]
when i run ncu on a project the output i get is:

 body-parser  ^1.15.2  →  ^1.16.0
 eslint       ^3.12.2  →  ^3.13.1

this is because on npm install the dependency was added with the accent (^). 

It would be nice to automatically remove these accents and use hard versions instead, based on an attribute say: --remove-accents.

result would be:

 body-parser  ^1.15.2  →  1.16.0
 eslint       ^3.12.2  →  3.13.1

**Comment by raineorshine** [comment]
I support that idea. I think it should be called `--remove-range` to support the removal of all version range syntax.

**Comment by joelharkes** [comment]
Exactly, thanks for the addition.

The reasons are actually described well by an npm comparator: http://www.eloquentwebapp.com/yarn-new-package-manager-javascript/

**Comment by raineorshine** [comment]
Cool! Are you available to assist with a pull request? I am currently the
only maintainer of the project. I have a list of tasks currently.

**Comment by joelharkes** [comment]
Alright, ill see if i have time, but i'm generally very busy.

**Comment by karanjthakkar** [comment]
@raineorshine I can help with this. I'm thinking the changes to be done are only in the `updatePackageData` method in `versionmanager.js`? Or would there also be changes in the `printUpgrades` method?

**Comment by raineorshine** [comment]
Thanks @karanjthakkar! The main change would need to be made in [upgradeDependencyDeclaration](https://github.com/tjunnone/npm-check-updates/blob/master/lib/versionmanager.js#L34), plus all the places the command line option needs to be added (which is easiest to determine by tracing another command line option through from the beginning).
