### ISSUE TITLE
ncu stops with find

### ISSUE THREAD

**Issue by gdeward** [tjunnone/npm-check-updates#316]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.9.4
* npm version: 4.1.2
* npm-check-updates version: 2.8.9

---------------------------

Please help me understand why ncu is causing a `find` operation to stop after the first file?  I have 25 project folders, all with their own `package.json` and `bower.json` file (not all have `bower.json`).

Issuing this command with an `echo` works perfectly:

    find ../ -name "package.json" -type f -exec echo '{}' +

... all files are printed to the screen.

However, this syntax stops after the first file when I use ncu:

    find ../ -name "package.json" -type f -exec ncu -u -a --packageFile '{}' +

Here's the only output of the command:

    $ find ../ -name "package.json" -type f -exec ncu -u -a --silent --packageFile '{}' +
    Using /home/joeblow/projects/app01/package.json
    [..................] - :
    All dependencies match the latest package versions :)

The versions I'm using is:

    bash version: 4.3.42(1)-release
    find version: 4.7.0-git
    node version: 6.9.4
    npm version: 4.1.2
    npm-check-updates version: 2.8.9

**Comment by raineorshine** [comment]
Thanks for providing the detailed report!

This is really a bash issue, so I'm limited in how much I can assist here, but I was curious and played around with it and perhaps my findings will solve your problem!

```
find ../ -name "package.json" -type f -exec ncu -a --loglevel silent --packageFile '{}' \;
```

I don't know how to get it to work with the "+" at the end (or really how it is any different) but I tested the above and it works across multiple files. Key difference: Use the `;` terminator and make sure it's escaped.

I changed `--silent` to `--loglevel silent` as the former appears to be broken 😬 . 

(Careful with this command as it will also update nested package.json files within your node_modules directories, which you probably don't want!)
