### ISSUE TITLE
README not visible on npmjs package page

### ISSUE THREAD

**Issue by dkris** [tjunnone/npm-check-updates#319]
-  [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
-  [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: NA
* npm version: NA
* npm-check-updates version: NA

---------------------------
The README section on [npm-check-updates
](https://www.npmjs.com/package/npm-check-updates) has no readme section.

**Comment by raineorshine** [comment]
Thanks. Probably the result of a force commit or something. It will get updated in the next patch!
