### ISSUE TITLE
Can we have an option to force remove compatibility version range?

### ISSUE THREAD

**Issue by betimer** [tjunnone/npm-check-updates#327]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.10
* npm version: 4.05
* npm-check-updates version: 2.10.3

---------------------------

I have package.json:
  "dependencies": {
    "express": "^4.14.1",
    "socket.io": "^1.7.3",
    "socket.io-redis": "^4.0.0",
    "winston": "^2.3.1",
    "yargs": "^6.6.0"
  }

Can we have a option to just upgrade but remove all ^ and ~ stuff?
Because it is much safer on production.
Thanks

**Comment by karanjthakkar** [comment]
@betimer Does `--removeRange` seem to be what you want to do?

**Comment by betimer** [comment]
@karanjthakkar `--removeRange` only checks the version, but it does not set to be exact version. I mean 1.2.3 instead of ^1.2.3

**Comment by karanjthakkar** [comment]
@betimer Ahh, I understand what you want. `--removeRange` will only work for dependencies who have a newer version. And for those newer version in the package it will remove the version range. For those dependencies of which it doesn't find a new version, it won't _just_ strip the version ranges for them.

**Comment by betimer** [comment]
I see. I have just tried, yes it works if the package is not up-to-date, and that parameter did remove the range. I tried `ncu -a --removeRange`

Cool. Thanks. Happy to close it. Will do it.

**Comment by karanjthakkar** [comment]
@betimer Glad I could help :)
