### ISSUE TITLE
Running multiple integrations simultaneously return same result 

### ISSUE THREAD

**Issue by vandernorth** [tjunnone/npm-check-updates#328]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.9.1
* npm version: 3.10.8
* npm-check-updates version: 2.10.3

---------------------------
I have a build-script in which I verify if any updates are required on two projects, this means two package.json's. When running this, both execution always return the same result. 

Script:
`const npm     = require('npm-check-updates');`
`npm.run({ packageFile: 'pack1.json', silent: true }).then(upgrade => { console.info('Updates #1:', upgrade); });`
`npm.run({ packageFile: 'pack2.json', silent: true }).then(upgrade => { console.info('Updates #2:', upgrade); });`

pack1.json
`{
  "name"        : "part-1",
  "dependencies": {
    "jquery": "^1"
  }
}`

pack2.json
`{
  "name"        : "part-2",
  "dependencies": {
    "lodash": "^1"
  }
}`

Result:
Updates #1: { lodash: '^4' }
Updates #2: { lodash: '^4' }

**Comment by raineorshine** [comment]
Thanks, will investigate as soon as I have time!

In the mean time, have you tried running them serially instead of in parallel, in case there is some shared state that is causing problems?

**Comment by vandernorth** [comment]
@raineorshine Yeah letting the second run wait for the first one to finish works.

**Comment by raineorshine** [comment]
Okay, thanks for reporting! This is a bug. I am not sure the architectural implications of removing the shared state. I will leave this open for a pull request and put it on my long term list of bug fixes.

**Comment by karanjthakkar** [comment]
@vandernorth @raineorshine Have sent a PR that fixes this. It now outputs:

```
Updates #2: { lodash: '^4' }
Updates #1: { jquery: '^3' }
```

instead of outputting `lodash` everytime.

**Comment by raineorshine** [comment]
Published in [v2.10.5](https://github.com/tjunnone/npm-check-updates/releases/tag/v2.10.5).
