### ISSUE TITLE
Windows scripts to accomplish similar behavior as ncu

### ISSUE THREAD

**Issue by hack2root** [tjunnone/npm-check-updates#330]
Windows cmd scripts to total update (both global and local)

https://gist.github.com/hack2root/722d63333efea0ec3c7cf8b20e33524d
https://gist.github.com/hack2root/8c6da298f4d04abce0c84e9273034df0

update-global.cmd:

@setlocal ENABLEDELAYEDEXPANSION
@echo off
:loop
set /a count = 0
for /f "eol=! tokens=1,2,3,* delims=: " %%i in ('ncu -g') do (
  if "%%j"=="%%l" (
    echo %%i %%j
  ) else (
    if "%%i"=="All" (
      echo %%i: %%j - %%l
      goto:eof
    ) else (
      set /a count += 1
      echo %%i: %%j - %%l >> %%i.ncu
      echo updating %%i: %%j %> %%l
      echo running npm install -g %%i
      npm install -g %%i
    )
  )
)
if "%count%"=="0" goto:eof
goto loop

update-local.cmd:

@setlocal ENABLEDELAYEDEXPANSION
@echo off
:loop
@set /a count = 0
@for /f "eol=! tokens=1,2,3,* delims= " %%i in ('ncu -u') do @(
  @if "%%j"=="%%l" @(
    echo %%i %%j
  ) else @(
    @if "%%i"=="All" @(
      @echo %%i: %%j - %%l
      @goto:eof
    ) else @(
      @if "%%i"=="Using" @(
        @echo %%i %%j %%k %%l
        @set /a count += 1
        @npm update
      ) else @(
        @if "%%i"=="The" @(
          @echo %%i %%j %%k %%l
          @set /a count += 1
        ) else @(
          @set /a count += 1
          @echo %%i: %%j - %%l >> %%i.ncu
          @echo updating %%i: %%j %> %%l
          @echo running npm install %%i
          @npm install %%i
        )
      )
    )
  )
)
@if "%count%"=="0" @(goto:eof)
goto loop

- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 
* npm version: 
* npm-check-updates version: 

---------------------------

**Comment by raineorshine** [comment]
Hi! Thanks for posting. I am assuming you are just offering this as an alternative approach to updating all npm dependencies? I can keep this as a `FAQ` is that's the case, so that it might help other users. If you had a different intention for posting, please let me know!
