### ISSUE TITLE
Error with file:dependencies

### ISSUE THREAD

**Issue by mriehema** [tjunnone/npm-check-updates#334]
* node version: 6.10.0
* npm version: 3.10.
* npm-check-updates version: 2.10.3

We have some local file dependencies, which cannot be handled. Example:

```
 "devDependencies": {
    "@test/grunt-utils": "file:lib/tools/grunt"
  }
```

If I run `ncu`, I get:

```
npm ERR! registry error parsing json
Unhandled rejection SyntaxError: Unexpected token < in JSON at position 1
```

See https://docs.npmjs.com/files/package.json#local-paths

**Comment by raineorshine** [comment]
Hi! Thanks for the information and for reporting.

I have tested local paths with `npm-check-updates` and they appear to work fine. You can see an example repo here: https://github.com/raineorshine/npm-check-updates-334

This makes me think that there might be something wrong with your package.json in `lib/tools/grunt`. The error `Unexpected token < in JSON at position 1` suggests that your package.json is malformed. Can you investigate that possible cause further, or provide an example repo that I can reproduce the error in?

**Comment by mriehema** [comment]
Thanks for ypur reply. I retested it today:

```
λ ncu
Using C:\dev\frontend\package.json
[..................] - :
All dependencies match the latest package versions :)
```

Everything looks fine. the `package.json` in `lib/tools/grunt` looks fine too. Maybe it was a problem with the registry server.

**Comment by raineorshine** [comment]
Great! Glad you figured it out!
