### ISSUE TITLE
Feature request: Show timestamps

### ISSUE THREAD

**Issue by s10wen** [tjunnone/npm-check-updates#335]
As well as showing the latest version, would it be possible to add a flag to show timestamps:
```
my-npm-package  0.22.6 20/03/2017 17:14  →  0.24.0 23/03/2017 17:14
```

and better still, the difference:
```
my-npm-package  0.22.6 20/03/2017 17:14  →  0.24.0 23/03/2017 17:14 => 3 days out of date
```

**Comment by raineorshine** [comment]
Good idea! This appears to be quite possible with `npm view PACKAGE_NAME time`.

There are currently some active bugs that I have as a priority, but I will support anyone who wants to try this on as a pull request!

**Comment by karanjthakkar** [comment]
@raineorshine Should we give this a shot in v3?

**Comment by raineorshine** [comment]
@karanjthakkar I think there are other higher priorities at the moment.
