### ISSUE TITLE
Fails to identify any outdated dependencies

### ISSUE THREAD

**Issue by callumlocke** [tjunnone/npm-check-updates#337]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 7.8.0
* npm version: 4.2.0
* npm-check-updates version: 2.10.5

---------------------------

npm-check-updates is currently failing to do anything for me. I've tried removing and reinstalling it.

**To reproduce:**

1. clone [this repo](https://github.com/airbnb/react-with-styles)
2. Run `ncu --upgradeAll`

**Expected behaviour:** it should update several dependencies.

**Actual behaviour:** it just prints "All dependencies match the latest package versions :)" and exits.

**Comment by callumlocke** [comment]
seems to have fixed itself

**Comment by raineorshine** [comment]
Sorry for the trouble!
