### ISSUE TITLE
Run tests between each update, or update a single package?

### ISSUE THREAD

**Issue by xdumaine** [tjunnone/npm-check-updates#338]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.
---------------------------

This is more of a two part question than an issue. Is there a method of using this package to update dependencies one at a time, and run tests, in a kind of bisect pattern? My goal is to quickly (or using automation) run through one update at a time, run tests, then continue. Alternatively, I could make this work with a script if there's a method to just accept a single update, instead of all at once - is that possible?

**Comment by karanjthakkar** [comment]
Hey @xdumaine, really excited to hear that you want the iterative upgrade feature! It is something we [have discussed](https://gitter.im/npm-check-updates/Lobby?at=58a9d09af045df0a2269e170) amongst us recently. We don't have an plan for this feature in place yet. Its a significantly big feature and there are time constraints on our end to implementing this. So, to answer your question, there is no way to update packages one at a time using `ncu`.

If you think you would like to work on adding this feature, I would love to help you with this! In the meanwhile, you can check out https://github.com/peerigon/updtr to see if it supports your use case.

**Comment by raineorshine** [comment]
@xdumaine Here's my pseudocode for the feature if you're curious. I would love to add this.

To answer the second part of your question, you can target a single package simply by adding a command line argument:  `ncu packageName`.

```
iterative upgrade

- option: bail on first failure
- option: run tests with no upgrades
- option: do not test non-major updates
- find upgraded deps
- upgradeIterative(deps, { bail })
  - // if there are no deps, we can skip the tests since know they will pass
  - if deps.length == 0
    - return ([ ], [ ])
  - upgrade deps in original package 
  - npm update
  - run tests
  - if tests pass
    - return (deps, [ ], [ ])
  - else return (switch deps.length)
    - // if there is only 1 dep, we know it is causing the failure
    - 1
      - ([ ], deps, [ ])
    - // otherwise we have to split the deps and continue testing
    - else
      - (safe1, unsafe1, unknown1) = upgradeIterative(deps1)
      - if unsafe1.length > 0 && bail
        - return (safe1, unsafe1, unknown1.deps2)
      - (safe2, unsafe2, unknown2) = upgradeIterative(deps2)
      - return (safe1.safe2, unsafe1.unsafe2, unknown1.unknown2)
```
