### ISSUE TITLE
Do you know how I can update ncu with linked libs

### ISSUE THREAD

**Issue by patrikx3** [tjunnone/npm-check-updates#340]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 
7.9
* npm version: 
4.5
* npm-check-updates version: 
2.10.5

---------------------------
Hi! How are you?
Do you know how I can update ncu with linked libs?
In the registry it show the latest version but ncu doesn't find it.
Thanks so much!

**Comment by karanjthakkar** [comment]
@patrikx3 Can you please explain what you mean by linked libs? Also, please paste an example of what your `package.json` looks like and what you expect to update. This would give us more information to help you faster.

**Comment by patrikx3** [comment]
hi! never mind, i have to unlink npm, if there is a linked npm, i cannot update anyhow, so ncu is good. thanks!!!
