### ISSUE TITLE
Change the color from blue to something else.

### ISSUE THREAD

**Issue by skorunka** [tjunnone/npm-check-updates#346]
Change the color from blue to something which is better readable while running ncu in windows PowerShell.

The problematic text: `Run **ncu** with **-u** to upgrade package.json`

The **ncu** and **-u** are in blue color which is hardtly readable in powershell:

![image](https://cloud.githubusercontent.com/assets/218913/25890383/27f3354a-3565-11e7-9864-03037381cf09.png)

In general, replacing the "blue" color with "cyan" would solve the issue.

Thank you.

**Comment by raineorshine** [comment]
Tried to fix this before, but did the opposite!
https://github.com/tjunnone/npm-check-updates/commit/4f497269d72e2cfd1c4f7e409a89aa5e55ce43e6

Fixed and published in [v2.11.1](https://github.com/tjunnone/npm-check-updates/releases/tag/v2.11.1).

**Comment by skorunka** [comment]
@raineorshine Lovely! Thank you.
![image](https://cloud.githubusercontent.com/assets/218913/25940136/028a671a-362d-11e7-981f-960c10514047.png)
