### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by stevenvachon** [tjunnone/npm-check-updates#347]
I install this module locally to projects via npm scripts for other team members:
```json
"devDependencies": {
  "npm-check-updates": "^2.11.1"
},
"scripts": {
  "updates": "ncu -a && npm install"
}
```

Whenever I try to update and install this local devDependency, I get this error:
```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/project/node_modules/.bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! path /project/node_modules/npm-check-updates/node_modules/get-stdin
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/project/node_modules/npm-check-updates/node_modules/get-stdin'
npm ERR!  { Error: EACCES: permission denied, rmdir '/project/node_modules/npm-check-updates/node_modules/get-stdin'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/project/node_modules/npm-check-updates/node_modules/get-stdin',
npm ERR!   parent: 'project' }
```

Local dependencies shouldn't require `sudo` or any special permissions.

**Comment by raineorshine** [comment]
I was able to successfully run this script in a mock project with a package.json like yours. That seems to indicate that there may be some permission issue specific to your environment, although I agree that sudo shouldn't be required for install.

Can you clarify, does the error occur when you run the `updates` script or just when you run `npm install` with this package.json?

**Comment by stevenvachon** [comment]
The error only occurs when I run `npm install`.

**Comment by raineorshine** [comment]
Are you able to install other npm modules successfully without this error? So npm-check-updates is the only module that causes this problem for you?

**Comment by stevenvachon** [comment]
Yes, this is the only module.

**Comment by raineorshine** [comment]
I'm not sure I know how to move forward on this. I am unable to reproduce
on my end. If anyone has any ideas please let me know.

One other thought: You could trying installing the node version manager,
nvm, and see if you can install npm-check-updates on a version of node
installed with nvm since it stores it in a different location where the
permissions may be different.

**Comment by stevenvachon** [comment]
This doesn't seem to be happening anymore now that I'm using npm5

**Comment by raineorshine** [comment]
Okay!
