### ISSUE TITLE
does not work with nvm (version number)

### ISSUE THREAD

**Issue by betimer** [tjunnone/npm-check-updates#349]
I really like this tool, very helpful to me.

* node version: 7.10.0 (node -v)
* npm version: 4.4.4 (npm -v)
* npm-check-updates version: 2.11.1 (ncu -v)

--------------------------- issues ----
1. ncu -g, shows incorrect version of existing global package.
2. after npm i -g npm-check-updates, still shows the previous version (shows in the log below), but the actual global package has been updated

--------------------------- logs ----
ncu -g I got:
PS C:\Repo\vcc-db-mssql> ncu -g
[..................] \ :
 azure-cli            0.10.12  →  0.10.13
 eslint-plugin-react   6.10.3  →    7.0.0
 express-generator     4.14.1  →   4.15.0
 npm                    4.0.5  →    4.5.0
 npm-check              5.4.0  →    5.4.4
 npm-check-updates     2.11.0  →   2.11.1
 webpack                2.4.1  →    2.5.1

**Comment by raineorshine** [comment]
Can you run the following two commands and post your results? That will maybe give more information about where ncu is running.

```
$ type ncu
ncu is /Users/raine/.nvm/versions/node/v6.1.0/bin/ncu

$ npm -g prefix
/Users/raine/.nvm/versions/node/v6.1.0
```

**Comment by raineorshine** [comment]
Also, you may want to check out #163. Possible duplicate.

**Comment by raineorshine** [comment]
@betimer Following up to see if we can troubleshoot this issue more for you.

**Comment by betimer** [comment]
Sorry, I lost my environment, nvm gets removed, using node directly.

**Comment by raineorshine** [comment]
@betimer Okay, I will close, but feel free to re-open if it's still an issue. Thanks!
