### ISSUE TITLE
Deprecate npm commands api

### ISSUE THREAD

**Issue by raineorshine** [tjunnone/npm-check-updates#350]
We should not use `npm.commands` anywhere (https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L21). Instead we should invoke npm as a child_process and parse the results, as done here: https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L94.

This ensures that npm-check-updates is using the user's installed npm version rather than the one that ships with npm-check-updates.

**Comment by bastienmoulia** [comment]
I agree, npm should not be required as a dependency because the difference of version with the global npm can cause bugs (like https://github.com/parshap/check-node-version/issues/12).

**Comment by vdh** [comment]
These dependencies on `npm` and `npmi` appear to be the cause of #333

**Comment by raineorshine** [comment]
Addition information in https://github.com/tjunnone/npm-check-updates/pull/408#issuecomment-401425596

**Comment by raineorshine** [comment]
Fixed in `v3` branch via https://github.com/tjunnone/npm-check-updates/commit/c0bd8b72fa353d6471f8ccb400d6e4d79b1568d5.

Duplicates: #408, #423, #453
