### ISSUE TITLE
[Suggestion] Dry-run mode?

### ISSUE THREAD

**Issue by t47io** [tjunnone/npm-check-updates#351]
Just a suggestion, a dry run mode (e.g. `--dry-run`) would be helpful to check available updates and decide later. Would that be hard to incorporate?

**Comment by karanjthakkar** [comment]
@t47io You can run `ncu` directly in the folder of your choice. This will tell you all the updates available. It will not modify your `package.json`. Does that seem like what you want?

**Comment by t47io** [comment]
Good point, sorry I was using `-u` as "default". Thanks!
