### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by bonesoul** [tjunnone/npm-check-updates#354]
somehow it stopped working today;

```
Unhandled rejection Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26)
```

λ ncu --version
2.11.1

λ node --version
v7.10.0

**Comment by raineorshine** [comment]
That almost seems like a networking issue. Does your internet work
everywhere else? Does ncu work on a different internet connection?

**Comment by bonesoul** [comment]
i'll check it, thanks

**Comment by raineorshine** [comment]
It could also be instability with npm. Does npm work on its own?

**Comment by bonesoul** [comment]
you were right, npm was having issues. ty.

**Comment by raineorshine** [comment]
Thanks!
