### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by skorunka** [tjunnone/npm-check-updates#359]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 7.10.0
* npm version: 4.2.0
* npm-check-updates version: 2.11.2

---------------------------
 After running "ncu" "ncu -u" the process takes a long time to finish and I got this error:
`npm ERR! registry error parsing json`

but it seems the "ncu" is working as it can give me the list of outdated packages and also update them.

**Comment by raineorshine** [comment]
Interesting. Looks like the JSON is malformed in either your package.json or in an npm response.

To clarify, are you saying that you don't get the error when you run `ncu`, but you do get the error when you run `ncu -u`?

Please post your complete package.json here.

**Comment by skorunka** [comment]
I got error for both commands.
I have just updated node to 8.0 and npm to 5.0 and no error = all works as expected. No any other changes, so it does not look like a problem with a package.json.

**Comment by raineorshine** [comment]
Glad it's working!
