### ISSUE TITLE
Bower semverLevel option not supported

### ISSUE THREAD

**Issue by Ginwu** [tjunnone/npm-check-updates#364]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version:  8.0
* npm version: 5.0.3
* npm-check-updates version: 2.11.3

---------------------------
Hello,

Thanks for your work! 

When I try:

`ncu -m bower -u --semverLevel minor`
Or 
`ncu -m bower -u --semverLevel major`

I have an error like:

> Unhandled rejection Error: Semantic versioning level "minor" is not supported for Bower

Is that normal? Since I have semver attributes in my bower.json, I didn't expected that since the option is apparently not npm only, or am I wrong?

Thanks for the help,
Ginwu

**Comment by raineorshine** [comment]
Hi! Thanks for reporting. semverLevel minor and major are not implemented
yet for bower. There are a small number of users using ncu for bower, and
so it is an even small number wanting to use it with the minor and major
semver levels. I would like to support all features, but without a large
community contributing it is difficult and issues have to be prioritized.

Can you explain more why you would like to use semverLevel? This is an
uncommon setting. Is there a reason you don't just specify version ranges
that exclude major version changes, and use bower update? Maybe bower
behaves differently than npm in this regard, but most users are satisfied
with either:

1. Upgrade major? ncu
2. Upgrade minor? npm update

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
