### ISSUE TITLE
Can not use local instance NCU, without global package installation

### ISSUE THREAD

**Issue by PredokMiF** [tjunnone/npm-check-updates#371]
I use NCU with NPM script:
```"npm_update_show": "./node_modules/.bin/ncu --packageFile package.json",```
But now it is not working:
```Unhandled rejection Error: Cannot find module 'unique-slug'```
Fix it, please.

node version: 8.1.2
npm version: 5.0.3
npm-check-updates version: 2.12.0

---------------------------

**Comment by raineorshine** [comment]
Hi! Thanks for reporting! This isn't a direct issue with npm-check-updates. It is likely an installation issue. I would recommend deleting your npm_modules folder and reinstalling. It is possible that this is not the only missing dependency.

Its dependency graph is:
npm-check-updates -> npm -> unique-filename > unique-slug

If this doesn't fix the issue, it is probably something more complicated related to having an older version of npm installed as a dependency. This is a bug in npm-check-updates, and will be resolved in the next major version release. 

Hope that helps!

**Comment by PredokMiF** [comment]
I run it from Jetbrains Idea console, but it fail.
From CMD - it works fine... I don't know whats wrong ((
