### ISSUE TITLE
add enhancement when update bower dependencies

### ISSUE THREAD

**Issue by achmadk** [tjunnone/npm-check-updates#375]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.11.0
* npm version: 4.6.1
* npm-check-updates version: 2.12.1

---------------------------
**Problem**
I have checked the latest version of bower dependencies with `ncu -m bower` command. The example result is
```javascript
I:\PROJECTS\sample>ncu -m bower
Using I:\PROJECTS\sample\bower.json

 validator-js  7.0.0  →  7.2.0

Run ncu with -u to upgrade bower.json
```
If I type that command, It will update npm dependencies to latest version, not bower ones.

**Suggestion**

Please replace `Run ncu with -u to upgrade bower.json` to `Run ncu -u -m bower to upgrade bower.json
`

**Comment by raineorshine** [comment]
Hi! Thanks for your suggestion! Notice that it says to run ncu _with_ -u. It does not suggest the complete command to run. It is just suggesting that you add the `-u` option. Hopefully that is clearer.

I am open to feedback if others also believe that it is poorly worded.

**Comment by raineorshine** [comment]
Closing due to age
