### ISSUE TITLE
Feature request: detect when dependencies should not be updated because other packages are peer dependent with the old version

### ISSUE THREAD

**Issue by coltonw** [tjunnone/npm-check-updates#376]
Whenever I use ncu to check and update my dependencies, I feel like most of the effort is spent manually picking through a bunch of package.json files to see if the peer dependencies match up properly across all the updates.

Inevitably some library updated to a new major version and all the plugins haven't caught up yet, so I have to manually update everything and manually figure out what the latest updates are that ARE compatible with each other.

Obviously, this is not a tiny body of work, but it seems like you have all the information to be able to KNOW when a dependency should not be updated or know the most up to date version you can safely update to.

**Comment by raineorshine** [comment]
Great suggestion! I will keep this open in case anyone has the time and motivation to tackle this.

**Comment by coltonw** [comment]
😢

**Comment by raineorshine** [comment]
This has been tagged with `revive-me` for those who want to contribute to `ncu`. Unfortunately there aren't a lot of contributors to `ncu` at this point in time.

**Comment by korelstar** [comment]
I'm very interested in this feature. Maybe [check-peer-dependencies](https://github.com/christopherthielen/check-peer-dependencies) could be used for gathering the list of peer dependencies?

**Comment by korelstar** [comment]
I did a quick implementation for this: please have a look at #869 :-)
