### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/npm-ckeck-updates

### ISSUE THREAD

**Issue by avandrevitor** [tjunnone/npm-check-updates#377]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 4.4.7
* npm version: 3.10.5
* npm-check-updates version: 2.12.0
---------------------------

Hi , i tried run : 
````
npm install -g npm-ckeck-updates
`````

but ... 

![image](https://user-images.githubusercontent.com/1133038/27877227-37c1086a-6190-11e7-917f-6c1de0d2f34e.png)

I think because of this :

![image](https://user-images.githubusercontent.com/1133038/27877397-d098ec56-6190-11e7-8be3-b3b674960459.png)

can you help me ?

**Comment by raineorshine** [comment]
Hi! It looks like there might be something wrong with your internet connection. The url works fine for me. 

I am going to close this ticket as it is definitely not ncu related!

**Comment by sgnl** [comment]
![image](https://user-images.githubusercontent.com/3915598/29381958-cb11c694-8266-11e7-988c-a799a3b9c50d.png)

`ckeck` 🤔
