### ISSUE TITLE
The promise returned by `run()` resolves too early

### ISSUE THREAD

**Issue by DanielSWolf** [tjunnone/npm-check-updates#378]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 7.10.0
* npm version: 4.2.0
* npm-check-updates version: 2.12.1

---------------------------

Consider the following Node script:

```js
const ncu = require('npm-check-updates');
const delay = require('delay');
const fs = require('fs');

function logPackageJson() {
  const content = fs.readFileSync('package.json', { encoding: 'utf-8' });
  console.log(`package.json: >>>${content}<<<`);
}

async function main() {
  await ncu.run({
    packageFile: 'package.json',
    upgrade: true,
  });
  logPackageJson();

  // This shouldn't be necessary:
  await delay(200);
  logPackageJson();
}

main();
```

I'd assume that right after executing the line `await ncu.run(...)`, the file `package.json` has been transformed. So in the following line, `logPackageJson()` should log the new content.

Instead, reading `package.json` right after awaiting `ncu.run()` results in *an empty string*. The output is this: `package.json: >>><<<`.

As a workaround, I'm waiting 200ms, then read and print `package.json` again. This time, the output is as expected.

**Comment by DanielSWolf** [comment]
If I add the following option: `loglevel: 'info'`, the error is even more obvious. In this case, the output looks like this:

```
⸨░░░░░░░░░░░░░░░░░░⸩ ⠸ :
 @mobilex/externals  ^1.2.0  →  ^2.0.0

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using undefined update. If you want to update the dependency in your package file anyway, run ncu -a.

 @mobilex/test  ^1.3.0  →  ^1.3.2

package.json: >>><<<
Upgraded /Users/wolf/dev/cross-mip/path/package.json

package.json: >>>{░⸩ ⠏ :
  "name": "@mobilex/path",
  "version": "1.0.2",
...
```

Notice how the line `Upgraded /Users/wolf/dev/cross-mip/path/package.json` appears *after* the first attempt to read the file.

Note also how NCU keeps logging its progress animation (those ░ characters) even after that.

**Comment by raineorshine** [comment]
Good catch! Is this something you'd be interested in writing a PR for?

**Comment by DanielSWolf** [comment]
I'm afraid I don't have the time. I only needed this package briefly for a one-time code migration.

**Comment by raineorshine** [comment]
I understand. Thank you for taking the time to report! I will add this to the list. ^_^
