### ISSUE TITLE
Identify not-installed packages too

### ISSUE THREAD

**Issue by rentalhost** [tjunnone/npm-check-updates#383]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.4.0
* npm version: 5.3.0
* npm-check-updates version: 2.12.1

---------------------------

`ncu` works fine to not-updated packages, but I think that it should includes not-installed packages too. Something like that:

```
 phonegap  6.5.2  →  7.0.0
 webpack   3.5.2  →  3.5.5
 axios     none   →  0.16.2
```

And it should consider the newest version, instead of `packages.json` version.

**Comment by raineorshine** [comment]
Thanks for your suggestion! In the past interacting with
installed/uninstalled packages has caused a lot of confusion for users so
I've decided to keep npm-check-updates solely a tool that interacts with
the package.json file.

**Comment by raineorshine** [comment]
In the next version it will ignore installed packages which should give more consistent behavior overall!
