### ISSUE TITLE
feature request: return nonzero exitcode when outdated dependencies are found

### ISSUE THREAD

**Issue by HowWeRollingham** [tjunnone/npm-check-updates#386]
i.e. the same behaviour exhibited by `npm outdated`

- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 
* npm version: 
* npm-check-updates version: 

---------------------------

**Comment by raineorshine** [comment]
Try `ncu --error-level 2`!

```
-e, --error-level        set the error-level. 1: exits with error code 0 if no
                         errors occur. 2: exits with error code 0 if no
                         packages need updating (useful for continuous
                         integration)
```
https://github.com/tjunnone/npm-check-updates#advanced-options

**Comment by HowWeRollingham** [comment]
I missed that!  Thank you, just what I was after.
