### ISSUE TITLE
Update multiple package.json files at once

### ISSUE THREAD

**Issue by mriehema** [tjunnone/npm-check-updates#387]
*Feature Request*

We have a project workspace which consist of multiple modules. I love "ncu" and it would be awesome, if we could add a feature like `-R` or `--recursive` to scan all subfolders for package.json files.

For example, this is our workspace:

```
project/package.json
  lib/
    tool-a/package.json
    tool-b/package.json
  themes/
    theme-a/package.json
    theme-b/package.json
```

Right now, I check every folder manually, but an _update all at once_ feature would be awesome. What do you think?

**Comment by raineorshine** [comment]
What about a shell script that cd's into each folder and runs `ncu`? I understand that you may want a more automated solution, but that's the quickest thing I can think of! `ncu` can also be used as a node module.

**Comment by mriehema** [comment]
Hi @raineorshine, I know, a shell script is the quickest solution, which I will use. But I thought, this idea could be a nice enhancement, which I should share with you at least.

**Comment by raineorshine** [comment]
Yes! Good thinking! Thanks!

**Comment by tkrotoff** [comment]
I do this to upgrade all package.json inside a directory:
`find . -type f -name 'package.json' -not -path './.git/*' -not -path '*/node_modules/*' -execdir ncu --upgrade \;`

**Comment by js2me** [comment]
What happened with this issue ?   
It is still actual ?

**Comment by raineorshine** [comment]
@js2me It is recommended to use a shell script such as suggested by @tkrotoff. npm-check-updates will not handle this natively.

**Comment by justnewbee** [comment]
although the shell script way works, it has some defects like time consuming (it might check one same package over and over again) and os compatibility.. i would very much expect it to be a native feature of ncu

it is very helpful when we use lerna to manage our sub-packages

so please make it happen :)

**Comment by kachkaev** [comment]
This is now resolved, thanks to #785 🎉

**Comment by metawrap-dev** [comment]
I have the opposite problem of this. I'm trying to update just a **single** project in a mono-repo and by default, ncu wants to upgrade the project in the **parent** directory too.

Is there a way to only upgrade one child project at a time in a mono-repo?

**Comment by raineorshine** [comment]
@metawrap-dev Please create a new issue and I'll respond there. Thanks!
