### ISSUE TITLE
How to install package with version limit ?

### ISSUE THREAD

**Issue by eromoe** [tjunnone/npm-check-updates#388]
I mistake update webpack to 3.X. I want to install the latest 2.0

I have seen 

> 
> Direct dependencies will be increased to the latest stable version:
> 2.0.1 → 2.2.0
> 1.2 → 1.3
> 0.1.0 → 1.0.1
> with --semverLevel major
> 0.1.0 → 0.2.1
> with --semverLevel minor
> 0.1.0 → 0.1.2
> Semantic versioning policies for levels are maintained while satisfying the latest version:
> ^1.2.0 → ^2.0.0
> 1.x → 2.x
> "Any version" is maintained:
> * → *
> "Greater than" is maintained:
> >0.2.0 → >0.3.0
> Closed ranges are replaced with a wildcard:
> 1.0.0 < 2.0.0 → ^3.0.0

So I can't use `--semverLevel` ,  I tried to use range like:
`ncu -f /webpack/ < 3.0.0`

But not work..

**Comment by raineorshine** [comment]
Hi @eromoe. It sounds like you want to upgrade webpack to an earlier version of latest (which is `3.5.5` at time of writing). Can you achieve this functionality by using semver, specifying the dependency as `^2.0.0`? Then you can simply exclude that package with ncu:

```
ncu -x webpack
```
