### ISSUE TITLE
What is the difference between `ncu -t` and `ncu -n`

### ISSUE THREAD

**Issue by 199911** [tjunnone/npm-check-updates#390]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v6.10.1
* npm version: 3.10.10
* npm-check-updates version: 2.12.1

---------------------------

I check these two parameter with ncu -h
```
-t, --greatest               find the highest versions available instead of the latest stable versions
-n, --newest                 find the newest versions available instead of the latest stable versions
```
What is the difference between them?
Are they the same?

**Comment by raineorshine** [comment]
Hi!

Greatest is the highest version number available numerically.

Newest is the version number that was last published. It is possible for
package authors to publish smaller version numbers later.
