### ISSUE TITLE
Changes powershell text color to yellow

### ISSUE THREAD

**Issue by PiterGoCompany** [tjunnone/npm-check-updates#391]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.5.0
* npm version: 5.3.0
* npm-check-updates version: 2.12.1
---------------------------
After running command ncu default text color in PowerShell is changed to yellow. Calling [System.Console]::ResetColor() restores user defined colors.  Problem occurs only when all packages are up-to-date. When there's something to update everything works as it should.

**Comment by raineorshine** [comment]
Is there someone with a Windows machine who is willing to troubleshoot this?

**Comment by PiterGoCompany** [comment]
Problem occurs only when all packages are up-to-date. When there's something to update everything works as it should.

**Comment by raineorshine** [comment]
Anybody able to reproduce this still?
