### ISSUE TITLE
Update all version with removing ranges

### ISSUE THREAD

**Issue by argnist** [tjunnone/npm-check-updates#392]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 7.4.0
* npm version: 4.0.5
* npm-check-updates version: 2.12.1

---------------------------
How to ncu -u --removeRange for all packages, not only that has update? 
"-a" returns "All dependencies match the latest package versions :)"

**Comment by raineorshine** [comment]
Thanks for the question! ncu only affects upgraded dependencies. It is not currently designed for formatting/changing/modifying all dependencies, so you would have to remove them manually if they are already up-to-date.
