### ISSUE TITLE
Consider ignoring or committing package-lock.json

### ISSUE THREAD

**Issue by nickmccurdy** [tjunnone/npm-check-updates#394]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

---------------------------

Yarn generates a `yarn.lock` file, while npm 5 generates a `package-lock.json` file. This project currently uses Yarn's lock file, without ignoring or committing npm's lockfile. To reduce confusion we should either ignore it in `.gitignore`, commit it alongside `yarn.lock` (with a note that contributors should maintain both lockfiles), or entirely replace Yarn with npm 5.

**Comment by raineorshine** [comment]
Yarn removed in c3d7611f858cdb9a49d3cb60a30e68d66b8fe917
