### ISSUE TITLE
Can I use this to locate deprecated installed versions?

### ISSUE THREAD

**Issue by i0natan** [tjunnone/npm-check-updates#397]
- [X ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.4
* npm version: 5.2
* npm-check-updates version: All

---------------------------

I have a very general question - can this package be used to find packages that are tagged as deprecated and installed locally? in other words, I'd like to know if a version that I use was marked by its author as deprecated. Case not, this might be a nice to have feature as it implies a big risk

**Comment by raineorshine** [comment]
Hi! ncu does not support this functionality currently, but that's a good idea for an enhancement.

**Comment by nickmccurdy** [comment]
I believe `npm install` warns about deprecated dependencies by default. I tend to run `npm install` after any `ncu -u` commands to update my lockfile anyway, I would recommend trying the same for now.
