### ISSUE TITLE
Doesn't show packages that has newer versions. All the time `Hmmmmm... this is taking a long time.`

### ISSUE THREAD

**Issue by wzup** [tjunnone/npm-check-updates#398]
React 16 is out already. My app has `"react": "^15.5.4"`
I'm using the plugin to see which packages need update. And the plugin doesn't show `react` and many others.
The plugin doesn't updates `react` even when it is specified explicitly

```
$ ncu -f react
Hmmmmm... this is taking a long time. Your console is telling me to wait for input
on stdin, but maybe that is not what you want.
Try specifying a package file explicitly with --packageFile package.json.
See https://github.com/tjunnone/npm-check-updates/issues/136#issuecomment-155721102
```

The plugin doesn't work if called without `--packageFile package.json`. Throws
```
Hmmmmm... this is taking a long time. Your console is telling me to wait for input
on stdin, but maybe that is not what you want.
Try specifying a package file explicitly with --packageFile package.json.
See https://github.com/tjunnone/npm-check-updates/issues/136#issuecomment-155721102
```

```
OS: Windows 10 x64

$ npm -v
4.0.2

$ node -v
v6.3.1
```

**Comment by raineorshine** [comment]
This is a known that will be corrected in v3. See https://github.com/tjunnone/npm-check-updates/issues/389. 

The issue with hanging is a known issue (2nd one down): https://github.com/tjunnone/npm-check-updates#known-issues

Thanks!
