### ISSUE TITLE
When updating this specific package.json it renames the package names

### ISSUE THREAD

**Issue by lipis** [tjunnone/npm-check-updates#40]
With the following `package.json` file
```json
{
  "dependencies": {
    "coffee-script": "~0.0",
    "less": "~0.0",
    "uglify-js": "~0.0"
  },
  "devDependencies": {
    "bower": "~0.0",
    "del": "~0.0",
    "gulp": "~0.0",
    "gulp-bower": "~0.0",
    "gulp-livereload": "~0.0",
    "gulp-load-plugins": "~0.0",
    "main-bower-files": "~0.0",
    "minimist": "~0.0"
  }
}
```

When I'm running the following:

```bash
$ npm-check-updates -u

"coffee-script" can be updated from ~0.0 to ~1.8 (Installed: 1.8.0, Latest: 1.8.0)
"less" can be updated from ~0.0 to ~2.2 (Installed: 2.2.0, Latest: 2.2.0)
"uglify-js" can be updated from ~0.0 to ~2.4 (Installed: 2.4.16, Latest: 2.4.16)
"bower" can be updated from ~0.0 to ~1.3 (Installed: 1.3.12, Latest: 1.3.12)
"del" can be updated from ~0.0 to ~1.1 (Installed: 1.1.1, Latest: 1.1.1)
"gulp" can be updated from ~0.0 to ~3.8 (Installed: 3.8.10, Latest: 3.8.10)
"gulp-livereload" can be updated from ~0.0 to ~3.4 (Installed: none, Latest: 3.4.0)
"gulp-load-plugins" can be updated from ~0.0 to ~0.8 (Installed: none, Latest: 0.8.0)
"main-bower-files" can be updated from ~0.0 to ~2.5 (Installed: none, Latest: 2.5.0)
"minimist" can be updated from ~0.0 to ~1.1 (Installed: 1.1.0, Latest: 1.1.0)
```

The result of package.json looks like this:

```json
{
  "dependencies": {
    "coffee-script": "~1.8",
    "less": "~2.2",
    "uglify-js": "~2.4"
  },
  "devDependencies": {
    "bower": "~1.3",
    "del": "~1.1",
    "gulp": "~3.8",
    "bower": "~1.3",
    "gulp": "~3.8",
    "gulp": "~3.8",
    "bower": "~1.3",
    "minimist": "~1.1"
  }
}
```

**Comment by metaraine** [comment]
Thanks! This is a high priority bug.

Pull Requests also welcome.

**Comment by lipis** [comment]
@metaraine I couldn't agree more.. but no time to dig into for a PR... soz :) for now did it manually :(

**Comment by metaraine** [comment]
I understand. I'm on it :)

**Comment by jwarkentin** [comment]
I just saw this and thought it looked like a simple thing to track down and fix. I submitted a pull request that fixes it. The problem was that the regex was too broad. It's easy to see how the expression `".*gulp.*:.*"~0\.0"` would match all of the gulp dependencies (since the 'g' modifier is given). There are several other options as well if you don't like my change. You could also just add a `$` to the end of the regex, which will work as long there is only ever one dependency per line.

**Comment by jwarkentin** [comment]
Or, you could just change the modifier to `m` instead of `g`. That would also work.

**Comment by jwarkentin** [comment]
Sorry to spam, but as I got thinking about it, the modifier change would still be a problem. Imagine of those dependencies were in a different order with something like `gulp-livereload` before `gulp`. When it got to `gulp` it would instead match `gulp-livereload`. The modifier alone won't fix the problem. The wildcard in the regex is simply too broad.

**Comment by lipis** [comment]
I wouldn't worry about the spam as long as the issue will be fixed the right way.. thanks for the analysis :)

**Comment by lipis** [comment]
Nice! Will make a new release for this one?

**Comment by metaraine** [comment]
`npm view npm-check-updates version`
1.5.1
