### ISSUE TITLE
ncu thinks ‘most recently published version’ is the same thing as ‘highest version’

### ISSUE THREAD

**Issue by callumlocke** [tjunnone/npm-check-updates#401]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.7.0
* npm version: 5.4.2
* npm-check-updates version: 2.13.0

---------------------------

I ran `ncu -a` and expected it to update one of my dependencies from `2.1.4` to `2.1.5`.

But it did nothing. It turns out ncu thinks the latest version of the package in question is `1.0.3`.

It's true in a way, the `1.0.3` version was pushed to npm _more recently_, but that doesn't mean it's the latest version. It just means the package authors decided to go back and release a security patch to help out users who are still on v1.

It would be great if ncu could look for the highest version instead of the most recently published version.

**Comment by raineorshine** [comment]
Yes, good point!

ncu actually just checks the `latest` tag. It is the responsibility of the package author to only publish the version they intend to be the latest version to the `latest` tag. It is usually the result of a package author mistake when this is broken.

To get around this with ncu, you can specify `-t` or `--greatest` from the [Advanced Options](https://github.com/tjunnone/npm-check-updates#advanced-options).
