### ISSUE TITLE
ncu -u does not work

### ISSUE THREAD

**Issue by Devinora** [tjunnone/npm-check-updates#405]
PS C:\Users\khdev\Desktop\html-ready> ncu -u
Using C:\Users\khdev\Desktop\html-ready\package.json
[..................] - :
The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, run ncu -a.

 gulp.spritesmith  ^6.5.1  →  ^6.7.0

PS C:\Users\khdev\Desktop\html-ready>

**Comment by raineorshine** [comment]
Can you explain what exactly is not working?

The message shows that `gulp.spritesmith` already satisfies its version range and does not need to be upgraded.
