### ISSUE TITLE
ncu depends installs 3 advisories

### ISSUE THREAD

**Issue by gemal** [tjunnone/npm-check-updates#407]
after installing ncu and running `nsp check` I get 3 advisories:
```
"https://nodesecurity.io/advisories/525",
"https://nodesecurity.io/advisories/338",
"https://nodesecurity.io/advisories/534"
```

get nsp from https://github.com/nodesecurity/nsp

**Comment by raineorshine** [comment]
Thanks! Will do

**Comment by gemal** [comment]
Perhaps some dependency needs to be updated in ncu?

**Comment by raineorshine** [comment]
I'm not familiar with `nsp`. I can look into it more when I have time, or someone could run the necessary tools and submit a PR if any dependencies need to be updated. Thanks!

**Comment by nickmccurdy** [comment]
If it helps, I believe Snyk uses nsp internally for Node projects, so you should already be getting these advisories by using Snyk.

**Comment by revelt** [comment]
Snyk link:

https://snyk.io/test/github/tjunnone/npm-check-updates/?severity=high&severity=medium&severity=low

**Comment by raineorshine** [comment]
@revelt 
> Is there are reason why we are not bumping npm dependency to v5.x?

`ncu` needs to be modified to use the system `npm` instead of installing its own. Currently there are no active developer of `ncu`, although this is on my list if I ever have time again to work on it.

**Comment by raineorshine** [comment]
Closing as the local npm has been removed in the soon-to-be-released [v3](https://github.com/tjunnone/npm-check-updates/issues/471) and snyk is showing 0 dependencies.
