### ISSUE TITLE
Add .ncurc config?

### ISSUE THREAD

**Issue by cavinsmith** [tjunnone/npm-check-updates#411]
I'm using `sequelize` with `pg@6` because `pg@7` is not currently supported.

When I'm running `ncu -a` / `ncu -g` `pg` gets updated to v7 even if strict version was set in `package.json`, the only way to exclude it is running `ncu -x pg`.

Is it a good idea to add ability to read parameters from local config e.g. `.ncurc` or `.ncurc.json` or `ncuconfig.json` etc.

I guess pre-defined ignoring for some packages, setting up registries and other parameters will be great?

**Comment by raineorshine** [comment]
Hi! Thanks for the suggestion. Yes, this would be a fairly easy feature to support. I would suggest keeping the config file the exact syntax as the cli options to avoid maintenance overhead. I am not available myself to work on this at the moment but I will mark it as an enhancement and invite anyone to submit a PR.

**Comment by cavinsmith** [comment]
https://github.com/tjunnone/npm-check-updates/pull/412

* Added popular package (https://www.npmjs.com/package/rc-config-loader) for reading rc config `.ncurc` for all formats.

* Checked everything but hasn't written tests for it, because it's a little tricky thing: need to add `rcFilePath` to argument list, then parse it with commander, check if argument exists, then read rc file, and invoke commander again to parse new array of parameters. All this to have ability to load custom rc files from fixtures.

**Comment by cavinsmith** [comment]
Oh, yeah. To test it on itself just create filer `.ncurc.json` in root project dir with following contents:

```
{
  "filter": "npm, npmi",
  "reject": "npmi"
}
```

This should result in 

```
$ ./bin/ncu 
 npm  ^3.10.6  →  ^5.6.0 
```

```
$ ./bin/ncu -x notnpmi
 npm   ^3.10.6  →  ^5.6.0 
 npmi   ^2.0.1  →  ^4.0.0 
```

**Comment by raineorshine** [comment]
I pointed to a test in the PR comments that generates temp files that should help with creating a simple unit test just so we have something. Thanks!

**Comment by cavinsmith** [comment]
@raineorshine ok, will do on weekend!

**Comment by cavinsmith** [comment]
@raineorshine

Added configFilePath and configFileName to allow custom config paths and files and to provide tests

Added tests for: loading by path, loading by name, overriding config file options with arguments

Added options info and configuration description to README.MD

**Comment by cavinsmith** [comment]
@raineorshine Hey! Is everything is ok now? Really want to upgrade my projects with new NCU with configs)

**Comment by raineorshine** [comment]
Thanks so much! Let me take a look.
