### ISSUE TITLE
Filter regex not working

### ISSUE THREAD

**Issue by jpduckwo** [tjunnone/npm-check-updates#417]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v9.1.0
* npm version: 5.6.0
* npm-check-updates version: 2.14.0

---------------------------
Applying regex to filter certain packages doesn't work
e.g.
```
$ ncu
Using /.../package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠼ :
 @ngrx/effects       ^4.1.1  →  ^5.0.0
 @ngrx/entity        ^4.1.1  →  ^5.0.0
 @ngrx/router-store  ^4.1.1  →  ^5.0.0
 @ngrx/store         ^4.1.1  →  ^5.0.0
 rxjs                 5.5.0  →   5.5.6
 zone.js             0.8.18  →  0.8.20
 @types/node         ^8.5.9  →  ^9.3.0
 precss              ^2.0.0  →  ^3.1.0
 typescript          ~2.5.3  →  ~2.6.2
 webpack-dashboard    0.4.0  →   1.1.1
```
If I try to filter them to just take the @ngrx packages using any variation of regex filter it doesn't return the packages.
e.g. I tried these as an example
```
ncu "@ngrx*"
ncu "@ngrx.*"
ncu -f "@ngrx*"
ncu -f "@ngrx.*"
ncu -f "^@ngrx.*"
ncu -f "^@ngrx.*$"
```
Nothing seems to work.

**Comment by raineorshine** [comment]
Hi! ncu's regex uses the Javascript syntax of `/.../`, otherwise it is treated as an exact string match.

What you want is:
`ncu /ngrx/`

**Comment by thw0rted** [comment]
This information should be in the `--help` text.  @raineorshine  Should I file a new issue for the documentation update or would it be preferable to reopen this one?  (It might also be helpful to document how literal wildcard characters can interact with various shells...)

**Comment by raineorshine** [comment]
Would changing the existing message from this:

> include only package names matching the given string, comma-delimited list, or regex

to this:

> include only package names matching the given string, comma-delimited list, or /regex/

be sufficient? I don't want to add too much extra extraneous information to the command line `--help`. Let's at least add it to the `README` though.

Shell advice is out-of-scope of the `--help`. People are advised to consult the `faq` here or learning specifics of their shell elsewhere.

**Comment by thw0rted** [comment]
I think a single-line example in the `--help` would be justified, but just adding slashes would at least be something.

I just noticed "comma-delimited list": I've been writing `ncu -u foo bar baz` and it updates those three packages, without using commas.  It seems that `ncu -u foo bar /baz.*/` basically ignores the last argument, though, so I guess you can't mix modes.

Agreed about the shell advice (though maybe an example in the README?).

**Comment by raineorshine** [comment]
Actually, I'm seeing now that the README has a hint about the bash issue in the main [Usage](https://github.com/tjunnone/npm-check-updates#usage) section. Did you see that?

In the mean time, I created #569 to improve the clarity in the `--help`. What do you think?
