### ISSUE TITLE
ncu not work when we have npm link

### ISSUE THREAD

**Issue by bluelovers** [tjunnone/npm-check-updates#422]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 9.5.0
* npm version:  5.6.0
* npm-check-updates version: 2.14.0

---------------------------

when our npm_module has a module is by npm link

ncu will skip check

then we can't update package.json when npm server has new version

**Comment by raineorshine** [comment]
`ncu` does not yet handle `npm link`ed dependencies. It is a needed feature, I agree!

**Comment by raineorshine** [comment]
Closing as duplicate issue.
