### ISSUE TITLE
Is it possible to upgrade the "npm" in the package.json

### ISSUE THREAD

**Issue by zrx8269** [tjunnone/npm-check-updates#423]
* node version: v6.10.2
* npm version: v3.10.10
* npm-check-updates version: 2.14.0

---------------------------
After install the "npm-check-updates" in my project, it will also install its dependencies, but the version of "qs" module under "npm" is too low for my security check, is it possible for you to update the "npm" version in package.json?
Thanks very much.

**Comment by raineorshine** [comment]
Yes, this has been an issue for many people recently (see other issues).

I made an alpha version with upgraded npm. Let me know if this helps: `npm
uninstall -g npm-check-updates && npm install -g
npm-check-updates@v3.0.0-alpha1`

**Comment by zrx8269** [comment]
Thanks for your reply, but the same error occurs under the "npmi" package.

**Comment by raineorshine** [comment]
Ah, good catch. Try now:

```
npm
uninstall -g npm-check-updates && npm install -g
npm-check-updates@v3-alpha
```

**Comment by billyjanitsch** [comment]
Hi @raineorshine! Thanks for your work maintaining this library! 😊

Just to let you know: [prerelease versions](https://docs.npmjs.com/misc/semver#prerelease-tags) should be formatted like `3.0.0-alpha.1`. The `.` between `alpha` and `1` is necessary for npm to handle semver/sorting correctly.

You might also consider tagging it as `next` rather than `v3-alpha` (not required, just an npm convention for prereleases). You can run:
```
$ npm dist-tag add npm-check-updates@3.0.0-alpha1 next
$ npm dist-tag rm npm-check-updates v3-alpha
```

In any case, I'm excited to play with this version!

**Comment by raineorshine** [comment]
Hi @billyjanitsch! Thank you. I must be getting rusty on my semver!

In hindsight I should have done the `next` tag. Glad it's fixable!

**Comment by raineorshine** [comment]
@billyjanitsch I'm getting a `401` on the delete. I've logged out and back in again so I seem to be logged in correctly. Any ideas?

**Comment by billyjanitsch** [comment]
That's odd. The man page says `npm dist-tag rm <pkg> <tag>`. Maybe v3-alpha needs to be quoted because of the dash?

Anyway, thanks for fixing up the versioning! :)

**Comment by JoshuaKGoldberg** [comment]
This is important because npm@3 requires gauge@2.6, which seems to be causing https://github.com/npm/npmlog/issues/48 for me.

What a fun chain of dependencies!

**Comment by raineorshine** [comment]
Fixed in `v3` branch via https://github.com/tjunnone/npm-check-updates/commit/c0bd8b72fa353d6471f8ccb400d6e4d79b1568d5.
