### ISSUE TITLE
Check `resolutions`

### ISSUE THREAD

**Issue by errorx666** [tjunnone/npm-check-updates#427]
The [`resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) field of package.json contains version specifications for modules-of-modules.  I would like it if npm-check-updates could check these dependencies as well.
The two main use-cases for the field are to either pin a dependency to a specific version (e.g., for compatibility) or to keep the versions in sync across modules (e.g., for smaller webpack bundles).
I'm interested in use-case 2, and for me that means I have to manually update the `resolutions` field to match `dependencies` after every `ncu`.  It would be nice if `ncu` could do it for me.
To support use-case 1, it shouldn't check this field by default; it needs to be opt-in, so a flag and/or a configuration option would be needed.

**Comment by raineorshine** [comment]
Great suggestion!

**Comment by bluelovers** [comment]
need this

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.

**Comment by khanzzirfan** [comment]
Need this feature for sure. Its real usecase.

**Comment by bluelovers** [comment]
> Need this feature for sure. Its real usecase.

try `yarn-tool ncu -R`

**Comment by Torathion** [comment]
Bump. I kinda need this for my tools using `pnpm`.
