### ISSUE TITLE
Use commands like "ncu ./[folderName]"

### ISSUE THREAD

**Issue by marco-carvalho** [tjunnone/npm-check-updates#428]
I have a folder with like 100 folders. Each one of those 100 folders are projects of mine, and they have a package.json in their root. I would like to run "ncu ./[folderName]" and NCU would search the package.json in the root and run it.

I checked if this was possible, but I couldn't find some way to do it.
Is this planned for the future or this is possible right now and I just don't know how?

**Comment by raineorshine** [comment]
It is recommended to use the power of your shell for this purpose:

```
for d in ./*/ ; do (cd "$d" && ncu); done
```
