### ISSUE TITLE
`snyk` is pulled in as a dependency but is apparently unused in runtime

### ISSUE THREAD

**Issue by ChALkeR** [tjunnone/npm-check-updates#429]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 9.5.0
* npm version: 5.6.0
* npm-check-updates version: git master

---------------------------

Commit 5efc9152b3c64a20e9992e819b6886b371b7e5be added `snyk` to `dependencies`, so it gets pulled in (along with all of its deps) on any installs. Adding it to `devDependencies` should have been sufficient, imo.

**Comment by raineorshine** [comment]
Makes sense, thanks!
