### ISSUE TITLE
Detect version in Git dependencies using #semver:^X.Y.Z format

### ISSUE THREAD

**Issue by ibc** [tjunnone/npm-check-updates#430]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.9.4
* npm version: 5.8.0
* npm-check-updates version: 2.14.1

---------------------------

It'd be great if `ncu` also works with Git dependencies in `package.json` that use the SEMVER format to specify the version (Git tag in fact), as documented [here](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies):

```
<protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]
```

Example:

```
"myPrivateLib": "github:myorg/myPrivateLib#semver:^1.3.0"
```

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
