### ISSUE TITLE
Support for third party/scoped registries

### ISSUE THREAD

**Issue by andyrichardson** [tjunnone/npm-check-updates#431]
- [ x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 
* npm version: 
* npm-check-updates version: 

---------------------------

First off, thanks for the great package!

## Issue
Running `ncu` while packages from third party registries are installed cause the following error

    Unhandled rejection Error: unregistered users are not allowed to access package @myprefix/mypackage: @myprefix/mypackage

## Registry setup
At work, we have set up a private registry and configured npm to fetch all packages scoped with `@myprefix` from said registry. 

This private registry requires authentication and, once initially signed in, packages are easily fetched without any authentication request. E.g. `npm i @myprefix/mypackage` would execute just as if it was fetching from the npmjs registry.

## Proposed solution
Read ~/.npmrc to fetch authentication credentials and alternate registries.

## Resources
[Scoped packages](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry)

**Comment by raineorshine** [comment]
Great suggestion, thanks! This project is in need of collaborators.

**Comment by andyrichardson** [comment]
This issue was also occuring when using the `npm outdated` command.

The problem is no longer present for me and I assume it is down to one of two reasons.

- My 3rd party repo now has a domain name (as opposed to being listed as an IP)
- My 3rd party repo is now using https

**Solution**
Ensure that any third party repositories use https and/or have a registered domain name.
