### ISSUE TITLE
Feature request: Update to specific date

### ISSUE THREAD

**Issue by BBaysinger** [tjunnone/npm-check-updates#435]
- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

---------------------------

I would think it would be very useful to have a feature that allows passing in a date, to have NCU update all dependencies to the latest versions as of the date specified. Of course I'm not sure if this is possible, as I don't know if the NPM repositories include such information.

My use case is relevant for today where I have an Angular 5 project, but have found Angular 6 was released within the last few days. Angular 6 breaks my project, and I'm not ready to migrate. I would like NCU to behave as if it was some date last week, so I can update everything to the latest versions from then, and try to get the last versions before this current major version. This is particularly important for me now, because I have two projects that I need to merge. I want to update them both to the same versions, and test before I merge, but updating them to todays current version is not an option.

I didn't see a similar feature in the documentation, so please let me know if this is already a feature.

Thanks for developing this tool. We use it a lot here, and don't know what we would do without it.

**Comment by raineorshine** [comment]
Thanks for the suggestion! I am going to mark this as an `enhancement` and invite the community to contribute. I have been unable to contribute directly to ncu in a while. Glad you are enjoying the tool!

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
