### ISSUE TITLE
Skip upgrading a dependency if set to a specific version?

### ISSUE THREAD

**Issue by oleersoy** [tjunnone/npm-check-updates#436]
Based on what I'm seeing, npm check updates everything it can find to update.  I was hoping it would only update things with a ^ character in the version?   

For example this updates:
```
multer            ^0.1.8  →   ^1.0.1
```
But this does not
```
multer            0.1.8  →   0.1.8 
```
Thoughts?

The reason I'm requesting this is I have dependencies that are updating, like `postcss-custom-properties` but the build they are updating to is broken so ...

**Comment by raineorshine** [comment]
Hi, thanks for posting. I could definitely see this being useful. Currently `ncu` only filters against the package name. It would be a good addition to offer a command line option to filter against the specified version as well.

In the mean time, you will have to explicitly exclude packages, e.g.

```
ncu -x postcss-custom-properties
```

**Comment by Zyphrax** [comment]
I would expect this to be default behavior.

When I pin a version with `0.1.8` instead of `^0.1.8` I'm choosing not to update that package to the latest version, I just want to keep it at `0.1.8`.

Could this perhaps be changed?
Basically just ignore all packages that have fixed versions.

**Comment by prantlf** [comment]
I upgrade all modules in `package.json` from time to time. I use pinned dependencies. Running `ncu` is a convenient way of checking and upgrading npm modules only when wanted.

If `ncu` should ignore npm modules with exact version, I'd prefer introducing a command line option for it, to be able to still use the original functionality. Running `npm outdated` checks npm modules with pinned version too.

**Comment by prantlf** [comment]
`.ncurc` can be used to list packages, which should not be touched by `ncu`, having pinned version or not.

**Comment by Zyphrax** [comment]
@prantlf I don't agree. When you specify an exact version number it is the developer's intent to stay at the specific version. There are many ways to specify a flexible version number:
https://docs.npmjs.com/misc/semver#ranges

NCU should honor these versioning rules. Upgrading pinned versions is risky, but you can always introduce something like `--upgradePinned`.

**Comment by raineorshine** [comment]
To clarify, the main purpose of ncu is to **break versioning rules**. `npm` is good at performing non-breaking upgrades. It is not so good at performing controlled breaking version upgrades, hence `ncu`. (A feature I'd love to add is the ability to run unit tests for each upgrade to determine if it actually breaks anything.) 

That said, people have a variety of needs around dependency management, and there should be a flag in ncu to optionally exclude fixed version numbers.

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.

**Comment by raineorshine** [comment]
`--filterVersion` and `--rejectVersion` added in `v10.2.0`, allowing filtering based on the version string.

e.g. You can exclude exact versions by filtering only ranges:

```sh
ncu --filterVersion "/^[~^<>]| - |\.x$/"
```
