### ISSUE TITLE
Separate -u and -a options

### ISSUE THREAD

**Issue by edmorley** [tjunnone/npm-check-updates#438]
* node version: 10.1.0
* npm version: N/A (yarn 1.6.0)
* npm-check-updates version: 2.14.2

---------------------------

Hi!

After reading the docs, I used `ncu --upgradeAll` to bump in-range deps, however was suprised to find that the actual files in the repository were modified without any kind of prompt, when I hadn't also passed the `--upgrade` option.

According to `ncu --help`:

>     -u, --upgrade            overwrite package file
>     -a, --upgradeAll         include even those dependencies whose latest version satisfies the declared semver dependency

...which says nothing about `--upgradeAll` writing to the files.

However from reading the source it appears to be by design:
https://github.com/tjunnone/npm-check-updates/blob/621dbd50e53677c16033b446d5d1e22bc71e409a/lib/npm-check-updates.js#L318-L319

It would be good to:
* Update the README and `ncu --help` to say this is the expected behaviour
* Consider renaming `--upgrade` to `--no-prompt` or `--write` in the next major version, and keeping it entirely separate from whether using standard upgrade rules or the "upgradeAll" approach.

Many thanks!

**Comment by raineorshine** [comment]
Both points well-taken! Will plan on this in v3.

**Comment by pjasiun** [comment]
Also, there is no option to prompt all. `ncu -a` upgrades all, but prompt only part of the dependencies. I expected `ncu -a` will prompt all and `ncu -a -u` will update all.

**Comment by raineorshine** [comment]
I am in favor of a separate `--write` option in v3.

**Comment by raineorshine** [comment]
For reference from #209:

> If I run ncu -u PKGNAME, it will update my package and print in raw text.
> If I run ncu -u PKGNAME --jsonUpgraded, it does not update the package, and prints in JSON the info about what it should have updated to. It seems like those two things should work together.

**Comment by cmloegcmluin** [comment]
Currently it seems that the part of the work has been done so that `-a` does not overwrite package.json by itself anymore. 

However, with `-a -u`, the dependencies whose latest version satisfies the declared semver dependency are printed out, but not written to the package.json.

**Comment by raineorshine** [comment]
Contrary to my previous comment, a decision had been made a while ago to change the default behavior. Many issues were created by people's expectation that ncu would always suggest the very latest versions.

In `v3`, `-u` and `-a` will be made to function independently, as previous described, but the `-a` dependency selection behavior will be the default behavior and the inverse (lack of `-a` in `v2`) will be enabled via the new `--minimum` option. Only with the `--minimum` option will ncu exclude versions that are already satisfied by the specified version range (the `v2` default behavior).

This change was implemented here:
https://github.com/tjunnone/npm-check-updates/commit/82acd575311651b79690c359996182b79a85db7a

Open for comments. Thanks!
