### ISSUE TITLE
package version inconsistency

### ISSUE THREAD

**Issue by neokio** [tjunnone/npm-check-updates#439]
[X] I have read the list of known issues before filing this issue.
[X] I have searched for similiar issues before filing this issue.

* node version: 10.1.0
* npm version: 6.0.1
* npm-check-updates version: 2.14.2

---------------------------

This morning, I opened a MAMP development server via terminal, ran `ncu` on two projects with nearly identical `package.json` local dependencies, and got very different results.

Both had the following dependencies and versions:

```
    "tablesorter": "^2.30.3",
    "gulp-rename": "^1.2.2",
```

In the first project's root directory, I ran `ncu`, and was shown this:

```
The following dependencies are satisfied by their declared version range,
but the installed versions are behind ...

    tablesorter  ^2.30.3  →  ^2.30.4
    gulp-rename   ^1.2.2  →   ^1.2.3
```

In the second project's root directory, I ran `ncu`, and was shown this:

```
All dependencies match the latest package versions :)
```

Why, when both projects have the `tablesorter ^2.30.3` dependency, would one project show the latest version, and another show no update?

**Comment by raineorshine** [comment]
It is noticing that you have the latest versions in the `node_modules` folder. This is counterintuitive behavior and will be removed in v3.

See https://github.com/tjunnone/npm-check-updates/issues/424#issuecomment-369207424

**Comment by neokio** [comment]
That's odd, but you're correct. Odd because I had only just done an `npm install` the day before, with those two updates appearing the following day. I must have updated them in my sleep :)

Looking forward to v3, thanks!
