### ISSUE TITLE
Better document .ncurc config options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [tjunnone/npm-check-updates#442]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

> ## Configuration Files
> Use a .ncurc.{json,yml,js} file to specify configuration information. You can specify file name and path using --configFileName and --configFilePath command line options.

Could there be a file excerpt or two put in the README.md to demonstrate the suggested usage?

**Comment by raineorshine** [comment]
How about adding this?

```js
{
  "upgrade": true, 
  "filter": "express"
}
```

**Comment by sanex3339** [comment]
Also, it will nice to update example with array variant:
```
{
  "reject": [
    "@types/estree",
    "ts-node"
  ]
}
```
