### ISSUE TITLE
Error writing the package.json file

### ISSUE THREAD

**Issue by johjacb** [tjunnone/npm-check-updates#45]
Thanks for this plugin - looks to be very helpful!

Unfortunately, I can't get it working. After a new install and running: npm-check-updates -u I see this error:

There was an error writing the package.json file: Error: EACCES, open 'package.json'

Likely user error, but look for some help. Thanks

**Comment by johjacb** [comment]
ha sorry - thought I had ran it w/ sudo, but apparently i didn't. Sorry for the issue!

**Comment by metaraine** [comment]
Glad you figured it out! Let us know if any other issues come up for you.
