### ISSUE TITLE
k updates

### ISSUE THREAD

**Issue by amariliscamargo** [tjunnone/npm-check-updates#450]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 
* npm version: 
* npm-check-updates version: 

---------------------------

**Comment by raineorshine** [comment]
Closing due to lack of information.
