### ISSUE TITLE
Package-lock Should that be updated as well?

### ISSUE THREAD

**Issue by chobo2** [tjunnone/npm-check-updates#451]
* node version:  8.11.3
* npm version: 5.6.0
* npm-check-updates version: 2.14.2

---------------------------

Hi I am using this plugin but I when I do an update with it, the package-lock does not get updated.

I did something like `ncu -u react-step-wizard ` and saw it was  updated in my package.json but then the whole plugin did not work properly after investigation I found like it still was on version 2.0(what I was on before) and not the latest version 4.0

I then looked at the package-lock and saw it still was pointing to 2.0 and not 4.0.

So wondering if that was the problem.

**Comment by fuhlig** [comment]
Using `ncu -u` updates only the version inside the `package.json`. In order to update the package's version(s) run `npm install` afterwards which should update the lock file as well.

**Comment by chobo2** [comment]
@fuhlig 

Ok I will try that.  maybe that should be included in the documentation.

Thanks

**Comment by fuhlig** [comment]
From the docs
_npm-check-updates allows you to upgrade your package.json dependencies_
Thats exactly what `ncu` does. But I agree, a hint in the documentation could avoid confusion.

cc @tjunnone

**Comment by raineorshine** [comment]
README updated. Thanks!
