### ISSUE TITLE
search/filter multiple packages/scopes 

### ISSUE THREAD

**Issue by webmutation** [tjunnone/npm-check-updates#452]
How to search for scoped packages?

ncu -f @ngrx, @angular does not seem to work. I remember that this was possible some time ago. But i forgot to write it down. It would be a good addition to the documentation.

ncu  /^@ngrx/, /^@angular/ also does not seem to work.
ncu ' /^@ngrx/',' /^@angular/' also does not work...

I am unsure how the -f works with comma seperated strings or regex ?

**Comment by raineorshine** [comment]
I tested it and it should work they way you did it. Here is a simple example with two packages that are out of date, one that is scoped:

```
raine[temp]$ ncu
Using /private/tmp/temp/package.json

 @ngrx/store  ^1.0.0  →  ^6.1.0
 chalk        ^1.1.3  →  ^2.4.1

raine[temp]$ ncu -f /^@ngrx/
Using /private/tmp/temp/package.json

 @ngrx/store  ^1.0.0  →  ^6.1.0

Run ncu with -u to upgrade package.json

raine[temp]$ ncu -f "/^@ngrx/"
Using /private/tmp/temp/package.json

 @ngrx/store  ^1.0.0  →  ^6.1.0

Run ncu with -u to upgrade package.json
```

Does `@ngrx/store` show up when you run `ncu` without options? i.e. Are there actually updates? Maybe there is a different issue that is being obscured.

**Comment by webmutation** [comment]
Hi @raineorshine the issue is multiple, one package works great. But i would like to update multiple at the same time using the comma seperated expression. This is what I was not able to achieve.

**Comment by raineorshine** [comment]
Ah, I see! Thank you for the clarification.

You would just use a single regex like so: `ncu -f "/^(@ngrx|@angular)/"`

**Comment by webmutation** [comment]
Of course... thank you! Maybe ad a note in the documentation, I have seen other with this question. In the end it is just the regex :)
