### ISSUE TITLE
Local installation causes issues since it installs outdated npm 3.10.x

### ISSUE THREAD

**Issue by IAMtheIAM** [tjunnone/npm-check-updates#453]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.11.4
* npm version: 5.6.0
* npm-check-updates version: 2.14.2

---------------------------
If the package is installed locally rather than globally, it causes major issues because it forces an installation of npm v3.10.x into local node_modules, which then gets used on subsequent `npm` scripts, causing all kinds of errors due to being outdated. Either
1) Don't install npm locally, because it should already be installed globally and if not, it needs to be
2) Install an up to date version of npm locally.

**Comment by raineorshine** [comment]
Thank you, this is clearly needed. The internal npm dependency will be removed in ncu `v3`. Unfortunately release has been delayed because there are no active contributors. Hopefully someone steps up.

**Comment by jamescodesthings** [comment]
+1 requiring NPM@3 caused all kinds of problems, had to remove the package for now.
