### ISSUE TITLE
zsh: command not found: ncu

### ISSUE THREAD

**Issue by vayurobins** [tjunnone/npm-check-updates#454]
node@v8.9.4
npm@6.4.1
npm-check@5.8.0
npm-check-updates@2.14.2
Mac OS@10.13.6

When I install npm-check-updates and thereafter use the ncu or the npm-check-update command, I just get the "command not found".

I hope someone can help? Thanks

**Comment by raineorshine** [comment]
Hi Vayu. Sorry for the trouble! Do other global npm packages work? Have you tried uninstalling and reinstalling npm-check-updates? Do you get anything from the command `type ncu`?

I'm not sure what the issue is, but it seems like it is at the level of your environment rather than npm-check-updates.

**Comment by vayurobins** [comment]
Thanks for responding. Good questions. After a few hours of trying to find a problem, I realized that adding this `/usr/local/share/npm/bin` to my PATH in .zshrc fixed the problem.
Thanks for helping!

**Comment by cfremgen** [comment]
For Windows uers, add to PATH:

C:\Users\UserName\AppData\Roaming\npm

**Comment by giulianagabrielli** [comment]
Hi, could anyone help me? 
I'm having this "command not found" issue too.
I'm using mac. Which file should I open and what do I need to write in it to correct the path? 
Thank you.

**Comment by raineorshine** [comment]
@giulianagabrielli 

1. Where is npm located on your machine? 
  - Enter this in a terminal: `type npm`.
2. What is in your PATH? 
  - `node -p "console.log(process.env.PATH.split(':').join('\n'))"`

Where does npm install packages?
https://stackoverflow.com/a/5926706/480608

You might have to add something like this to your `~/.bash_profile` file:

```
export PATH=$HOME/local/bin:$PATH
```

**Comment by romenigld** [comment]
I just run a `asdf reshim` and then I try and work's!

**Comment by ayachish** [comment]
> @giulianagabrielli
> 
> 1. Where is npm located on your machine?
> 
> * Enter this in a terminal: `type npm`.
> 
> 2. What is in your PATH?
> 
> * `node -p "console.log(process.env.PATH.split(':').join('\n'))"`
> 
> You might have to add something like this to your `~/.bash_profile` file:
> 
> ```
> export PATH=$HOME/local/bin:$PATH
> ```
> 
> Or this:
> 
> ```
> npm config set prefix /usr/local
> ```
> 
> This is probably the answer you want: https://stackoverflow.com/questions/14803978/npm-global-path-prefix

thank you so much, this helped!
