### ISSUE TITLE
[Feature Request]: Figure out unused npm dependencies

### ISSUE THREAD

**Issue by khaledosman** [tjunnone/npm-check-updates#457]
Would be nice if ncu would look at the package.json file and figure out which npm dependencies are unreferenced in the code and print them out as "unused" or similar.

**Comment by einperegrin** [comment]
In my opinion, this feature is a part of the static analysis of all code. But this tool checks just package.json.

**Comment by Vaibhav** [comment]
You could just use this: 

https://www.npmjs.com/package/npm-check-unused
