### ISSUE TITLE
What's the difference between ncu -a and ncu -u?

### ISSUE THREAD

**Issue by Kimserey** [tjunnone/npm-check-updates#459]
- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.11.3
* npm version: 5.6.0
* npm-check-updates version: 2.14.2

---------------------------

At one point in time I thought that `ncu -u` was updating only packages (in package.json) that needed to be updated (top list in `ncu` command result) while `ncu -a` was updating everything (top + bottom list in `ncu` command result).
But it seems like I got it wrong as they both seem to yield the same result; updating everything.

Could someone advise on the differences between `ncu -u` and `ncu -a`? If possible with an example?
Also when would you use `ncu -u -a`?

**Comment by raineorshine** [comment]
Yes, your initial interpretation is correct. Here are the unit tests that confirm this behavior: https://github.com/tjunnone/npm-check-updates/blob/87af594f68e23c522c18e3b318cab368e85da278/test/test-versionmanager.js#L137-L163

If you have a package.json that breaks this please post here!

`-au` is the same as `-a`

**Comment by Kimserey** [comment]
I have updated `npm` to version 6.4.1 and can't reproduce the issue anymore.
It now behave as you confirmed and as I expected it.

Thank you!
