### ISSUE TITLE
[enhacement] export package names

### ISSUE THREAD

**Issue by vire** [tjunnone/npm-check-updates#46]
Hi currently I'm not aware of the possibility of npm-check-updates to update all global packages in one run, so if this is not yet possible, it would be nice, to have the option to update all global packages `npm update -g [<name> [<name> ...]]`

now: 

`npm-check-updates -g`

produces:
```
"jshint" can be updated from 2.5.11 to 2.6.0
"node-inspector" can be updated from 0.8.1 to 0.8.3
"npm-check-updates" can be updated from 1.3.0 to 1.5.1
"testem" can be updated from 0.6.24 to 0.6.38
```

and `npm-check-updated -gn` (-n like names)

could produce an output **"jshint node-inspector npm-check-updates testem"** which could be passed to  `npm update -g' as the [npm update names arg](https://docs.npmjs.com/cli/update)

What do you think about this feature? (I know it could be done via sed without any change, but that's too much of **sed**ism :)

**Comment by metaraine** [comment]
I was able to update all global packages with `npm update -g`. Does that
solve your problem or are you dealing with something different?

**Comment by vire** [comment]
:+1 thats huge!

problem solved without a line of code :)
