### ISSUE TITLE
Can't catch the timeout error 

### ISSUE THREAD

**Issue by igor-lemon** [tjunnone/npm-check-updates#460]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v9.11.1
* npm version: 6.4.1
* npm-check-updates version: 2.14.2

---------------------------

If I set the timeout option I can't catch the error. I see the error message in console. But the promise always resolves. Timeout option doesn't stop script execution.

```javascript
ncu.run({ timeout: 1000 }).then((result) => {
// The script doesn't stop after 1s.
}).catch((error) => {
 // I don't see timeout error here
})
```

**Comment by raineorshine** [comment]
Thanks for reporting! Fixed and published in `v2.14.3` (Commit https://github.com/tjunnone/npm-check-updates/commit/850666c9061d1d2ae75b53ed692fc48ddfda9d5f)
