### ISSUE TITLE
new feature request — recognise packages used by babel.config.js

### ISSUE THREAD

**Issue by revelt** [tjunnone/npm-check-updates#464]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.13.0
* npm version: 6.4.1
* npm-check-updates version: 2.14.3

---------------------------

Currently `npm-check-updates` does not recognise packages used only by `babel.config.js` config which sits in the root.

Here's a sample `babel.config.js` to try:

```js
module.exports = function babelConfig(api) {
  const plugins = [
    '@babel/plugin-proposal-class-properties'
  ]
  return {
    plugins
  }
}
```

then make sure the `@babel/plugin-proposal-class-properties` is required among dependencies. When `ncu` is ran, you should get:

<img width="552" alt="msg" src="https://user-images.githubusercontent.com/8344688/48953849-1dfe8e00-ef3f-11e8-812f-7120535e8e36.png">

I think it should be technically possible to expand the places where we search for "used" things so that Babel configs are included, what do you think?

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
