### ISSUE TITLE
Issue a warning when repository owner is changed

### ISSUE THREAD

**Issue by ceremcem** [tjunnone/npm-check-updates#465]
- [x] I have read *most of* the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue. (took a quick look, though)

---------------------------

This is an enhancement request: Due to a security vulnerability message of a dependency package, I took a look at the [issue](https://github.com/dominictarr/event-stream/issues/116) and understand the injection has been performed by a different person, not by the creator of the library. 

Original author drops maintaining the library, then someone wants it, he hands it over. The new guy implements a malicious code, publishes it. Currently even the original author has no publish rights on npm. 

What I could think of is that: npm-check-updates might warn us when owner is changed, like in the way: 

```
************************************ WARNING ******************************************

This repository's owner has changed. You are advised to check on the new owner. 
Please type the new owner's mail address to continue: ...

************************************ WARNING ******************************************
```

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
