### ISSUE TITLE
Falsely reports "All dependencies match the latest package versions :)" for some packages

### ISSUE THREAD

**Issue by jacobq** [tjunnone/npm-check-updates#466]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 11.4.0
* npm version: 6.5.0
* npm-check-updates version: 2.15.0

---------------------------

## Steps to reproduce problem:

1. Run `npm init` in an empty directory and accept the defaults
2. Install something like `@types/node` with `npm` or `yarn` & save to either dependencies or devDependencies. Strangely, the problem seems to be package specific. For example, I could not get it to happen with `chalk`. Perhaps it has to do with how recently the new packages were published??
3. Edit `package.json` and intentionally set the version back
4. Run `ncu` and observe that it reports all dependencies are up to date (even though they are not)

Here's an example `package.json`:
```json
{
  "name": "ncu-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ember-cli-htmlbars-inline-precompile": "^2.0.0"
  },
  "devDependencies": {
    "@types/node": "^10.12.14"
  }
}
```

but `npm info` shows the following for these packages:

```
ember-cli-htmlbars-inline-precompile@2.1.0 | MIT | deps: 5 | versions: 35
Precompile inline HTMLBars templates via ES6 tagged template strings
https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile#readme

keywords: ember-addon, ember-cli

dist
.tarball: https://registry.npmjs.org/ember-cli-htmlbars-inline-precompile/-/ember-cli-htmlbars-inline-precompile-2.1.0.tgz
.shasum: 61b91ff1879d44ae504cadb46fb1f2604995ae08
.integrity: sha512-BylIHduwQkncPhnj0ZyorBuljXbTzLgRo6kuHf1W+IHFxThFl2xG+r87BVwsqx4Mn9MTgW9SE0XWjwBJcSWd6Q==
.unpackedSize: 44.2 kB

dependencies:
babel-plugin-htmlbars-inline-precompile: ^1.0.0 hash-for-dep: ^1.2.3                            silent-error: ^1.1.0                            
ember-cli-version-checker: ^2.1.2               heimdalljs-logger: ^0.1.9                       

maintainers:
- ember-cli <stefan.penner+ember-cli@gmail.com>
- pangratz <cmueller.418@gmail.com>
- rwjblue <me@rwjblue.com>
- stefanpenner <stefan.penner@gmail.com>
- turbo87 <tobias.bieniek@gmx.de>

dist-tags:
beta: 0.4.0-beta.2  latest: 2.1.0       v0-3-x: 0.3.12      

published 6 days ago by rwjblue <me@rwjblue.com>
```

```
@types/node@10.12.18 | MIT | deps: none | versions: 487
TypeScript definitions for Node.js

dist
.tarball: https://registry.npmjs.org/@types/node/-/node-10.12.18.tgz
.shasum: 1d3ca764718915584fcd9f6344621b7672665c67
.integrity: sha512-fh+pAqt4xRzPfqA6eh3Z2y6fyZavRIumvjhaCL753+TVkGKGhpPeyrJG2JftD0T9q4GF00KjefsQ+PQNDdWQaQ==
.unpackedSize: 581.6 kB

maintainers:
- types <ts-npm-types@microsoft.com>

dist-tags:
latest: 10.12.18  ts2.1: 10.12.18   ts2.3: 10.12.18   ts2.5: 10.12.18   ts2.7: 10.12.18   ts2.9: 10.12.18   ts3.1: 10.12.18   ts3.3: 10.12.18   
ts2.0: 10.12.18   ts2.2: 10.12.18   ts2.4: 10.12.18   ts2.6: 10.12.18   ts2.8: 10.12.18   ts3.0: 10.12.18   ts3.2: 10.12.18   

published 5 hours ago by types <ts-npm-types@microsoft.com>
```

**Comment by linvain** [comment]
![image](https://user-images.githubusercontent.com/42490556/50472392-a7373380-09c9-11e9-888e-95efb1120a22.png)

Same for me. Look at the image: ncu reports that all deps are up to date though they are not. Not only for this one, there are like 10 more.

Strangely enough:
I have very similar second project, in which `ncu` reported "up to date" but `ncu -a` updated everything as expected. However, in this project both `ncu` and `ncu -a` report "up to date".

UPD: i ran `yarn add @babel/cli@7.2.0` then `ncu -a` and ncu updated everything as expected.

node version: 11.6.0
npm version: 6.5.0
npm-check-updates version: 2.15.0

If it helps: i am using yarn and `semver` package is installed not through npm but through pacman.
`npm ls -g --depth=0` output:
```
/usr/lib
├── node-gyp@3.8.0
├── npm@6.5.0
├── npm-check-updates@2.15.0
└── yarn@1.12.3

npm ERR! missing: semver@^5.5.1, required by npm@6.5.0
```

**Comment by raineorshine** [comment]
Yes, this is confusing behavior and should be fixed in v3. See https://github.com/tjunnone/npm-check-updates/issues/389. 

Unfortunately ncu is lacking in contributors at the moment.

**Comment by raineorshine** [comment]
Closing in anticipation of branch `v3` (where this is fixed) being released soon. See #471 for roadmap.
