### ISSUE TITLE
Support NPQ

### ISSUE THREAD

**Issue by acekevin** [tjunnone/npm-check-updates#468]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: LTS
* npm version: LTS
* npm-check-updates version: Latest

---------------------------

Is it possible to support [NPQ](https://github.com/lirantal/npq) as a package manager installer so we can have better security guidance on what we are installing?

Alternatively, if NCU could output the list of installs so the output could be chained into a custom command? Such as `ncu -u --drystring` outputting a dry run string of `sinon@7.2.2 eslint@5.11.1` so we can then easily call `npq install $(ncu -u --drystring)`

**Comment by raineorshine** [comment]
That's a great idea! New package managers can be added fairly easily, as described here: https://github.com/tjunnone/npm-check-updates/tree/master/lib/package-managers

The `ncu` command by default is a dry run and does not update anything. There is `ncu -j` which outputs json, which might be easiest to transform into an install command. It will require either some additional shell or js scripting to convert.

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
