### ISSUE TITLE
Replaces terminal prompt with progress bar when ran programatically/Not honouring silent: true

### ISSUE THREAD

**Issue by j0nas** [tjunnone/npm-check-updates#469]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.13.0
* npm version: 6.4.1
* npm-check-updates version: 2.15.0
* OS: macOS Mojave
---------------------------

My terminal prompt gets replaced with a progress bar after calling `run` programatically from `npm-check-updates` ([like so](https://github.com/j0nas/init-project/blob/44e709f760c4fc4deb361a32b2d45d30cb2c36cc/src/api.js#L31)), and stays that way for the duration of the process: 

![image](https://user-images.githubusercontent.com/6001131/50549724-01353480-0c28-11e9-8509-72ac530c26dd.png)

Steps to reproduce:
- `npm i -g create-new-project`
- `init my-test-project`

You should see the terminal prompt be replaced with a progress bar. 

This is not a big issue, but NPM install seems to use the same progress bar and doesn't cause this issue, so I expect the fix to simply be a version bump. 
However, I would also expect that passing `silent: true` in the config would mute any output, including not displaying a progress bar.

I couldn't find any existing issues/PRs for these things. Is a PR for this wanted?

**Comment by raineorshine** [comment]
Good catch! I believe this comes from the underlying `npm` command that gets run. At some point npm added the progress bar and it started bleeding through into ncu's output. I am not sure how to disable it without also disabling the stdout from npm that ncu uses to determine updates.

**Comment by j0nas** [comment]
> This is not a big issue, but NPM install seems to use the same progress bar and doesn't cause this issue, so I expect the fix to simply be a version bump.

I see that you're depending on npm ^3.10 in your package.json. Would you accept a PR to bump it to the latest version?

**Comment by j0nas** [comment]
Alright! 😄 I'm definitely interested in contributing to v3. 
I tried to search around for a v3 roadmap or list of remaining changes, but couldn't find anything of the likes. Is there such a document anywhere, or somewhere to get an overview of what needs to be done?

**Comment by raineorshine** [comment]
@j0nas Amazing!!! Thank you! I have created #471 to track progress towards v3. Please comment there and I will be glad to offer support!

**Comment by joebnb** [comment]
same problem + 1

**Comment by joebnb** [comment]
hi @j0nas did you working on this issue ?if not , i can trying to solve this

**Comment by j0nas** [comment]
@joebnb I'm sorry, I'm swamped with moving and switching jobs at the moment, do take a crack at it if you can. Apologies for trying to stepping up and revoking that promise again :(

**Comment by raineorshine** [comment]
Fixed in ncu v3.0.5

**Comment by joebnb** [comment]
great
