### ISSUE TITLE
ncu different behaviour from VS Code git-bash terminal and standalone git-bash terminal

### ISSUE THREAD

**Issue by nicewaytodoit** [tjunnone/npm-check-updates#470]
If I run ncu in standalone git-bash terminal, of course withing the project folder - I get message:
```
Hmmmmm... this is taking a long time. Your console is telling me to wait for input
on stdin, but maybe that is not what you want.
Try specifying a package file explicitly with --packageFile package.json.
See https://github.com/tjunnone/npm-check-updates/issues/136#issuecomment-155721                              102
```
but if I do it by opening VS Code (code .) end then run the same command in git-bash terminal within VS Code ncu will not complains that I need to supply extra parameter for package.json file.

```
$ node -v  = v10.15.0
$ npm -v  = 6.4.1
$ ncu -v = 2.15.0
Windows 10 x64
```
I have not had issue before, so what is the setting withing ncu that makes difference between two git-bash terminals ?

**Comment by tw0517tw** [comment]
You may like to take a look at https://github.com/tjunnone/npm-check-updates/issues/136#issuecomment-184275891 .

**Comment by nicewaytodoit** [comment]
Thank you 
`winpty ncu.cmd`  works, 
but can this be embedded into the ncu code?

Somehow I do not see users remembering this.

**Comment by raineorshine** [comment]
@nicewaytodoit I'm not sure we can assume that `winpty` is on all users' machines. I can update the message however to at least suggest the command.

**Comment by hizablet** [comment]
> Thank you
> `winpty ncu.cmd` works,
> but can this be embedded into the ncu code?
> 
> Somehow I do not see users remembering this.

 `winpty ncu.cmd` works ,but use `ncu -u` it still display ：
```
Hmmmmm... this is taking a long time. Your console is telling me to wait for input
on stdin, but maybe that is not what you want.
Try winpty ncu.cmd, or specify a package file explicitly with --packageFile package.json.
See https://github.com/raineorshine/npm-check-updates/issues/136#issuecomment-155721102
```
it drive me crazy!!!😭

**Comment by raineorshine** [comment]
`winpty ncu.cmd -u`

**Comment by oshihirii** [comment]
tried:

    winpty ncu.cmd -u

got:

    winpty: error: cannot start 'ncu.md': Not found in PATH

**Comment by raineorshine** [comment]
> `ncu --loglevel verbose --packageFile package.json`

`--loglevel verbose` is used primarily for debugging.

`--packageFile` explicitly specifies where the package.json file is located, relative to the current working directory. It is sometimes needed on Windows if there is unexpected TTY behavior causing `npm-check-updates` to wait indefinitely for data on stdin.

> ncu -u --packageFile package.json

`-u` overwrites your package file. If you omit `-u`, it will execute a read-only dry run and just display the updates in the console instead of updating the package file.

> ```
> // and for some reason i then had to run npm install (or else some of my dev dependencies were not in my node_modules folder ¯\_(ツ)_/¯ )
> ```

This is expected. `npm update` will not install updates if they are already changed in the package.json. So you need to use `npm install` instead.
