### ISSUE TITLE
v3 ROADMAP

### ISSUE THREAD

**Issue by raineorshine** [tjunnone/npm-check-updates#471]
This issue track progress towards a v3 release. Comments related to individual items should go in their respective issues.

- Code: [v3 branch](https://github.com/tjunnone/npm-check-updates/tree/v3)
- Milestones: [v3 issues](https://github.com/tjunnone/npm-check-updates/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0)

The most important is #440 (es6) and #350 (switching to system npm). The conversion to es6 needs to happen before any other changes can really be made to the codebase.

**Comment by j0nas** [comment]
I'm interested in doing #440. Would it be preferable to do the rewrite with Typescript?

**Comment by karanjthakkar** [comment]
Hey @raineorshine! Just wanted to drop in and say that there was some work regarding #440 that I did which can be tracked here: https://github.com/tjunnone/npm-check-updates/tree/es6 It was branched off of `v3`. All the changes have been done using codemods. The commit log should be helpful to see which ones. However, I don't think I will have the bandwidth to take it forward anytime soon. So feel free to use that as the base to build towards complete es6 support. The branch won't be useful if rewriting in Typescript is something that is planned.

**Comment by raineorshine** [comment]
@j0nas Thanks! I would prefer not to do this project in Typescript though. Just updating the code to es6 will be a nice improvement.

@karanjthakkar Thanks for the followup and the work you did so far!

I can merge karan's branch onto v3 when I get the chance. You are welcome to as well @j0nas just not sure how bad the merge conflicts will be. If they are bad, might be worth running the codemods again from scratch.

**Comment by raineorshine** [comment]
- [x] Merged
- [x] All tests pass

I think @karanjthakkar's es6 modifications via [js-codemod](https://github.com/cpojer/js-codemod) accomplish the major goal of upgrading to more modern syntax. The exact transformations were:

- use-strict
- unquote-properties
- template-literals
- object-shorthand
- no-vars
- arrow-function (I did this earlier in the v3 branch)

Take a look at the code (e.g. [lib/versionmanager.js](https://github.com/tjunnone/npm-check-updates/blob/v3/lib/versionmanager.js)) and if there is something I am missing please mention it! Otherwise we may be ready to get into functional v3 milestones.

**Comment by kibertoad** [comment]
@raineorshine Checked out the code, raised https://github.com/tjunnone/npm-check-updates/pull/473 to address couple of minor things.

**Comment by raineorshine** [comment]
@kibertoad I cleaned up the v3 milestone and added some comments for clarification. All that is left for a `v3` release are two issues: #368 and #438!

Would love the help in getting those resolved! If you have any questions, please post in the respective issues. Thanks!

**Comment by raineorshine** [comment]
v3 published: https://github.com/tjunnone/npm-check-updates/releases/tag/v3.0.0
