### ISSUE TITLE
`dist-tags.latest` & npm view PCK show latest by date not by value

### ISSUE THREAD

**Issue by McFoggy** [tjunnone/npm-check-updates#475]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.15.0
* npm version: 6.4.1
* npm-check-updates version: 2.12.0

---------------------------

It seems that for npm latest version is retrieved by looking at the field `dist-tags.latest` of the result of execution of `npm view PCK`, see [here](https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L110).
Unfortunately this is wrong because it reports the latest value __by date__ but not by version value.

On a module we have, if I look at the cached metadata of the package inside my `node_cache/..../my_lib/.cache.json` I can find

```
{
...
	"dist-tags": {
		"latest": "2.13.0"
	},
	"versions": {
             .... 
                all known versions here 
             ....
	},
	"name": "@mycompany/my_lib",
	"time": {
		"created": "2017-05-11T06:07:01.416Z",
                ...
		"2.2.0": "2018-04-27T13:11:06.486Z",
                ...
		"3.7.1": "2019-01-16T14:20:18.169Z",
		"2.13.0": "2019-01-16T16:46:50.989Z"
	}
}
```

here the latest field reflects the __latest by date__ published version __not__ the __highest__ we are interested in with [npm-check-updates](https://github.com/tjunnone/npm-check-updates)

**Comment by raineorshine** [comment]
In the npm world, "latest" refers to whatever is published under the "latest" tag. Ultimately it is up to the package authors. This is what npm uses to install `mymodule@latest`. ncu follows the same semantics.

To search the newest version number, use `ncu --newest`. To search the highest version number, use `ncu --greatest`.

**Comment by McFoggy** [comment]
ok thanks.
