### ISSUE TITLE
Feature request : support yarn workspace

### ISSUE THREAD

**Issue by sylvainbaronnet** [tjunnone/npm-check-updates#476]
Hello,

It would be nice if ncu could detect yarn workspace conf from main package.js and work with all package.json at once

**Comment by raineorshine** [comment]
Closed with the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Arevive-me+) tag for interested contributors. See #484.
