### ISSUE TITLE
Question: How to specify which dist-tag to upgrade to?

### ISSUE THREAD

**Issue by mohsinulhaq** [tjunnone/npm-check-updates#478]
Just filing to ask if it's possible to specify the dist-tag to upgrade to. I can only see -n and -t which doesn't seem to satisfy my use case. For example I have many rcs and alphas released. And I want to upgrade to latest rc of that package which may not necessarily be the latest release.

**Comment by raineorshine** [comment]
This is not currently supported. Good idea for an enhancement.

**Comment by raineorshine** [comment]
Closed with the `revive-me` tag for interested contributors. See #484.
