### ISSUE TITLE
"npm" can be updated from 2.5.1 to 2.5.0

### ISSUE THREAD

**Issue by cowst** [tjunnone/npm-check-updates#48]
npm-check-updates -g
"npm" can be updated from 2.5.1 to 2.5.0

npm -v
2.5.0

npm install npm
npm WARN prefer global npm@2.5.0 should be installed with -g
npm@2.5.0 node_modules/npm

npm uninstall npm
unbuild npm@2.5.0

npm-check-updates -g
All global packages are up to date :)

Funny :)

**Comment by metaraine** [comment]
Thanks. There is a known issue with installed versions beyond what is
listed as "latest".

**Comment by metaraine** [comment]
Changed npm-check-updates to never downgrade. Published on unstable tag. Feedback welcome!

`npm install npm-check-updates@unstable`
