### ISSUE TITLE
High and Moderate Vulnerabilities

### ISSUE THREAD

**Issue by fuzzthink** [tjunnone/npm-check-updates#480]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.15
* npm version: 6.4.1
* npm-check-updates version: 2.15

---------------------------

`npm audit` reports:
**High** vulnerabilities from this repo via:
tough-cookie - fixed in: https://github.com/salesforce/tough-cookie/issues/92
sshpk - fixed in: https://github.com/joyent/node-sshpk/issues/49

Moderate vulnerabilities:
tunnel-agent - open issue: https://github.com/request/tunnel-agent/issues/41
hoek - fixed in: https://github.com/hapijs/hoek/issues/230 and tracked in this repo since April'18 in this repo https://github.com/tjunnone/npm-check-updates/issues/432
brace-expansion - fixed in: https://github.com/juliangruber/brace-expansion/issues/33
stringstream  - https://github.com/mhart/StringStream/issues/12

Low:
debug - fixed in: https://github.com/visionmedia/debug/issues/570

With 6 out of 7 vulnerabilities fixed, the only question is if chain of packages from those to this repo have already pulled in the fixes. Can maintainers please take a look at this? This is pretty important since 6 of these are **High** and Moderate vulnerabilities.

**Comment by raineorshine** [comment]
Thanks! Packages will be updated in the upcoming v3 release. Development has been delayed due to there not being any active contributors.
