### ISSUE TITLE
Command ncu -u doesn't upgrade my package.json

### ISSUE THREAD

**Issue by anonimoconiglio** [tjunnone/npm-check-updates#482]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 11.10.1-1
* npm version: 6.8.0-1
* npm-check-updates version: 2.15.0-1
* ncu version: 2.15.0
---------------------------
The command `ncu -u` doesn't upgrade my `package.json` file.

```node
ncu -u                                                    
Using /path/to/package.json
[..................] / :
 gatsby                  ^2.1.19  →  ^2.1.22 
 gatsby-image            ^2.0.30  →  ^2.0.31 
 gatsby-plugin-manifest  ^2.0.20  →  ^2.0.21 
 gatsby-plugin-sharp     ^2.0.23  →  ^2.0.24 
 gatsby-remark-images     ^3.0.5  →   ^3.0.6 
 react-spring             ^8.0.9  →  ^8.0.11 
```

It lacks the message `package.json upgraded` and indeed the package doesn't change at all.

**Comment by raineorshine** [comment]
Thanks for reporting. I will try this out when I am at my computer and see if I can reproduce.

**Comment by mgohin** [comment]
I can relate

**Comment by thebiltheory** [comment]
I downgraded my ncu version in the meantime.
Not sure in was version it's breaking but I randomly downgraded to 2.11.0 

@anonimoconiglio `npm install -g npm-check-updates@2.11.0`

**Comment by anonimoconiglio** [comment]
> I downgraded my ncu version in the meantime.
> Not sure in was version it's breaking but I randomly downgraded to 2.11.0
> 
> @anonimoconiglio `npm install -g npm-check-updates@2.11.0`

Did it work if downgraded?

**Comment by raineorshine** [comment]
That's very odd. `-u` is upgrading the package.json on my end.

**Comment by anonimoconiglio** [comment]
I just upgraded to V3 (3.0.3) and now it works again!
```node 
ncu -u      
Using /home/path/to/package.json

 gatsby                       ^2.1.19  →   ^2.1.27 
 gatsby-image                 ^2.0.30  →   ^2.0.31 
 gatsby-plugin-manifest       ^2.0.20  →   ^2.0.22 
 gatsby-plugin-react-helmet    ^3.0.7  →    ^3.0.8 
 gatsby-plugin-sharp          ^2.0.23  →   ^2.0.25 
 gatsby-remark-images          ^3.0.5  →    ^3.0.6 
 gatsby-transformer-remark     ^2.3.0  →    ^2.3.1 
 react                        ^16.8.3  →   ^16.8.4 
 react-dom                    ^16.8.3  →   ^16.8.4 
 react-spring                  ^8.0.9  →   ^8.0.14 
 react-typography            ^0.16.18  →  ^0.16.19 
 typography                  ^0.16.18  →  ^0.16.19 
 typography-theme-sutro      ^0.16.18  →  ^0.16.19 

Upgraded /home/path/to/package.json. Run npm install to install new versions.

```
