### ISSUE TITLE
Dep option does not seem to work

### ISSUE THREAD

**Issue by morganfree** [tjunnone/npm-check-updates#489]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.13.0
* npm version: 6.4.1
* npm-check-updates version: 3.0.2

---------------------------

`ncu --dep prod` does not seem to have any effect on filtering out the depedencies.
It also does not work as a module:
```
ncu.run({
  dep: 'prod',
}).then(upgraded => {
  console.log(upgraded)
})
```

package.json
```json
  "dependencies": {
    "npm-check-updates": "^3.0.2",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "simple-git": "^1.107.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1"
  }
```
output
```
eslint  ^4.19.1  _  ^5.15.1
```

**Comment by raineorshine** [comment]
Will investigate. Thanks!
