### ISSUE TITLE
npm-check-updates -f /^((?!gulp-).)*$/ doesn't work

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#49]
```
npm-check-updates -f /^((?gulp).)*$/
package.json not found
```

I've tried lots of regex, it does that.

1.5.1 here.

**Comment by metaraine** [comment]
Thanks, I will look into it.

**Comment by kud** [comment]
I wanted to do `$ npm-check-updates -f /^gulp/`, it only returns `gulp`, not `gulp` + `glulp-*`.

**Comment by metaraine** [comment]
It's working as of 1.4.0. The gulp regex provided in the readme needed single quotes to avoid bash parsing: `npm-check-updates -f '/^(?!gulp-).*$/'`. Thanks!
