### ISSUE TITLE
Unhandled rejection on Git URLs

### ISSUE THREAD

**Issue by gavinhungry** [tjunnone/npm-check-updates#491]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: `11.11.0`
* npm version: `6.8.0`
* npm-check-updates version: `3.0.2`

---------------------------

Starting with `3.0.x`, `ncu` crashes with `Unhandled rejection` if my `package.json` contains (some?) Git URLs (I haven't been able to narrow down exactly what it is that `ncu` doesn't like).

Example:

```json
{
  "dependencies": {
    "lodash": "4.10.x",
    "some-private-module": "git+https://mycompany.biz/git/some-private-module"
  }
}
```

```
$ ncu --loglevel verbose
Initializing...
Running in local mode...
Finding package file data...
Using /tmp/test/package.json
Fetching latest versions...
Unhandled rejection 
```

Since `ncu` can't check these anyway (#463), shouldn't they be ignored?

The same `package.json`, but with `ncu` `2.15.0`:

```
Using /tmp/test/package.json
[..................] \ :
 lodash  4.10.x  →  4.17.x 

Run ncu with -u to upgrade package.json
```

**Comment by raineorshine** [comment]
Hi @gavinhungry, thanks for reporting. I tried this out and I didn't get any error myself. It seems to ignore git urls for me. If you can find out what the actual error is, that might be a good way forward.

**Comment by gavinhungry** [comment]
@raineorshine,

Update: with `ncu` `3.0.5`, I now see:
```
Using /tmp/test/package.json
[================----] 80%Unhandled rejection PackageNotFoundError: Package `some-private-module` could not be found
    at packageJson (/home/gavin/.local/lib/node_modules/npm-check-updates/node_modules/package-json/index.js:70:10)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by robjackstewart** [comment]
I can confirm this is a problem as of `ncu` version  `3.0.5`:

```
ClientApp> ncu
[===================-] 93%Unhandled rejection PackageNotFoundError: Package `ng-uikit-pro-standard` could not be found
    at packageJson (C:\Users\robja\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\package-json\index.js:70:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by dfadev** [comment]
I am also getting this error on "git+ssh" entries.

**Comment by imrefazekas** [comment]
+1 me too, same error for all repose references with git + ssh or https

**Comment by raineorshine** [comment]
Should be fixed in latest!

**Comment by gavinhungry** [comment]
`ncu` `3.0.8` works for me, thanks!
