### ISSUE TITLE
ncu command gets stuck (3.0.4)

### ISSUE THREAD

**Issue by ibc** [tjunnone/npm-check-updates#496]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.15.0
* npm version: 6.8.0
* npm-check-updates version: 3.0.4
* OS: OSX 10.14.1

---------------------------

Sometimes `ncu` command gets stuck forever and ever. It seems to happen always in the same project directories. It does not happen in others. I'm trying to get a patron but could just get a repo in which `ncu` always gets stuck. I don't see any option in `ncu` command to do debugging or whatever so not sure why it's failing.

### Steps to reproduce

```bash
$ git clone git@github.com:versatica/mediasoup-client.git

$ npm i

$ time ncu
// => never ends
```

NOTE: Eventually I got it working, but it took SO long. It was just once.

**Comment by raineorshine** [comment]
Thanks for reporting. In v3, ncu naively spawns a new process for each
module in your package.json, which may result in very long wait times. A PR
for this is being worked on. I would also like to add a progress bar.

It is also possible that there is a failed asynchronous request that is
timing out and not being caught correctly. That's a bit trickier to find.
There is --logLevel verbose, but I am not if that will generate anything
useful in this case.

Stay tuned for the next patch, and hopefully that prevents the time outs!

**Comment by ibc** [comment]
Thanks. Given that "sometimes" it works and sometimes it never ends, I'll expect that some spawned process is failing and produces the forever timeout.

**Comment by artemsky** [comment]
same issue.
ncu 3+ spaws tons of processes and works more than 30 seconds while ncu 2 did the same in 2 seconds

**Comment by Primajin** [comment]
Yes, and please please bring back the progress bar or some kind of indicator back that something is actually happening. In v2 or native npm I can see a progressbar and a thing spinning, while in v3 it just says `Using /whatever/package.json` for a while and you don't know if it's stuck or not.

**Comment by Blunderchips** [comment]
Same isssue

**Comment by jtinz** [comment]
To clarify: Very long load times should not be several hours while the system is idling?

This is the output I get now. ncu did work before:
`ncu --loglevel verbose
Initializing...
Running in local mode...
Finding package file data...
Checking D:\myfolder\ts\package.json
Fetching latest versions...
[--------------------] 0/7 0%
`

**Comment by raineorshine** [comment]
@jtinz Yeah, it should not be that long, unless the network connection is completely blocked.

Without steps to reproduce it on a different machine, I'm not able to debug. We need a generous user who is experiencing this issue to dig into the code, put in some console.logs, and figure out where it's hanging.
