### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by dantman** [tjunnone/npm-check-updates#50]
I'm getting this error.

```
$ npm-check-updates -g
/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:88
            var unconstrainedCurrentVersion = currentVersion.substr(getVersion
                                                            ^
TypeError: Cannot read property 'substr' of undefined
    at Object.upgradeDependencies (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:88:61)
    at /usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:30:39
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:286:9
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:270:13
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:251:9
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/view.js:146:28
```

I've tried removing and re-installing the module.

**Comment by metaraine** [comment]
Can you narrow it down to which dependency is causing it to fail? It looks
like the version manager is not parsing one of the version numbers
correctly.

**Comment by metaraine** [comment]
I see you are running it globally, so maybe that question is not as relevant. Still, it's probably a single module. What global modules do you have installed?

**Comment by dantman** [comment]
`
$ ls /usr/local/lib/node_modules/
bower			i18next-conv		npm
codepainter		jshint			npm-check-updates
coffee-script		jsocco			sequelize-cli
express-generator	less			ssmount
groc			mocha			uglify-js
grunt-cli		node-inspector
grunt-init		nodeunit
`

**Comment by dantman** [comment]
I inserted `console.log(currentDependencies, latestVersions, currentDependencies);` after line 77 of versionmanager.js and console.log(dependency); before line 88.

This is the output:
```
$ npm-check-updates -g
{ bower: '1.3.12',
  codepainter: '0.4.4',
  'coffee-script': '1.9.0',
  'express-generator': '4.11.2',
  undefined: undefined,
  'grunt-cli': '0.1.13',
  'grunt-init': '0.3.2',
  'i18next-conv': '0.1.4',
  jshint: '2.6.0',
  jsocco: '0.1.0',
  less: '2.4.0',
  mocha: '2.1.0',
  'node-inspector': '0.8.3',
  nodeunit: '0.9.0',
  npm: '2.5.1',
  'npm-check-updates': '1.5.1',
  'sequelize-cli': '1.2.0',
  ssmount: '0.5.1',
  'uglify-js': '2.4.16' } { bower: '1.3.12',
  codepainter: '0.4.4',
  'coffee-script': '1.9.0',
  'express-generator': '4.11.2',
  undefined: '0.1.0',
  'grunt-cli': '0.1.13',
  'grunt-init': '0.3.2',
  'i18next-conv': '0.1.4',
  jshint: '2.6.0',
  jsocco: '0.1.0',
  less: '2.4.0',
  mocha: '2.1.0',
  'node-inspector': '0.8.3',
  nodeunit: '0.9.0',
  npm: '2.5.0',
  'npm-check-updates': '1.5.1',
  'sequelize-cli': '1.2.0',
  ssmount: '0.5.1',
  'uglify-js': '2.4.16' } { bower: '1.3.12',
  codepainter: '0.4.4',
  'coffee-script': '1.9.0',
  'express-generator': '4.11.2',
  undefined: undefined,
  'grunt-cli': '0.1.13',
  'grunt-init': '0.3.2',
  'i18next-conv': '0.1.4',
  jshint: '2.6.0',
  jsocco: '0.1.0',
  less: '2.4.0',
  mocha: '2.1.0',
  'node-inspector': '0.8.3',
  nodeunit: '0.9.0',
  npm: '2.5.1',
  'npm-check-updates': '1.5.1',
  'sequelize-cli': '1.2.0',
  ssmount: '0.5.1',
  'uglify-js': '2.4.16' }
bower
codepainter
coffee-script
express-generator
undefined
/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:90
            var unconstrainedCurrentVersion = currentVersion.substr(getVersion
                                                            ^
TypeError: Cannot read property 'substr' of undefined
    at Object.upgradeDependencies (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:90:61)
    at /usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:30:39
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:288:9
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:272:13
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:253:9
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/view.js:146:28
```
This seems related to the undefined there.

So there are 2 things we could solve.
A) Find out why there is an undefined in there.
B) Make the script output at least a reasonable error/warning if it comes across something like this.

**Comment by dantman** [comment]
I did a bit more digging and this has something to do with groc (which I don't remember when I installed or what I did to it). But `npm.commands.list`'s dependencies contains `groc: '*'` and `/usr/local/lib/node_modules/groc/` contains nothing but an empty `node_modules/jade/`.

**Comment by dantman** [comment]
Personally using npm to `rm -g` then `i -g` groc fixes this. I'm not sure why it's like that, though it's possible that I removed it when I was switching from using `sudo npm` to just `npm` and permissions were off leading to a partial removal (wild theory).

But since it's possible for npm to give that kind of output I think getInstalledPackages should skip over any `results.dependencies[*]` value that isn't an object and just print a quick warning that the module may be corrupt.

**Comment by metaraine** [comment]
Thanks for the in-depth debugging! I wish I knew why it was returning undefined there. I'd like to get to the root of the problem. I found some code in [getLatestVersions](https://github.com/tjunnone/npm-check-updates/blob/9af2579d37724150f00156a2129dd8fc2e377e03/lib/versionmanager.js#L279-L282) that could have potentially been returning empty objects for packages with npm errors. I [updated it](https://github.com/tjunnone/npm-check-updates/blob/master/lib/versionmanager.js#L309) but we really won't know unless we find a way to reproduce this issue.

Thanks!

**Comment by dantman** [comment]
Did you miss my last two comments?

The code you want to fix is in [getInstalledPackages](https://github.com/tjunnone/npm-check-updates/blob/master/lib/versionmanager.js#L227-L229). `packageList[package]` can sometimes be `"*"` if there is something wrong with the module (like my directory containing an empty directory).

**Comment by metaraine** [comment]
Thanks, I hadn't looked at getInstalledPackages, but now that I have it makes sense. I will patch it to ignore those that return "*".
