### ISSUE TITLE
Implement --interactive flag to ask each dependency "do you want to upgrade?"

### ISSUE THREAD

**Issue by mkungla** [tjunnone/npm-check-updates#502]
Ref #95, why could not these be merged https://github.com/th0r/npm-upgrade

- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version:  *
* npm version: *
* npm-check-updates version: *

---------------------------

**Comment by raineorshine** [comment]
That would be a great addition! I'm happy to review a PR for this.
