### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by mikerogerz** [tjunnone/npm-check-updates#504]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.15.3
* npm version: 6.9.0
* npm-check-updates version: 3.0.8

---------------------------

Unhandled rejection TypeError: Cannot read property 'latest' of undefined
    at packageJson.then.result (/home/mrogers/.npm-packages/lib/node_modules/npm-check-updates/lib/package-managers/npm.js:36:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mikerogerz** [comment]
https://pastebin.com/1CVTFAdX

**Comment by stoically** [comment]
The dependency [`selectizebootstrap`](https://registry.npmjs.org/selectizebootstrap) got unpublished and in this case the registry returns a result which doesn't include `dist-tags`. Fixed in #508.

**Comment by stoically** [comment]
Just realized that `selectizebootstrap` is a github dependency. We shouldn't check for new versions on npm if the current version isn't a valid semver range - modified #508 accordingly.

**Comment by mikerogerz** [comment]
Appreciate the quick fix, thanks a lot.
