### ISSUE TITLE
Hard to distinguish between breaking and non-breaking changes in v3

### ISSUE THREAD

**Issue by kachkaev** [tjunnone/npm-check-updates#512]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.15.2
* npm version: v6.4.1
* npm-check-updates version: 3.0.11

---------------------------

👋

Before v3, the output of `ncu` was split into two sections. The first one was containing breaking changes and the second one included minor bumps and patches. Now, possibly due to the removal of option `-a`, the list is merged into one.

This change makes it difficult to see which version bumps are breaking and which are not, and it'd be great if this could be improved a bit. The solution can be pretty simple: if the version has changed from `A.×.×` to `B.×.×` or from `0.A.×` to `0.B.×`, it could be simply coloured with yellow instead of green. Additionally, pinned versions could be also highlighted with some other colour to bring attention. If something has been pinned in package.json, the could have been a good reason for it.

WDYT?

**Comment by raineorshine** [comment]
> Before v3, the output of ncu was split into two sections. The first one was containing breaking changes and the second one included minor bumps and patches.

Actually, the first section in v2 contained versions that were not satisfied by the declared version ranges and the second section contained versions that were behind but satisfied by the declared version ranges (e.g. v1.0.1 satisfied by "^1.0.0"). Confusing!

v3 simplifies this by applying the former `-a` by default.

`ncu` does color code the version numbers, but I agree all green is not very clear. I don't think it would be hard to use red, yellow, and green to indicate different levels of risk.

**Comment by raineorshine** [comment]
Published in v3.1.0. I used red, cyan, and green for contrast.
