### ISSUE TITLE
ncu colors

### ISSUE THREAD

**Issue by blondie63** [tjunnone/npm-check-updates#518]
- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.15.3
* npm version: 6.9.0
* npm-check-updates version: 3.1.0

---------------------------
ncu display available updated using some colors, is there a color legend?
for example:
 core-js                             2.6.5  →      3.0.0 
 @angular/compiler                  ~7.2.9  →    ~7.2.10 
 @angular/compiler-cli              ~7.2.9  →    ~7.2.10 
 @angular/language-service          ~7.2.9  →    ~7.2.10 
 typescript                         ~3.2.4  →  ~3.3.4000 

core-js 3.0.0 is red colored, what means ?

**Comment by raineorshine** [comment]
Major upgrades are in red because they include breaking changes.

Red = major upgrade
Cyan = minor upgrade
Green = patch upgrade

I updated the README with a legend and a new screenshot. Thanks!
