### ISSUE TITLE
Exit code when accessing a private registry with invalid credentials

### ISSUE THREAD

**Issue by trippingtarballs** [tjunnone/npm-check-updates#527]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.15.3
* npm version: 6.4.1
* npm-check-updates version: 3.1.3

---------------------------

Shouldn't the exit code of a failed run of `ncu` be non-zero?

For example ...

```bash
$ npx -p npm-check-updates -- ncu --error-level 2

npx: installed 154 in 6.922s
Checking ~/my-project/package.json
[=====---------------] 9/37 24%(node:38811) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at EventEmitter.emitter.on (~/.npm/_npx/38800/lib/node_modules/npm-check-updates/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[==================--] 34/37 91%%

$ echo $?
0
```

In the above example the `HTTPError: Response code 401 (Unauthorized)` is correct. Similar to issue #519 I am using a private registry where authentication is required. However, in my scenario, I have **accidentally forgotten to setup authentication** for my private registry on my CI server and I get **an exit code of `0`**. Thus, the CI server passes 😕 Is this expected behaviour? 🤔

**Comment by raineorshine** [comment]
Fixed and published in `v3.1.4`. Thanks!

**Comment by bdovaz** [comment]
@raineorshine just happened to me so either there is a regression or I don't know....

**Comment by raineorshine** [comment]
That sounds like a different error, or at least a different cause. The previous fix handles all unhandled promise rejections. So if you're still experiencing this issue it must be from something other than an unhandled promise rejection. Feel free to open a new issue with steps to reproduce and the error message.
