### ISSUE TITLE
Highlighting possible breaking changes for packages before they reach v1.0.0

### ISSUE THREAD

**Issue by kachkaev** [tjunnone/npm-check-updates#529]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.15.2
* npm version: 6.4.1
* npm-check-updates version: 3.1.4

---------------------------

👋 Since https://github.com/tjunnone/npm-check-updates/issues/512 and 3.1.0, ncu colour-codes different version changes, which is great.  Green for patches, cyan for feature releases and read for major version bumps (breaking changes). This works great, there's just one small caveat. Before a package has reached v1.0.0, every bump in its second number _can_ be a breaking change by convention. This is not necessary though. The way these bumps are printed now makes them indistinguishable from usual minor version bumps, so a breaking change can go unnoticed. Here's an example:

<img width="413" alt="Screenshot 2019-04-04 at 08 23 30" src="https://user-images.githubusercontent.com/608862/55647182-ec42e100-57d4-11e9-9332-8ce137575075.png">

How about showing bumps in second numbers as red or orange if the first number is less than 1?

**Comment by raineorshine** [comment]
Thank you for reporting, and for the clear explanation! Couldn't agree more. Fixed and published in `v3.1.5`.
