### ISSUE TITLE
Exception on busy linux socket.

### ISSUE THREAD

**Issue by merbst** [tjunnone/npm-check-updates#532]
/usr/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:387                           throw err;                                                 ^                                                                                                             RequestError: getaddrinfo EBUSY registry.npmjs.org registry.npmjs.org:443                                                 at ClientRequest.request.once.error (/usr/lib/node_modules/npm-check-updates/node_modules/got/source/request-as-event-emitter.js:178:14)                                         at Object.onceWrapper (events.js:281:20)                   at ClientRequest.emit (events.js:198:15)                   at ClientRequest.origin.emit.args (/usr/lib/node_modules/npm-check-updates/node_modules/@szmarczak/http-timer/source/index.js:37:11)                                             at TLSSocket.socketErrorListener (_http_client.js:397:9)                                                              at TLSSocket.emit (events.js:193:13)                       at emitErrorNT (internal/streams/destroy.js:91:8)          at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)                                                             at processTicksAndRejections (internal/process/task_queues.js:81:17)

On Linux Kernel 4.20 something, after starting "ncu -u &" in the background of one too many directories containing a package.json file.
If it helps to diagnose this (stupid) use-case (I have since rewritten this script as a "parallel" command to be more nettiquette friendly), see the shell function that triggered it:
upall_ncu ()                                               {                                                              for D in ./*/;                                       do                                                             {                                                              if test -f "${D}"package.json; then                            pushd "$D";                                                ncu -u & popd;                                         fi                                                     };                                                     done                                                   }

- [*] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [*] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v11.14.0
* npm version: 6.9.0
* npm-check-updates version: 
3.1.7
---------------------------

**Comment by raineorshine** [comment]
Thanks! Perhaps this will be helpful to others.
