### ISSUE TITLE
ncu never finishes with proxy settings

### ISSUE THREAD

**Issue by bman61** [tjunnone/npm-check-updates#537]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.15.3
* npm version: 6.9.0
* npm-check-updates version: 3.1.1

---------------------------
ncu -g enumerates the installed packages correctly and then starts to fetch latest versions.  It gets stuck on 0/xx which for me is 0/24. That is, it never finishes the first one.

ncu version 3.1.1 works fine. all ncu versions after 3.1.1 hang

**Comment by stoically** [comment]
After 3.1.0 proxy support got added, which might be the cause for this. Could you check if you have a proxy in [your env or npmrc](https://github.com/kevva/get-proxy/blob/0f305bcc25fb7694d8ad1be902c1ab007ffda0cb/index.js#L5-L11)?

**Comment by bman61** [comment]
I updated the version info- it's breaking between 3.1.1 and later. v3.1.2 added the proxy features (get-proxy and https-proxy-agent).  My proxy settings are in .npmrc

**Comment by stoically** [comment]
Could you share your proxy settings? And does npm itself work with those proxy settings (like npm install)?

**Comment by bman61** [comment]
npm works fine with my proxy settings

**Comment by stoically** [comment]
Does ncu -g work if you remove the proxy settings?

And without information on how your proxy settings look, I'm unfortunately unable to help.

**Comment by bman61** [comment]
my proxy settings for http and https are the same. they do not include a username/password. only the url to the internal proxy server    http://proxy.nmq.com:4239

ncu -g v3.1.2 works if I remove the npm proxies but then npm cannot install packages e.g. npm i -g npm-check-updates@3.1.8  gets stuck

**Comment by stoically** [comment]
Well, that's interesting. Since ncu and npm use `registry.npm.com` by default, it shouldn't work for both if the proxy is removed.

To debug that it'd need a more involved approach. Specifically, in `make-fetch-happen` a `console.log(popts);` [here](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L152). Then execute e.g. `npm i -g npm-check-updates` with proxy set.

Then compare that to the object passed to `ProxyAgent` in ncu [here](https://github.com/tjunnone/npm-check-updates/blob/9650e7918bf5551dddb3e1cc4efa21c1f22010a6/lib/package-managers/npm-proxy.js#L43).

(Both in the global npm node_modules)

**Comment by bman61** [comment]
make-fetch-happen:
{
  host: 'proxy.nmq.com',
  port: '4239',
  protocol: 'http:',
  path: '/',
  auth: null,
  ca: null,
  cert: null,
  key: null,
  timeout: NaN,
  localAddress: undefined,
  maxSockets: 50,
  rejectUnauthorized: false 
}

proxy passed into ProxyAgent:
{
  href: 'http://proxy.nmq.com:4239/',
  origin: 'http://proxy.nmq.com:4239',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'proxy.nmq.com:4239',
  hostname: 'proxy.nmq.com',
  port: '4239',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' 
}

**Comment by stoically** [comment]
Thanks. But I'd need to see the object passed into `ProxyAgent`, not the `proxy` const.

**Comment by bman61** [comment]
sorry about that. ProxyAgent object is:
```
{
  host: 'proxy.nmq.com',
  port: '4239',
  auth: '',
  secureProxy: false,
  keepAlive: true,
  maxSockets: 50,
  ca: null,
  key: null,
  cert: null,
  rejectUnauthorized: false 
}
```

**Comment by stoically** [comment]
No worries - and thanks. So, the only thing that seems to be different is that ncu doesn't explicitly pass in the `protocol`. I was under the impression that `secureProxy: false` switches it to `http:`, but maybe I was wrong. Could you try `npx npm-check-updates@stoically/npm-check-updates#proxy-protocol -g` and see if it works?

**Comment by stoically** [comment]
I peeked into the code of the `ProxyAgent`, and it actually decides whether to use a `secureProxy`, which means connecting with `tls.connect`, based on the `protocol` - but if the `protocol` is not included, as in your case, it defaults to `net.connect`. So, yeah, my only explanation is that your proxy doesn't support the method used by [`https-proxy-agent`](https://github.com/TooTallNate/node-https-proxy-agent), which is [`CONNECT HTTP`](http://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_Tunneling) - do you by chance can ask the sysops whether that's the case?

**Comment by stoically** [comment]
The other difference seems to be, that npm is using `http-proxy-agent` for http proxies (though, http- and https-proxy-agent seem to do exactly the same thing). So you could try `npx npm-check-updates@stoically/npm-check-updates#http-proxy-agent` too, and see if that helps.

**Comment by stoically** [comment]
Well, in this case the proxy shouldn't be used to connect to your npm registry, correct? How did you configure npm to not use the proxy for connecting to the registry?

**Comment by k7sleeper** [comment]
> Well, in this case the proxy shouldn't be used to connect to your npm registry, correct?

Yes

> How did you configure npm to not use the proxy for connecting to the registry?

Omit the configuration values
```
proxy=http://proxy.materna.de:8080/
https-proxy=http://proxy.materna.de:8080/
```
in `.npmrc`.

**Comment by k7sleeper** [comment]
> Environment variables?

Yes

**Comment by stoically** [comment]
In this case npm should use the proxy too. Which environment variables did you configure exactly for the proxy? And is `NO_PROXY` (or `no_proxy`) environment variable set?

**Comment by k7sleeper** [comment]
> And is NO_PROXY (or no_proxy) environment variable set?

Yes

**Comment by stoically** [comment]
That's interesting. npm simply [checks all levels of the registry and no_proxy hostname against eachother](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L72-L88), and only if all levels match it doesn't use a proxy. Meaning that having a registry set to `http://registry.example.com` and `NO_PROXY` set to `example.com` should still use the proxy. Can you add your exact npm registry hostname to the `NO_PROXY` env see if ncu works with that?

To understand why npm doesn't use a proxy in this case, I'd need information how/where you configured the npm registry and what's the url it uses and which environment variables you used to configure the proxy itself?

**Comment by k7sleeper** [comment]
> Can you add your exact npm registry hostname to the NO_PROXY env see if ncu works with that?

If I add the exact hostname to the NO_PROXY list the newest version of NCU works, too. That's it.

**Comment by k7sleeper** [comment]
Just for information: `ncu` still does not behave the same as `npm´ regarding proxy support.

**Comment by raineorshine** [comment]
I wonder if this suggestion would help externalize the proxy logic from npm-check-updates:

> For Node.js v12 and above you can use https://github.com/gajus/global-agent.
> 
> For older version of Node.js you can use https://www.npmjs.com/package/global-tunnel-ng.

– https://github.com/nodejs/node/issues/8381#issuecomment-486717645

**Comment by stoically** [comment]
Both packages would still need logic in ncu to determine when to use a proxy. Without the exact information from @k7sleeper as requested in my last comment, we have little chance of getting that logic right.

**Comment by raineorshine** [comment]
@stoically Fair point. I'm keeping an eye on https://github.com/dylang/npm-check/issues/106 as well.

**Comment by k7sleeper** [comment]
My `.npmrc` contains the line
```
registry = "https://artifact.mycompany.de/nexus/repository/npm_cache/"
```
and my environment contains
```
HTTP-PROXY=http://proxy.mycompany.de:8080
HTTPS-PROXY=http://proxy.mycompany.de:8080
HTTPS_PROXY=http://proxy.mycompany.de:8080
HTTP_PROXY=http://proxy.mycompany.de:8080
NO_PROXY=mycompany.de
```
Using these settings `ncu@3.1.1` works and all later versions *not*. 

`ncu@>3.1.1` only works if I add `artifact.mycompany.de` to `NO_PROXY`:
```
HTTP-PROXY=http://proxy.mycompany.de:8080
HTTPS-PROXY=http://proxy.mycompany.de:8080
HTTPS_PROXY=http://proxy.mycompany.de:8080
HTTP_PROXY=http://proxy.mycompany.de:8080
NO_PROXY=mycompany.de,artifact.mycompany.de
```
which is not a long-term solution for me.

**Comment by stoically** [comment]
Thanks. So after looking at [the code in npm](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L72-L88) again and comparing it to your configuration, I realized that npm checks all levels of the no_proxy env, after splitting by `.`, against the a given uri (the registry url). Which means, that `de` and `mycompany` are compared - nothing more - and they both match. This seems contradictory to other no_proxy implementations out there, which require `*.mycompany.de` or `.mycompany.de` to make it a wildcard. But since we're in the npm world, it makes sense to adjust, I guess.

**Comment by k7sleeper** [comment]
> This seems contradictory to other no_proxy implementations out there

Really? My `NO_PROXY`settings is not NPM specific but works with all other programs.

**Comment by stoically** [comment]
Good to know. I've only checked some Linux commandline tools (and their docs), which work as mentioned.

Personally I think it makes sense to explicitly define the wildcard, because otherwise you have no chance of allowing *only* a specific domain, but have to *always* allow subdomains of it.
