### ISSUE TITLE
ncu -g doesn't work on Windows Scoop

### ISSUE THREAD

**Issue by acmilank22** [tjunnone/npm-check-updates#541]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.4.0 (installed by [Scoop](https://github.com/lukesampson/scoop): ```scoop install nodejs```) 
* npm version: 6.9.0
* npm-check-updates version: 3.1.10

---------------------------

```shell
ncu -g
```

out put
```shell
No dependencies.
```

**Comment by raineorshine** [comment]
I would probably report to Scoop. If npm-check-updates works in PowerShell and not in Scoop, then this is a Scoop issue.
