### ISSUE TITLE
ncu fails to parse response from artifactory

### ISSUE THREAD

**Issue by callmemagnus** [tjunnone/npm-check-updates#544]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8 and 10
* npm version: 5.6.0
* npm-check-updates version: 3.1.2 -> 3.1.11
---------------------------

I'm using artifactory as a NPM registry (corporate environment) and I cannot access npm's registry.

Since version 3.1.2, `ncu` fails to return result and crashes with different errors.
On the latest version (3.1.11) I'm getting (copied by hand, sorry):

```
$ ncu
RequestError: Parse Error
   at ClientRequest.request.once.error
```

I can't look into your code right now, I'll do it the evening. But it seems that the way to retrieve data from the registry has changed and that Artifactory does not support it.

Is my assumption correct?

**Comment by stoically** [comment]
In 3.1.2 proxy support was added, so that might be related. Would you mind checking/sharing your proxy settings, like `registry` in `.npmrc`, `HTTP(S)_PROXY` and `NO_PROXY` env vars?

**Comment by callmemagnus** [comment]
hi, thanks for the fast response.
yes I had a proxy configured, I removed it and it works.

I thought that it would only use the proxy if the registry was the default... Bad assumption on my side.

I guess this is solved although I probably would have expect a nicer error message.

Thanks!

**Comment by stoically** [comment]
Glad it works for you.

Yeah, we could probably try/catch the call to package-json and log something human-readable if it fails, including whether a proxy was used.

Feel free to close the issue.
