### ISSUE TITLE
Semver wrongly interpreted

### ISSUE THREAD

**Issue by Blanen** [tjunnone/npm-check-updates#545]
> npm-check-updates maintains your existing semantic versioning policies, i.e., it will upgrade "express": "^4.0.0" to "express": "^5.0.0".

Why? ^4.0.0 means 4.x.x. 
It EXPLICITLY shouldn't do this.
What does 'maintains' mean here? Because it clearly doesn't follow semver convention.
> The tilde ~ matches the most recent patch version (the third number) for the specified minor version (the second number).
> ~1.2.3 will match all 1.2.x versions but will hold off on 1.3.0.
> 
> The caret ^ is more relaxed. It matches the most recent minor version (the second number) for the specified major version (the first number).
> ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.

**Comment by stoically** [comment]
See https://github.com/tjunnone/npm-check-updates/issues/540#issuecomment-494125271

**Comment by Blanen** [comment]
@stoically 
Ok closed...

**Comment by stoically** [comment]
> What does 'maintains' mean here?

It means, it keeps the semver flag, `^` in this case.
