### ISSUE TITLE
v3.1.12 no longer works with private registries

### ISSUE THREAD

**Issue by sbmw** [tjunnone/npm-check-updates#547]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.16.0
* npm version: 6.9.0
* npm-check-updates version: 3.1.12

---------------------------

Running ncu no longer finds updates for private registries.  I.e. added with:

npm login --registry=https://myregistry.com/ --scope=@mynamespace --always-auth

And included in package.json with:

"dependencies": {
        "@mynamespace/my-component": "^1.0.0"
}

I have confirmed that:

- The issue was introduced in v3.1.12
- The issue only affects private registries

I haven't confirmed if the @namespacing is relevant.

Hope this helps!

**Comment by sbmw** [comment]
I suppose it's because pacote doesn't look at .npmrc?

https://github.com/zkat/pacote/issues/156

**Comment by tdukai** [comment]
I am seeing the very same issue!

**Comment by stoically** [comment]
Thanks for the report and linking the relevant issue. Could you try if `npx npm-check-updates@stoically/npm-check-updates#libnpmconfig` works?

**Comment by sbmw** [comment]
Hi @stoically - yep, you got it! That works :)
