### ISSUE TITLE
ncu -g is not reading the correct package version

### ISSUE THREAD

**Issue by LuigiMaestrelli** [tjunnone/npm-check-updates#549]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.16.0
* npm version: 6.9.0
* npm-check-updates version: 3.1.12

---------------------------

Running ncu -g is returning a list of packages available to update.

![image](https://user-images.githubusercontent.com/5038871/60187465-03a5cf00-9804-11e9-82e8-ec726f34d1eb.png)

But the packages are already update.
If we look at some of the packages versions, they are already installed with the last version.

![image](https://user-images.githubusercontent.com/5038871/60187569-2e902300-9804-11e9-8a00-6a7f65fa16c6.png)

I even tried to remove and add one of the package and got the same result

**Comment by stoically** [comment]
Could you check e.g. `npm ls -g eslint` and see which version it shows?

**Comment by raineorshine** [comment]
You could also check to confirm that `which eslint` is in the same place as `npm config get prefix`

**Comment by LuigiMaestrelli** [comment]
> Could you check e.g. `npm ls -g eslint` and see which version it shows?

```
C:\Users\luigi.maestrelli>npm ls -g eslint
D:\Program Files\nodejs
`-- eslint@6.0.1
```


> You could also check to confirm that `which eslint` is in the same place as `npm config get prefix`

```
C:\Users\luigi.maestrelli>npm config get prefix
D:\Program Files\nodejs

```
I don't know if it is relevant, but I'm using nvm on Windows and I have 2 versions of node instaled.
```
C:\Users\luigi.maestrelli>nvm list
    12.4.0
  * 10.16.0 (Currently using 64-bit executable)
```

**Comment by stoically** [comment]
Not sure, but `D:\Program Files\nodejs` looks like a global node installation, not like nvm. So that might play a role.

`which eslint` is `where eslint` on windows. Might also want to check `eslint --version`.

**Comment by LuigiMaestrelli** [comment]
Sorry, there was two instalation folders.

```
D:\Program Files\nodejs\eslint
D:\Program Files\nodejs\eslint.cmd
C:\Users\luigi.maestrelli\AppData\Roaming\npm\eslint
C:\Users\luigi.maestrelli\AppData\Roaming\npm\eslint.cmd
```

Probaly one is from before nvm
