### ISSUE TITLE
ncu does not work behind a proxy

### ISSUE THREAD

**Issue by AxelTerizaki** [tjunnone/npm-check-updates#551]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.4.0
* npm version: 6.9.0
* npm-check-updates version: 3.1.12

---------------------------

Hello.

I've seen there were issues with proxies and checked them first, but couldn't find anything particularly relevant in my (simple) case.

When I run ncu 3.1.12, I get the following error :

```
d:\Apps\node\node_modules\npm-check-updates\lib\npm-check-updates.js:387
        throw err;
        ^
FetchError: request to https://registry.npmjs.org/got failed, reason: write EPROTO 11240:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at ClientRequest.<anonymous> (d:\Apps\node\node_modules\npm-check-updates\node_modules\node-fetchnpm\src\index.js:68:14)
    at ClientRequest.emit (events.js:200:13)
    at onerror (d:\Apps\node\node_modules\npm-check-updates\node_modules\agent-base\index.js:101:9)
    at callbackError (d:\Apps\node\node_modules\npm-check-updates\node_modules\agent-base\index.js:123:5)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  message: 'request to https://registry.npmjs.org/got failed, reason: write
 ' +
    'EPROTO 11240:error:1408F10B:SSL routines:ssl3_get_record:wrong '
+
    'version ' +
    'number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332:
\n',
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}
```

I'm behind a proxy when I use ncu and before upgrading to 3.1.12 I was running versions 2.x which worked fine and used npm settings for proxy use. I was able to run it and get the list of packages to update on my package.json just fine.

I tried 3.1.1 (before proxy support, from what I gathered when reading various issues here) and while it didn't throw any errors, for some reason it didn't display any package to update even though there were some reported by version 2.x of ncu.

My http and https proxies are the same, I'm using strict-ssl = false and the proxy and http-proxy config parameters in npm.

Thanks in advance for your help, tell me if you need more info.

**Comment by stoically** [comment]
According to https://stackoverflow.com/a/22673961 the reason might be that you're trying to connect over https to a proxy that doesn't support it.

proxy as precedence over http-proxy and if your proxy has no protocol defined, a protocol will inferred from the registry. ([see here](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L118-L127))

**Comment by emjaksa** [comment]
I am having the same issue. Downgraded to version 3.1.11

**Comment by stoically** [comment]
Ah, wait, https://github.com/tjunnone/npm-check-updates/issues/547 didn't get published yet, so proxy configurations from the `.npmrc` aren't respect at all currently.

**Comment by raineorshine** [comment]
Now published in `v3.1.13`

**Comment by AxelTerizaki** [comment]
I confirm it works fine now with 3.1.13. Closing :)

Thank you !

**Comment by CharlieAraya** [comment]
I'm having the same issue with versions 3.1.14+

**Comment by stoically** [comment]
3.1.14 introduced support for scoped registry-urls. How do your registry-url and (no)proxy npmrc/env configurations exactly look like?

**Comment by CharlieAraya** [comment]
Hi @stoically, this is the output:
http-proxy = "http://***.***.com:8080/"
https-proxy = "http://***.***.com:8080/"
proxy = "http://***.***.com:8080/"
registry = "https://registry.npmjs.org/"

I'm using windows and the system variables look the same.

**Comment by stoically** [comment]
Looks good to me. Maybe put a `console.log(npmConfig);` [here](https://github.com/tjunnone/npm-check-updates/blob/cd7e9c59eafda6d972c3c711fb91bd7e73717a1d/lib/package-managers/npm.js#L63) and check whether the proxy and registry configurations are what you expect them to be?

**Comment by CharlieAraya** [comment]
Looks good. 
The error I get is this:
C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check
-updates.js:387
        throw err;
        ^
FetchError: request to https://registry.npmjs.org/@aws-amplify%2fcli failed, rea
son: write EPROTO 3176:error:1408F10B:SSL routines:ssl3_get_record:wrong version
 number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:252

**Comment by stoically** [comment]
`http-proxy` is a non-existent npm config, there's only `proxy` and `https-proxy`. npm-registry-fetch prefers [https-proxy over proxy](https://github.com/npm/npm-registry-fetch/blob/fc0e119773651c598159679b9b2cbd8d052cdf0d/index.js#L93). make-fetch-happen [falls back to env](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L118-L127) vars if no proxy is set. So are you sure you didn't accidentally configure https-proxy to a https url, which might [not be supported](https://github.com/tjunnone/npm-check-updates/issues/551#issuecomment-507187959) by your proxy? Though, if that'd the case, npm itself should give you the same error, so I'm not exactly sure what's going on.

**Comment by CharlieAraya** [comment]
I tried to set the proxy variable and no change. I will just let it go and keep using 3.1.13, the proxy situation at work is really bad, so maybe it's  just my work's annoying proxy messing around...

**Comment by stoically** [comment]
Well, if it works in an earlier version, it probably isn't your proxy. If you want to give it another look, you could put a `console.log(proxy)` [here](https://github.com/zkat/make-fetch-happen/blob/b323d020314b09fefcf7e406bb79f68b3a8466f0/agent.js#L38) for working and not working versions and compare the results.
