### ISSUE TITLE
Added 255 packages when upgraded from 3.1.13 -> 3.1.14

### ISSUE THREAD

**Issue by mlc-mlapis** [tjunnone/npm-check-updates#558]
It looks really strange that 255 packages from 255 contributors were added when upgrading from the previous version 3.1.13. It was installed as a global package before and now also.

---------------------------

* node version: 11.13.0
* npm version: 6.7.0
* npm-check-updates version: 3.1.14
* Windows 10

**Comment by billyjanitsch** [comment]
I think this is because `snyk` was accidentally moved from dev dependencies to dependencies in https://github.com/tjunnone/npm-check-updates/commit/689b8dc557dd181e6dbbab38e6d6802b9d59de6c (cc @raineorshine) 🙂

**Comment by raineorshine** [comment]
Yes, it was the result of the [snyk patch](https://github.com/tjunnone/npm-check-updates/commit/689b8dc557dd181e6dbbab38e6d6802b9d59de6c). Snyk did that automatically as part of its preinstall protect hook. I don't really like the results.

Reverted and published in `v3.1.15`. Thanks for bringing this to my attention!

**Comment by billyjanitsch** [comment]
Thank you @raineorshine!
