### ISSUE TITLE
3.1.14 broke authentication with Artifactory using .npmrc with auth key

### ISSUE THREAD

**Issue by IdanAdar** [tjunnone/npm-check-updates#559]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.13
* npm version: 6.9.0
* npm-check-updates version: 3.1.14

---------------------------

@raineorshine 
It seems that starting with release 3.1.14, it is no longer possible for npm-check-updates to authenticate with Artifactory using an .npmrc that uses an auth key. I had to revert to 3.1.13 in order to succeed.

Such an .npmrc file will for example look like this:

```
registry=https://***com:443/artifactory/api/npm/***-virtual/
//***.com:443/artifactory/api/npm/***-virtual/:_password=<api key / token here>
//***:443/artifactory/api/npm/***-virtual/:username=***@***.com
//***.com:443/artifactory/api/npm/***-virtual/:email=***@***.com
//***.com:443/artifactory/api/npm/***-virtual/:always-auth=true
```

**Comment by stoically** [comment]
Please see https://github.com/tjunnone/npm-check-updates/issues/556#issuecomment-509023354
