### ISSUE TITLE
Ignore pinned versions

### ISSUE THREAD

**Issue by shiftgeist** [tjunnone/npm-check-updates#562]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.4.0
* npm version: 6.10.0
* npm-check-updates version: 3.1.17

---------------------------

First of all: Big props!

Second here is an example of an `ncu` output:
```
 core-js                      ^2.6.9  →   ^3.1.4 
 tslib                        ^1.9.0  →  ^1.10.0 
 karma-jasmine                ~1.1.2  →   ~2.0.1 
 karma-jasmine-html-reporter  ^0.2.2  →   ^1.4.2 
 protractor                    5.4.0  →    6.0.0 
 ts-node                      ~7.0.0  →   ~8.3.0 
 typescript                    3.4.1  →    3.5.3 
```
Suggests the update of typescript and protractor.

It would be helpful to ignore pinned packages (no ~ or ^).

Is this intentional and is there another way to to this?

**Comment by stoically** [comment]
Please see https://github.com/tjunnone/npm-check-updates/issues/540#issuecomment-494125271

You could use the ncu `-x` option.

**Comment by shiftgeist** [comment]
Thanks!

**Comment by Primajin** [comment]
Unearthing this old thread here - wouldn't it be beneficial to have an option to ignore pinned versions automatically?
I would like to avoid running ncu then look at all the versions make a note on the pinned ones and then run ncu again with excluding the pinned versions one by one manually.
I guess going the other way round and filtering for regex "starts with ~ or ^" won't work either since the filter only checks the name afterwards, right?

**Comment by raineorshine** [comment]
> I guess going the other way round and filtering for regex "starts with ~ or ^" won't work either since the filter only checks the name afterwards, right?

I think it would be reasonable to have an equivalent of `filter` and `reject` that works on the version, say `filter-version` and `reject-version`. Would that work for you?

**Comment by Primajin** [comment]
Thanks @raineorshine for considering! Hmm, how would that work? With version numbers or semver indicators?

**Comment by raineorshine** [comment]
Regex on the entire dependency value as listed in your package.json, i.e. "^6.0.0"

**Comment by Primajin** [comment]
Ahh sweet so then I would say `filter-version` regex starts with `^` or `~` to ultimately get everything but pinned versions 👍

**Comment by raineorshine** [comment]
Published in `v10.2.0`. Try it out!

```sh
ncu --filterVersion "/^[~^]/"
```

This includes less than, greater than, exact ranges, and `.x`:

```sh
ncu --filterVersion "/^[~^<>]| - |\.x$/"
```

**Comment by Primajin** [comment]
This is incredible. Thank you so much for this amazing fast feature implementation! ❤️🚀

**Comment by Primajin** [comment]
Works perfectly!

**Comment by davejog** [comment]
hey there

so, how would you use filterVersion for say ALL versions that are lower than 700.x.x ?

**Comment by raineorshine** [comment]
Do you want to filter on the the version listed in your package.json, or the latest version?

> `filterResults` runs after new versions are fetched, in contrast to `filter`, `reject`, `filterVersion`, and `rejectVersion`, which run before. This allows you to filter out upgrades with `filterResults` based on how the version has changed (e.g. a major version change).

**Comment by davejog** [comment]
let's assume that I want to filter out new versions are fetched which are 700.x.x and above

**Comment by raineorshine** [comment]
You would use `filterResults` to filter on the fetched version. You can use a regex that only matches versions that start with `6\d\d\.` (assuming you're on v6). 

For a different approach, you might consider using a custom `target` function that changes the strategy from `latest` to `minor` for that particular dependency. That leaves the logic up to npm-check-updates but ensures the dependency does not update to the next major version.

**Comment by davejog** [comment]
can that be done in a way that rejects anything higher than 700.x? meaning all the below versions are legit (remember, we are talking about multiple packages, ranging from 0.x to 6.x)

**Comment by raineorshine** [comment]
Yes, something like `parseInt(currentSemver[0]?.major) < 700`.
