### ISSUE TITLE
`ncu -u` doesn't go from `"@angular/flex-layout": "^7.0.0-beta.23"` to `"@angular/flex-layout": "^8.0.0-beta.26"`

### ISSUE THREAD

**Issue by SamuelMarks** [tjunnone/npm-check-updates#571]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.16.1
* npm version: 6.10.2
* npm-check-updates version: 3.1.20

---------------------------

**Comment by raineorshine** [comment]
ncu ignores alpha, beta, and rc versions by default. A more intuitive behavior would be to include beta if the dependency is already using it. In the mean time, use `--pre 1` to include betas or `--greatest` to check against the highest version number available.

**Comment by Simek** [comment]
@raineorshine Am I correct in assuming that 1f7312a will also fix that issue?

**Comment by raineorshine** [comment]
@Simek Yes, thanks!
