### ISSUE TITLE
"UNMET PEER DEPENDENCY" is considered latest version

### ISSUE THREAD

**Issue by garyking** [tjunnone/npm-check-updates#572]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v10.16.0
* npm version: 6.10.3
* npm-check-updates version: 3.1.20

---------------------------

1. Install `eslint-plugin-unicorn@10` globally, which has a peer dependency of `eslint@6`. (`sudo npm i -g eslint-plugin-unicorn`)
2. Install `eslint@5` globally (yes, version 5).
3. Run `ncu -g`.

It will say all packages are updated, but `eslint`'s latest version is 6, not 5.

**Comment by raineorshine** [comment]
Good catch! Turns out the entry in `npm ls` lacks the `version` property it would normally have when it's an unmet peer dependency. The version is instead nested in `required.version`. I should be able to have it fall back to `required.version` if `version` is not specified!

**Comment by raineorshine** [comment]
Fixed in `v3.1.21`
