### ISSUE TITLE
Question: When choosing no should it say "All dependencies match the latest package versions :)"

### ISSUE THREAD

**Issue by Primajin** [tjunnone/npm-check-updates#575]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v12.9.1
* npm version: 6.11.3
* npm-check-updates version: 3.1.21

---------------------------

When running ncu and choosing `no` on all proposed updates, it reports "All dependencies match the latest package versions :)"

Is this intended or is it a bug?
Saying no means all dependencies match the _desired_ versions yes but not the _latest_, as there are obviously newer versions reported. 🤔 

![Screenshot 2019-09-05 at 11 24 33](https://user-images.githubusercontent.com/1742115/64330165-c3678780-cfd0-11e9-8872-234dfe078afc.png)

What do you think?

**Comment by raineorshine** [comment]
Yes, I agree. The message should change to make more sense when some/all dependencies are filtered out or declined.
