### ISSUE TITLE
ncu -g no longer lists the items that can be upgraded

### ISSUE THREAD

**Issue by fmorriso** [tjunnone/npm-check-updates#580]
- [ ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version:  10.16.0
* npm version:  6.11.3
* npm-check-updates version:  3.1.22

---------------------------
As of npm-check-updates 3.1.22, running `ncu -g` no longer lists the available globally installed packages that can be upgraded.   Running `ncu` in a directory that has a `package.json` in it still works, so it appears that this is a regression bug that occurs only when the `-g` option is specified.  The old version, 3.1.21, worked correctly.

**Comment by MartinManev** [comment]
I just noticed I'm no longer getting the following message when I run `ncu -g`:
```
All dependencies match the latest package versions :)
```
It might be related.

**Comment by raineorshine** [comment]
Fixed in `v3.1.23`
