### ISSUE TITLE
Ignore dependencies like git+ssh://git@bitbucket.org:org/project

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#59]
When you've got an url like `"project": "git+ssh://git@bitbucket.org:org/project"` (yes, it's private), it returns `Unable to determine updates for "xxx": Error: 404 Not Found: xxx`

It should be ignored by npm-check-updates, no?

**Comment by metaraine** [comment]
Thanks, definitely!

**Comment by kud** [comment]
;)

**Comment by metaraine** [comment]
See #12

**Comment by kud** [comment]
Wonderful; thanks!
