### ISSUE TITLE
Simple quote regex doesn't work on Windows

### ISSUE THREAD

**Issue by acailly** [tjunnone/npm-check-updates#591]
On Windows, this command does not return updates:

```
npx npm-check-updates '/storybook/'
```

... whereas this command does return the correct updates:

```
npx npm-check-updates "/storybook/"
```

If double quotes works correctly on Linux, maybe the documentation should use them.

If not, a "tips for windows" would be great 😃 

In every case, a lost developper now can find this issue and understand the problem comes from quotes 😉

**Comment by raineorshine** [comment]
Good catch!

Does `ncu "/^(?!storybook).*/"` work on Windows? I have to use single quotes in Bash because double quotes break.

From README:

> match packages that do not start with "gulp-". Note: single quotes are required
> here to avoid inadvertent bash parsing
> $ ncu '/^(?!gulp-).*$/'

**Comment by acailly** [comment]
yes, running `ncu "/^(?!@storybook).*/"` exclude all dependencies starting with `@storybook` if that's  your question

**Comment by raineorshine** [comment]
So...

Windows: `A && !B`
Linux: `!A && B`

Very well, I shall update the README! :)
