### ISSUE TITLE
Vulnerability Warning

### ISSUE THREAD

**Issue by FlyRocketDrones** [tjunnone/npm-check-updates#593]
- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

node: v10.16.2
npm : 6.12.0
npm-check-updates: 3.1.24

---------------------------

Currently, I am getting the below vulnerability warning on npm-check-updates. Is there a way I can fix it? or need to wait for an update?

Error
`=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Machine-In-The-Middle

  Package         https-proxy-agent

  Patched in      >=3.0.0

  Dependency of   npm-check-updates

  Path            npm-check-updates > pacote > make-fetch-happen >
                  https-proxy-agent

  More info       https://npmjs.com/advisories/1184

  High            Machine-In-The-Middle

  Package         https-proxy-agent

  Patched in      >=3.0.0

  Dependency of   npm-check-updates

  Path            npm-check-updates > pacote > npm-registry-fetch >
                  make-fetch-happen > https-proxy-agent

  More info       https://npmjs.com/advisories/1184

found 2 high severity vulnerabilities in 908324 scanned packages
  2 vulnerabilities require manual review. See the full report for details.`

**Comment by raineorshine** [comment]
Thanks for reporting! Both of these vulnerabilities are in _[pacote](https://github.com/npm/pacote)._ You should file an issue there.
