### ISSUE TITLE
Could be great to list packages instead of using regex

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#60]
like `pm-check-updates -f masonry-layout gulp-concat gulp-filter gulp-minify-css gulp-svgmin gulp-replace lodash -u`

**Comment by metaraine** [comment]
Works almost as suggested:

`npm-check-updates -f "masonry-layout gulp-concat gulp-filter"`
`npm-check-updates -f masonry-layout,gulp-concat,gulp-filter`

**Comment by kud** [comment]
:+1: thanks
