### ISSUE TITLE
Execution Policies issue after upgrading to v3.2.0

### ISSUE THREAD

**Issue by Hlsgs** [tjunnone/npm-check-updates#605]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.13.0 LTS
* npm version: 6.12.1
* npm-check-updates version: 3.2.0

---------------------------

Windows 10 x64: After upgrading to the latest v3.2.0, I get:
```
ncu : File C:\Users\ZZZ\AppData\Roaming\npm\ncu.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ncu -u
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
I didn't mess with any Execution policy stuff and never encountered anything related while using `npm-check-updates`.
Downgrading to al earlier version of `npm-check-updates` does not help.

**Comment by Hlsgs** [comment]
It would seem that my exectution policies somehow got reset, and I do not think it has anything to do with `npm-check-updates`. Closing.

**Comment by Jack-Barry** [comment]
I hadn't changed any policies on my machine, but I got around this by just running it in a plain `cmd.exe` prompt

**Comment by Hlsgs** [comment]
@Jack-Barry run `Get-ExecutionPolicy -list` in PowerShell to check if `CurrentUser` is set to `RemoteSigned`. If it's not, it means Windows reset them(happens sometimes) and you need to set it to that.

**Comment by justrealmilk** [comment]
Thanks for the quick fix @Hlsgs
