### ISSUE TITLE
Change default command-line arguments to filter

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#61]
```console
$ npm-check-updates masonry-layout
masonry-layout is not a valid file or directory
```

**Comment by kud** [comment]
Sorry, missed the -f

**Comment by metaraine** [comment]
I'm considering changing this behavior in the next major version release.

Currently the default argument is a path to a package.json, which I'm not sure how many people use:
`npm-check-updates ../../package.json`

I could easily add that as an option, e.g. --package, but it strikes me as not the best candidate for the default argument.

Would it be more intuitive and helpful to specify the package filter as the default command line argument?
`npm-check-updates masonry-layout`

**Comment by kud** [comment]
Exactly. Agreed with that. ;)

**Comment by metaraine** [comment]
Thanks. I'll schedule this for 2.0.0 and keep this issue open if others have an opinion.

**Comment by kud** [comment]
Perfect.

**Comment by metaraine** [comment]
Haven't heard any complaints, so moving to command-line argument filter. (Old behavior can be achieved by piping alternative package.json to stdin.)
