### ISSUE TITLE
Syntax error in index.js file, unexpected token ...

### ISSUE THREAD

**Issue by SSaquif** [tjunnone/npm-check-updates#613]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.2.1
* npm version: 6.12.0
* npm-check-updates version: 3.2.1

---------------------------
Getting a syntax error in the index.js file while simply running ncu -g from terminal. Seems like it's because the first argument is being prefixed with a rest operator. Comes from the dependency find-up node module. Please check the attached screenshots.

Terminal:
![ncu_Issue](https://user-images.githubusercontent.com/9747452/68728341-0deb1e80-0595-11ea-8905-b842a0a29997.png)

Code snippet:
![ncu_Issue_Code](https://user-images.githubusercontent.com/9747452/68728461-68847a80-0595-11ea-8a6c-a179ae8f26d7.png)

**Comment by SSaquif** [comment]
Solved by updating node to latest version 13.1.0

**Comment by raineorshine** [comment]
Thanks for reporting! ncu is supposed to work on node >= 8, but perhaps that's no longer true with the `find-up` module (although if that's the case their `engines` field is wrong).
