### ISSUE TITLE
ncu -g  it told me no dependencies.

### ISSUE THREAD

**Issue by linpengteng** [tjunnone/npm-check-updates#616]
npm config get prefix
  E:\Nodejs\npm_global

but it reads `$ {process.env.AppData} \\ npm`

about npm.js
  return spawn(cmd, ['config', 'get', 'prefix']).then(prefix => {
        .....
       // I need that prefix
  })

* node version:  v12.13.1
* npm version:  6.12.1
* npm-check-updates version: 3.2.2
* process.platform: win32

**Comment by raineorshine** [comment]
Do any of the tips in #549 help?

Sometimes this can happen if there are multiple versions of npm installed.

**Comment by raineorshine** [comment]
Also see #293

**Comment by linpengteng** [comment]
resolved path issues with npm -g prefix xxx

**Comment by Iahiax** [comment]
npm -g prefix xxx
