### ISSUE TITLE
Feature request: only update non-git-url packages

### ISSUE THREAD

**Issue by fiznool** [tjunnone/npm-check-updates#62]
I have a situation in a fairly large app where most of my package versions are caret-style semver releases but a few are git urls, due to the fact that these packages have bugs fixed on my own fork but have not merged into the original npm module.

Abridged example:

```
"dependencies": {
    "async": "^0.9.0",
    "express": "^4.11.2",
    "freshbooks": "joewoodhouse/freshbooks.js#2d62fed5937cefd24bfd1f11c2bcd45af306ebed",
    "lodash": "^3.1.0",
    "passport": "^0.2.1",
    "passport-google-oauth": "fiznool/passport-google-oauth#9091ec3",
}
```

It would be great if I could run a command to update the `async`, `express`, `lodash` and `passport` versions whilst keeping `freshbooks` and `passport-google-oauth` at the same level.

**Comment by fiznool** [comment]
Apologies, I didn't realise this is the default behaviour. I guess the console output confused me a little bit:

```
"passport-google-oauth" can be updated from git+https://github.com/fiznool/passport-google-oauth#9091ec3 to git+https://github.com/fiznool/passport-google-oauth#0 (Installed: 0.2.0, Latest: 0.1.5)
```

**Comment by metaraine** [comment]
Yes, this message is confusing and has been removed in v2.0.0, currently available in the unstable tag:

`npm install npm-check-updates@unstable` (@v2.0.0-alpha.7)

Thanks!
