### ISSUE TITLE
[question] A valid range consider as invalid

### ISSUE THREAD

**Issue by Kikobeats** [tjunnone/npm-check-updates#623]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: `v12.14.1`
* npm version: `6.13.4`
* npm-check-updates version: `4.0.1`

---------------------------

<img width="737" alt="Screenshot 2020-01-16 at 21 56 53" src="https://user-images.githubusercontent.com/2096101/72562199-22a4a500-38ab-11ea-959f-e2c15bc4d11e.png">

Hello,

`ncu` is throwing an error because a dependency range version isn't satisfied, when `semver.npmjs.com` is saying to me the range is correct. 

<img width="1438" alt="Screenshot 2020-01-16 at 21 56 34" src="https://user-images.githubusercontent.com/2096101/72562175-14ef1f80-38ab-11ea-98a7-61604800e27e.png">

Any idea why this is happening?

**Comment by raineorshine** [comment]
This is expected behavior:

> - Closed ranges are replaced with a wildcard:
>   - 1.0.0 < 2.0.0 → ^3.0.0

https://github.com/tjunnone/npm-check-updates#how-dependency-updates-are-determined

**Comment by Kikobeats** [comment]
Then, how to support a range of dependencies properly?

<img width="734" alt="Screenshot 2020-01-17 at 10 23 26" src="https://user-images.githubusercontent.com/2096101/72600194-76e36f80-3913-11ea-9216-72a38dba8f85.png">

**Comment by raineorshine** [comment]
**Breaking** your dependencies is the central feature of `npm-check-updates`, so this is the expected behavior in general. But if you would like to ignore a specific dependency, you can use the reject option:

```
ncu -x styled-components
```
