### ISSUE TITLE
npm Release

### ISSUE THREAD

**Issue by brettz9** [tjunnone/npm-check-updates#629]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: N/A
* npm version: N/A
* npm-check-updates version: N/A

---------------------------

Hi,

Could we get a new npm release? It'd be nice to get the dependency vulnerability fixed in a versioned release.

Thanks!

**Comment by raineorshine** [comment]
Published in `v4.0.2`.
