### ISSUE TITLE
Problem when using another branch

### ISSUE THREAD

**Issue by pwnsdx** [tjunnone/npm-check-updates#63]
Hello,

For example, let's suppose I'm using the 2.0 branch from https://github.com/mongodb/node-mongodb-native, when I run npm-check-updates I will get something like this:
"mongodb" can be updated from ^2.0.15 to ^1.4.32 (Installed: 2.0.15, Latest: 1.4.32)

Is there a way to specify the branch in npm-check-updates or, packages.json please?

Thanks!

**Comment by metaraine** [comment]
Hi! There are two ways to address this:

1. You can ignore the package by filtering out node-mongodb-native:
```sh
$ npm-check-updates -f '/^(?!node-mongodb-native)$/' 
```

2. You can tell npm-check-updates to look for the *highest* version instead of the default *latest* versions (v2.0.0-alpha.7 only)
```sh
$ npm install -g npm-check-updates@unstable
$ npm-check-updates --greatest
```
