### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by garyking** [tjunnone/npm-check-updates#638]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

Please add TypeScript type definitions to this great package. Thanks!

Would you accept types, if I submitted them in a PR?

**Comment by raineorshine** [comment]
Sure! Although I might need some help with setup. I’m not very experienced with typescript.

**Comment by garyking** [comment]
@raineorshine Okay I've submitted the PR.
