### ISSUE TITLE
Support for pnpm ? And what does ncu using the package-lock for ?

### ISSUE THREAD

**Issue by iangregsondev** [tjunnone/npm-check-updates#644]
Hi,

I have just moved over to using pnpm package manager (improved npm package manager)

I was wondering if ncu supports this, i see a lot of reference to updating the package-lock.json - pnpm has its own lock.

Do you know if ncu supports or has been tested with pnpm and other package managers apart from npm.

Thanks.

**Comment by raineorshine** [comment]
`ncu` does not currently support pnpm, but there is a clean interface to add new package managers:
https://github.com/tjunnone/npm-check-updates/tree/master/lib/package-managers

`ncu` does not interact with the lock file. It only reads/updates `package.json`.

**Comment by iangregsondev** [comment]
Hi, thanks for the quick response.

So, in that case, ncu should be compatible with pnpm ?

I mean, if its only looking at the package.json (which pnpm uses) - then its probably OK to use it - right ?

**Comment by raineorshine** [comment]
They are compatible when it comes to the `package.json`. As long as `pnpm` uses the `npm` registry, then the latest versions retrieved will be identical.

**Comment by iangregsondev** [comment]
Thanks @raineorshine
