### ISSUE TITLE
Unhandled promise rejection "The system cannot find the path specified."

### ISSUE THREAD

**Issue by colsen1991** [tjunnone/npm-check-updates#648]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.16.1
* npm version: 6.14.4
* npm-check-updates version: ^3 and ^4 (4.1.2 specifically)
* os: windows 10 home version 1909 build 18363.778

---------------------------
Hi,

I've had a problem for quite some time with version ^3 and ^4 of ncu. Whenever i run `ncu` i get the error "The system cannot find the path specified." in `npm-check-updates.js:412`

Example from version 4.1.2:
```
$ NODE_OPTIONS='--trace-uncaught' ncu --packageFile package.json

C:\Users\colse\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:412
    throw err;
    ^
The system cannot find the path specified.

Thrown at:
    at C:\Users\colse\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:412:5
    at emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```
Same goes for version ^3. Only solution so far has been downgrading to version ^2 and using that. Little confused as to what could be causing this(?).

**Comment by raineorshine** [comment]
It's too bad it doesn't give us more of a stack trace. If it broke in v3 though, it's likely due to this change:

> ### System npm used
> In ncu v2, an internally packaged npm was used for version lookups. When this became out-of-date and differed considerably from the system npm problems would occur. In ncu v3, the system-installed npm will be used for all lookups. This comes with the maintenance cost of needing to upgrade ncu whenever the output format of npm changes.

https://github.com/tjunnone/npm-check-updates/releases/tag/v3.0.0

My best guess is that it cannot find `npm.cmd` in your path for some reason:

https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L121

You may want to try some of the troubleshooting tips for npm on Windows here:

https://stackoverflow.com/questions/39190164/npm-the-system-cannot-find-the-path-specified

**Comment by colsen1991** [comment]
Thanks for the quick reply!

I seem to have found the culprit after some digging; A non existing AutoRun script from an old Conda-installation was the problem. Detailed under this answer https://stackoverflow.com/a/60361398 in the stackoverflow-link you provided. Thought I had ruled out that option, but must've taken a wrong turn in regedit.

Thanks again!

**Comment by raineorshine** [comment]
Yay! Glad you solved it. Damn those non-existent AutoRun scripts! 😂
