### ISSUE TITLE
beta

### ISSUE THREAD

**Issue by lookfirst** [tjunnone/npm-check-updates#66]
I've got:

`"babel-core": "^4.7.16"`

5.0.0-beta1 was just released to npm.

n-c-u tries to update that to the beta, that seems wrong.

**Comment by metaraine** [comment]
I've tried this with both ncu `v1.5.1` and `v2.0.0-alpha.7`. Neither attempts to update `babel-core` to the beta unless the --greatest flag is added, which is the intended behavior.

Are you using one of the above versions of npm-check-updates, and not using the --greatest flag?

**Comment by lookfirst** [comment]
weird... i didn't have a --greatest flag set. anyways, the released version of babel-core has been fixed now, so it is harder to reproduce... i'll close as works-for-you. =)

**Comment by metaraine** [comment]
Thanks
