### ISSUE TITLE
Add cli alias: ncu?

### ISSUE THREAD

**Issue by metaraine** [tjunnone/npm-check-updates#67]
I intend to leave the project name the same, but `npm-check-updates` is a bit annoying to type on the command line. What do you think about having an alias of `ncu`? `npm-check-updates` would still work.

**Comment by XhmikosR** [comment]
:+1:

**Comment by metaraine** [comment]
Done

**Comment by jlukic** [comment]
Just installed and tried `ncu`, command was not found.

Found this thread and tried 
```
$ npm-check-updates
```

Everything worked fine.

I'm assuming this alias is a feature of  `@unstable`. Perhaps readme should reflect this?

**Comment by metaraine** [comment]
Thanks! It's in the readme, but I can see how it could be missed:

    This documentation is for the upcoming v2 release, available on the unstable tag. 
    It is recommended that you install the unstable branch using 
    npm install -g npm-check-updates@unstable in preparation for v2.
