### ISSUE TITLE
custom/private git support

### ISSUE THREAD

**Issue by ludoo0d0a** [tjunnone/npm-check-updates#68]
if dependency is private linked to a custom git then it tries to update to a bad url.

if I have this in my package.json,
```js
"term.js": "git+https://github.com/ludoo0d0a/term.js.git",
```

npm-check-updates -u will give this : 
```js
"term.js" can be updated from git+https://github.com/ludoo0d0a/term.js.git to git+https://github.com/ludoo0.0.4 (Installed: 0.0.4, Latest: 0.0.4)
```

**Comment by metaraine** [comment]
Hi. Thanks for reporting. This has been fixed in the upcoming v2.0.0. You can install the prerelease version with `npm -g install npm-check-updates@unstable`.
