### ISSUE TITLE
Feature Request: Backup (-b) flag

### ISSUE THREAD

**Issue by davetgreen** [tjunnone/npm-check-updates#69]
Hello!

I absolutely love this tool: it's made life so much easier. 

It would be really useful to have a -b flag that creates a backup copy of the file e.g. package_backup.json

You could then run npm-check-updates -u -b to safely upgrade, and have a fall back.

Granted, if you're using version control you can just roll back to an earlier version of the file, but this would be a useful alternative.

Thanks again,
Dave

**Comment by metaraine** [comment]
Hi Dave!

Thanks for the suggestion! I highly recommend using version control as you suggested. I think this provides the best solution. Any package.json you're working with should be part of a git repo so as long as you have well-disciplined commits, it'll be no problem reverting. From this perspective, the -b flag would be superfluous.

Thanks,
Raine

**Comment by raineorshine** [comment]
That also works. 

`git checkout package.json` or `git checkout .` seems simpler to me, but to each their own.
