### ISSUE TITLE
Highlight major/minor level differences

### ISSUE THREAD

**Issue by rragan** [tjunnone/npm-check-updates#7]
Mostly I'm configured to pick up patch changes automatically via semver rules. What this tool also tells  me is if I need to worry about major/minor versions that I'm behind on. However, the output makes these hard to spot as they are interleaved with all the patch level changes I'm behind on but generally are getting. 

Could there be some option to show just versions that would not be picked up by semver rules? Maybe list them in a separate group or have the option to only display them. I can find them now but have to scan a lot of chaff along the way.

**Comment by metaraine** [comment]
I think `npm outdated` should suffice. The only improvement at that point is integrating it into npm-check-updates to have it all in one place, but that doesn't seem to be worth the effort.
