### ISSUE TITLE
Allow specifying registry

### ISSUE THREAD

**Issue by yamalight** [tjunnone/npm-check-updates#70]
Would it be hard to add a way to specify npm registry for checks (similar to `npm --registry http://myregistry.com/`)?

**Comment by metaraine** [comment]
Is seems possible, as nom-check-updates just uses
https://www.npmjs.com/package/npm internally, which is just a wrapper for
the npm cli. It may be able to be specified as a flag or as something on
npm.registry. I do not have immediate availability to look into this, but
if you are able to investigate that would help it along.

Thanks!

-Raine

**Comment by yamalight** [comment]
@metaraine alright, will have a look :)

**Comment by yamalight** [comment]
@metaraine PR #74 submitted, please have a look :)

**Comment by metaraine** [comment]
Thanks!

**Comment by yamalight** [comment]
awesome! was glad to help :)
