### ISSUE TITLE
Add ability to only update packages with non-major version updates

### ISSUE THREAD

**Issue by herbrandson** [tjunnone/npm-check-updates#73]
I often find that when I run npm-check-updates, there will be one or two results that have major version updates (i.e. going from 1.2.0 to 2.0.0). These major updates to packages usually requires more thorough testing and investigating into what the breaking changes are before I'm ready to go ahead with the upgrade. However, with minor version updates or simple patch updates I usually feel much safer about just installing the upgrade and doing a quick smoke test to make sure everything still seems fine.

It would be really nice to have a way to use a variant of -u that would only update packages with a non-major version number update. This would allow me to quickly/easily update packages with non-api breaking changes and then look into the updates that are more severe later.

**Comment by metaraine** [comment]
Hi Eric,

The default semantics of ^ or ~, which allow your package to be updated for
all non-breaking changes, seems like it should handle your situation. i.e.,
if you specify a version in your package.json as “^1.2.0", as I am sure you
are already aware, running "npm update” will update it to 1.2.1, or 1.3.0,
but not 2.0.0. I would recommend relying on this standard semver protocol.
npm-check-updates is really for updating past major version numbers.
Lastly, just rewriting the version in your package.json from “^1.2.0” to
“^1.3.0”, if this is what you are wanting, does not do much, as they will
both hit the same versions between 1.3.0 and 2.0.0. You might as well leave
“^1.2.0” in that case.

-Raine

**Comment by herbrandson** [comment]
Great points Raine! I'll have to think on that a bit. I guess I've been using npm-check-updates a bit differently. I always run npm-check-updates before updating my npm packages because I like to know what's going to be updated and how major of an update it's going to be. For example, if a package is going from 1.0.8 to 1.0.9, I feel pretty safe about the update and won't do much testing. A package going from 1.0.0 to 1.9.4 on the other hand will likely require more testing even though it doesn't have a major version number update (a lot has still changed in 9+ updates).

Based on your feedback, I'm almost wondering if what I really want is to NOT use ^ or ~ at all. However, I realize this may be outside the scope of how you're intending npm-check-updates to be used. That being said, I use this package all of the time (thank you!) and am able to get most of what I want out of it as is. But, adding this feature would be super useful to my workflow ;)

**Comment by metaraine** [comment]
If the package authors are following semver correctly, an update from 1.0.0
to 1.9.4 should not break anything!

You may not want to use ^ or ~ if you want that tight control. Or, you
could only allow patches, instead of minor version updates, by using
something like “1.0.2 < 1.1.0”.

I will leave you with these words though: "Trust in the semver" ;)

**Comment by herbrandson** [comment]
Hah! I guess most days I'd be inclined to agree with you, but just today I hit an issue where a "minor" update to a package caused my app to crash :(

Anyhow, thanks for taking the time to respond! You've definitely given me some things to consider.
