### ISSUE TITLE
Add ability to not check updates for packages which are defined with git urls?

### ISSUE THREAD

**Issue by rasjani** [tjunnone/npm-check-updates#75]
I'd assume that people that use private repositories and/or private npm modules want their module names leaked into npmjs search logs?

Alternatively, if git url is used as root for npm module, update could actually check that particular git repo and see if there are semver based tags available  which are never than what's currently installed..

**Comment by metaraine** [comment]
How are private repositories or repos specified? I don't have experience with this.

**Comment by rasjani** [comment]
Maybe i was bit hasty on the issue description but what i meant:

if the package is defined in package.json with full blown url and not just by version number, there's a good change that the package is not publicly available npm package (in which case it should not be queried from npmjs repo)

**Comment by metaraine** [comment]
Thanks, that makes sense. I agree that full urls should not be searched on
npm.

**Comment by metaraine** [comment]
See #12.
