### ISSUE TITLE
Print release notes between current and latest version if available

### ISSUE THREAD

**Issue by eeroan** [tjunnone/npm-check-updates#76]
This would require parsing i.e. History.md

**Comment by metaraine** [comment]
Good idea! Is there a consistent format to History.md files that can be parsed?

This may be a lower priority item.

**Comment by eeroan** [comment]
I could try to implement this. There's no standard format but I could try to support the most popular formatting styles

**Comment by metaraine** [comment]
Sounds great! Do you think this should be available with a command flag, or
be the default behavior? I’m thinking we may want it to be available with a
-v/--verbose flag.

Also, how do you see the changeling being formatted in the output?

**Comment by eeroan** [comment]
-v sounds great. I guess the first step could be to just show in original format.

Eero Anttila <eea@iki.fi>
+358 50 359 0079

**Comment by sapegin** [comment]
Now more and more projects use GitHub releases for changelogs. It should be easier to get change logs there instead of manually parsing changelog files.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Comment by azachar** [comment]
There is also a https://github.com/conventional-changelog/standard-version project that maintains semversions, perhaps the same logic can be used to display breaking changes, that is what you need the most.
