### ISSUE TITLE
Ignore packages that specify a fork with a specific commit

### ISSUE THREAD

**Issue by RichardLitt** [tjunnone/npm-check-updates#78]
I have this package in my `package.json`: 

```js
"rangy": "git://github.com:RichardLitt/rangy.git#748582f"
```

When I use `npm-check-dependencies`, the following is suggested: 

```sh
"rangy" can be updated from git://github.com:RichardLitt/rangy.git#748582f to git://github.com:RichardLitt/rangy.git#1 (Installed: none, Latest: 1.3.0)
```

This isn't right - I am referencing a specific commit on my fork of `rangy.git`, so there's no update possible.

**Comment by kyriacos** [comment]
:+1: for ignoring packages in general though. I have some very specific packages that i want to completely ignore from being updated....ever.

Actually came along to post that but i found this instead. Could we get some kind of a config file that maybe stores this info?

Thanks!

**Comment by elektronik2k5** [comment]
+1

**Comment by metaraine** [comment]
Agreed. I'm publishing 2.0.0 within the next couple weeks. I'll make sure this gets included. Thanks!

@kyriacos I would suggest using the filter option to ignore certain packages, e.g. `npm-check-updates -f '/^(?!gulp-).*$/'`. Maybe I will add a -fi option for "filter ignore" which makes the regex easier for ignoring packages.

In the mean time, let's track this issue in #12.
