### ISSUE TITLE
Create a tools website

### ISSUE THREAD

**Issue by zckrs** [tjunnone/npm-check-updates#79]
Hi,

Your node modules is really helpful. Thank you.

Do you plane to create a website who use this module with a paste `package.json` ?
That would be awesome to illustrate `npm-check-updates` and serve the community.

I have some ideas for this website. If your are interested we can discuss here or by mail or on Gitter (http://gitter.im/zckrs)

**Comment by metaraine** [comment]
Hi! Thanks for your suggestion. As a developer, I find command line tools
the most efficient, and the README should serve most users who are familiar
with github. Beyond that, I don't see the benefit of creating a website. Do
you think there should be better examples in the README? Thanks!

**Comment by zckrs** [comment]
Nope. README is clear.

I just imagine a website between http://semver.npmjs.com/ and https://david-dm.org/tjunnone/npm-check-updates where we can paste a `package.json`

**Comment by metaraine** [comment]
That’s not a bad idea. I can imagine how it would look as well. However, I
don’t see a case where copying and pasting a package.json would be
preferable to just running nom-check-updates from the command line. Let me
know if I’m missing something, but other than it looking nice, I don’t see
a great practical value.

**Comment by zckrs** [comment]
http://npm.click/
I have missed this tool

**Comment by metaraine** [comment]
There you go! :)
