### ISSUE TITLE
babel-core replaced with babel

### ISSUE THREAD

**Issue by barbalex** [tjunnone/npm-check-updates#81]
I ran "npm-check-updates -u"

babel-core got replaced with babel

See screenshot from GitHub for Windows:
![2015-06-07_22h43_40](https://cloud.githubusercontent.com/assets/669783/8025955/0f42a648-0d67-11e5-80d7-e2bf33f33ef4.png)

Trying to find out the difference between babel and babel-core I got confused when I found two projects:

- Babel (https://www.npmjs.com/package/Babel)
- babel (https://www.npmjs.com/package/babel)

But probably this has nothing to do with the issue

**edit:**

I tried to reproduce the issue:

- set babel back to 4.4.7
- set babel-core back to 4.4.7
- ran "npm-check-updates -u"

and got this in the console:
![console](https://cloud.githubusercontent.com/assets/669783/8026064/b56b170c-0d68-11e5-9986-f1ddfb7f654f.png)

and this in GitHub for Windows:
![git](https://cloud.githubusercontent.com/assets/669783/8026066/bfa112f8-0d68-11e5-9ff4-435eae210346.png)

**Comment by metaraine** [comment]
Thanks! I will investigate.

**Comment by metaraine** [comment]
Could you try with the dev branch and let me know if it still breaks?

`npm install -g npm-check-updates@unstable`

**Comment by barbalex** [comment]
@metaraine bingo: it works
![2015-06-08_19h49_06](https://cloud.githubusercontent.com/assets/669783/8041306/8b160c28-0e17-11e5-9742-2f4bfc0af214.png)

**Comment by metaraine** [comment]
:thumbsup:

On Mon, Jun 8, 2015 at 11:50 AM, Alexander Gabriel <notifications@github.com
