### ISSUE TITLE
Private repo: shouldn't be notified?

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#82]
I've got some private projects and when npm-check-updates checks them, I've got:

`Unable to determine updates for "pmd-player": Error: 404 Not Found: pmd-player`

I'm not sure it's necessary. Is it possible to ignore it?

**Comment by metaraine** [comment]
Can you provide the full key-value pair of this dependency as it appears in
your package.json? Thanks!

**Comment by metaraine** [comment]
In the mean time, feel free to try the dev branch, as it has many
improvements that are soon to be released in v2:
$ sudo npm install -g npm-check-updates@unstable

**Comment by kud** [comment]
`git+ssh://git@repo.org:orga/lib-package#1.4.2`

**Comment by metaraine** [comment]
Yes, it’s fixed in the unstable branch. Thanks!

**Comment by kud** [comment]
Okay, it works with the unstable version so no need to do anything. :) Cheers.

By the way, I didn't know `ncu` existed! It's cool. :D

**Comment by metaraine** [comment]
ncu is new… much better I’d say :)
