### ISSUE TITLE
Don't downgrade

### ISSUE THREAD

**Issue by wemu** [tjunnone/npm-check-updates#84]
Hallo
not sure if this module is wrong or the angular package. But I have this:

$ npm-check-updates 
"angular" can be updated from ~1.4.0 to ~1.3.16 (Installed: 1.4.0, Latest: 1.3.16)
"angular-mocks" can be updated from ~1.4.0 to ~1.3.16 (Installed: 1.4.0, Latest: 1.3.16)

I tried ^1.4.0 or >=1.4.0 for the dependencies but it always wants to go backwards. All other dependencies are ok.

**Comment by metaraine** [comment]
There is a bug in the current version of nom-check-updates that will
downgrade installed packages that are newer than the latest version. The
latest published version of angular is 1.3.16, but there is a beta that has
been published at 1.4.0-rc.2.

You shouldn’t have a problem with v2 of npm-check-updates. It is available
currently with:
$ npm install -g npm-check-updates@unstable

It will ignore any dependencies that are farther ahead than the latest.

To actually check dependencies against the greatest published version, you
can use the --greatest option:
$ npm-check-updates -f angular --greatest

**Comment by wemu** [comment]
thanks for the reply.

I would have expected depending on the semantic version syntax (with those ^ or ~) that 1.3.16 will not be updated to 1.4.0-rc - or alpha/beta something. That seems reasonable to me. But 1.4.0 was released so I was sure after 1.3.16 that version would follow :)

I'll try out the options you mentioned.

Thanks a lot! :+1:

**Comment by metaraine** [comment]
You’re welcome!

You can run `npm view angular` to see that the stable, published version of
angular if currently 1.3.16.
