### ISSUE TITLE
Expose ncu as an API for Gulp/Grunt tasks supporting CI reports

### ISSUE THREAD

**Issue by marcellodesales** [tjunnone/npm-check-updates#85]
Hi there,

Thanks for writing this module... I was looking for something similar and I found your reference in a stackoverflow... So, I'm building shared libraries for different teams to use and this is perfect to include in a CI environment, where each app owner could see exactly what can be upgraded and device when.

Unfortunately our CI police is to have all the dependencies in the project as the CI hosts are disposables... 

1. Do you expose this as an API?
2. Do you have interests/thoughts in exposing it as an API?
3. Do you have anything on that direction?

We don't have direct access to DavidDM for our internal shared libraries nor an Internal NPM registry (compatible with the public one yet)...

thanks
Marcello

**Comment by metaraine** [comment]
Hi Marcello,

I'm not very familiar with CI or know what disposables are, so you'll have to make conclusions yourself, but I can tell you that there is an undocumented API that exports much of the functionality of npm-check-updates. You can find this in [versionmanager.js](https://github.com/tjunnone/npm-check-updates/blob/master/lib/versionmanager.js):

```
initialize
upgradeDependencyDeclaration
updatePackageData
getCurrentDependencies
upgradeDependencies
getInstalledPackages
getLatestPackageVersion
getGreatestPackageVersion
getLatestVersions
isUpgradeable
getPreferredWildcard
```

I was planning on reducing the surface area of the API in the next major release, so if any of these functions are critical for you, please let me know!

-Raine

**Comment by metaraine** [comment]
You can now `require('npm-check-updates')`.

Closing, but let me know if there are specific functions that are important to you, and I will make sure they get included in v2!
