### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#86]
```console
$ ncu
You can now use the alias "ncu" for less typing!
```

**Comment by dozoisch** [comment]
`alias ncu=npm-check-update` ?

**Comment by kud** [comment]
I mean, ncu works well but why it tells me "you can use the alias" when I already use it? :p

**Comment by dozoisch** [comment]
Oh that was really unclear!

**Comment by kud** [comment]
Yeah I know, sorry :D it just made me laugh :p

**Comment by metaraine** [comment]
You don’t need to create an alias for it; the new version installs ncu and
won’t show the message when you type “ncu”. I guess when the alias the
process still sees it as “nom-check-updates” and then tries to be helpful
:).
