### ISSUE TITLE
Is there a way to not upgrade from `^1.0.0` to `^1.1.0` when running with `-u`?

### ISSUE THREAD

**Issue by stevemao** [tjunnone/npm-check-updates#87]
Same to `~1.0.0` to `~1.0.1` because they are not necessary and noisy in git history.

**Comment by mathieumg** [comment]
I think this will be the default behavior in the new 2.0 version.

**Comment by metaraine** [comment]
Yes, this will be controllable in v2, if not the default.

**Comment by stevemao** [comment]
Can you link me what is the duplicate of?

**Comment by metaraine** [comment]
It was sort of mixed in with #83. I'll keep this open so that it can be tracked and closed when it is released. Thanks!

https://github.com/tjunnone/npm-check-updates/issues/83#issuecomment-113539606

**Comment by metaraine** [comment]
This is much more clearly documented in the README now. Closing.
