### ISSUE TITLE
ncu vs npm-check-updates [Can someone with Windows help?]

### ISSUE THREAD

**Issue by metaraine** [tjunnone/npm-check-updates#90]
I saw this output in another issue, but I don't have Windows to test. Can someone with Windows test if you get the following message with npm-check-updates@2.0.0-alpha.10?

    $ ncu
    You can now use "ncu" for less typing!

The "You can now use..." message is only supposed to be shown when you type out the full "npm-check-updates". 

Thank you! If you'd like to be *even more helpful*, can you verify what process.argv returns? The comparison for this is `path.basename(process.argv[1]) === 'npm-check-updates'`, and maybe there is different behavior on Windows.

**Comment by etiktin** [comment]
Yes, that's correct. `ncu.cmd` calls node with .`...\npm-check-updates\\bin\\npm-check-updates`, so `argv[0]= 'node'` and `argv[1] = '...\npm-check-updates\\bin\\npm-check-updates'`. You get exactly the same thing when you use `npm-check-updates.cmd`.

How about changing npm-check-update batch and shell scripts to pass `--notncu` to the startup script? `commander` will parse it and we can replace the argv test with `options.notncu`.

**Comment by metaraine** [comment]
Good to know.

I think we'll have to create a separate executable in ./bin/ that just outputs the warning and then includes the normal program. We can't put --notncu directly in the package.json bin property because it gets symlinked so it must just be the file.

**Comment by etiktin** [comment]
I had some free time, so I took the liberty to fix the issue according to your suggestion.
