### ISSUE TITLE
option to respect policy

### ISSUE THREAD

**Issue by JaKXz** [tjunnone/npm-check-updates#92]
I'm just curious if an option is in the works to respect the `~` or particularly the `^` attached to the package version. e.g:

```bash
$ ncu --respect
"dep1": "^1.2.3" --> ^1.3.4
"dep2": "~1.2.3" --> ~1.2.9
"dep3": "1.2.3" --> 1.2.3
```

It would just skip packages with no policy attached so that you could come back to them afterwards.

This is a great package, regardless. Thanks!

**Comment by metaraine** [comment]
This should be the behavior! Are you seeing something different? Please provide your package.json and I can help troubleshoot.

It will detect which wildcard character you prefer and use that one.

The command line argument is a filter string or regex, but you shouldn't need it in this case.

**Comment by JaKXz** [comment]
This is an example of what I'm seeing:

```bash
$ npm-check-updates
...
"karma-chrome-launcher" can be updated from ~0.1.12 to ~0.2.0 (Installed: 0.1.12, Latest: 0.2.0)
...
```

and my `package.json` looks like this:

```json
...
"karma-chrome-launcher": "~0.1.12"
...
```

**Comment by JaKXz** [comment]
I should also mention I'm using v1.5.1, not the unstable branch. Is that where the functionality is? I apologize, I used `ncu` for brevity but that was unclear.

**Comment by mathieumg** [comment]
In semver, below 1.0, minor versions are considered "major" (i.e. breaking). Thus, `0.2` is like a new major version with regards to `0.1`. Also worthy of note, though I assume you know given the posts above, even if it were `~1.1.12` you'd still see the message to upgrade to `~1.2.0` because of the `~`.

**Comment by metaraine** [comment]
If I understand correctly, you would like to upgrade dependencies while staying within the specified version range. This is the behavior of `npm update`. npm-check-updates exists specifically for the purpose of upgrading *past* the specified version range, to the latest (or highest) published version. 

For most projects I would recommend using `npm update` for normal, nonbreaking upgrades. npm-check-updates is great when starting a new project, or attempting to modernize old project code.

**Comment by metaraine** [comment]
@JaKXz I'm rereading your original issue again and I think I understand better. You want to ignore version numbers that are not wildcards. The regex filter argument is a good solve:

    ncu /[~*^x]/

Let me know if this does not address your issue, otherwise I will close. Thanks!
