### ISSUE TITLE
Interactive mode for the `--upgrade` flag?

### ISSUE THREAD

**Issue by th0r** [tjunnone/npm-check-updates#95]
It would be great if one could type `ncu --upgrade --interactive` and answer `yes/no` for each package that can be updated.

Something like this:
```bash
$ ncu -ui
"babel-runtime" can be updated from 5.6.4 to 5.6.15 (Installed: 5.6.4, Latest: 5.6.15)
Update? [Y/n] Y

"bluebird" can be updated from 2.9.30 to 2.9.32 (Installed: 2.9.30, Latest: 2.9.32)
Update? [Y/n] n
```

**Comment by metaraine** [comment]
I like it! Any interest in doing a pull request? This is an enhancement that probably won't make it into v2 if it's just me working on it.

**Comment by th0r** [comment]
Guys, I've decided to create another module on top of this one, because I wanted a little-bit more functionality than just update `package.json`.
Here it is: https://github.com/th0r/npm-upgrade
It also can show changelog for an outdated module for you to decide whether it should be updated or not.

P.S. Thanks a lot for this great module! It made development or `m much easier!

**Comment by elektronik2k5** [comment]
Awesome! Thank you @th0r

**Comment by metaraine** [comment]
Very cool! Thanks!

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Comment by Primajin** [comment]
I guess we can remove revive-me as this works now as intended by the Author.
