### ISSUE TITLE
Fails to recognize git dependencies on branches correctly

### ISSUE THREAD

**Issue by lookfirst** [tjunnone/npm-check-updates#99]
```
"gulp-ng-html2js" can be updated from git+https://github.com/lookfirst/gulp-ng-html2js#export2 to git+https://github.com/lookfirst/gulp-ng-html0 (Installed: 0.2.0, Latest: 0.2.0)
```

```
    "gulp-ng-html2js": "lookfirst/gulp-ng-html2js#export2"
```

The branch is made `0` so the comparison fails even though there is no new version.

**Comment by metaraine** [comment]
This is a known bug in v1... just hasn't made it's way into stable yet. Should work on the unstable tag until v2 is released!

    npm install -g npm-check-updates@unstable

**Comment by lookfirst** [comment]
I had switched back to stable cause of the other bugs. =)
